"""StateMask-R baseline (explanation + refining) for RICE.

Paper reference
---------------
Cheng et al., *RICE: A Refining Scheme for Reinforcement Learning with
Explanation*, ICML 2024 (PMLR 235).

* **Baseline explanation method** (Sec. 4.1, "Baseline Explanation Methods"):
  "Since our explanation method proposes an alternative design of StateMask, the
  first baseline is StateMask. We compare our explanation method with StateMask
  to show the equivalence and efficiency of our method."  Appendix C.1:
  "as for StateMask, we use their released opensourced code from
  https://github.com/nuwuxian/RL-state_mask".

* **Baseline refining method** (Sec. 4.1, "Baseline Refining Methods"):
  "The second baseline is a refining method introduced by StateMask
  (Cheng et al., 2023), i.e., resetting to the critical state and continuing
  training from the critical state."

So ``StateMask-R`` is the union of the two:

1. ``StateMaskExplainer`` / ``StateMaskTrainer`` — an explanation stage that
   reproduces the *primal-dual* StateMask formulation
   (``min |eta(pi) - eta(pi_bar)|`` solved with a Lagrangian multiplier on the
   blinding reward, as opposed to RICE's vanilla-PPO reformulation
   ``max eta(pi_bar)``, see Sec. 3.3 / Theorem 3.3).  This is the reference for
   Experiment I / Table 4 (fidelity ~= RICE, but 16.8% slower to train).

2. ``StateMaskRefiner`` — a refinement stage that **always** resets to the
   identified critical state (``p = 1`` in the mixed-initial-state rule, i.e. no
   ``rho`` component, no RND bonus) before continuing PPO training.  Per
   Sec. 4.2 Experiment II, "all the refining methods use the same explanation
   generated by our explanation method if needed, to ensure a fair comparison" —
   so when used as a *refining* baseline, this class is fed RICE's mask net.

Only *trends* matter for reproduction (see the plan's validation approach):
StateMask fidelity ~= RICE fidelity > Random; StateMask-R "does not always help
(overfits)" relative to RICE's mixed-initial-distribution refinement.

Everything is written defensively: the module stays importable (and usable for
the Random / RICE branches) even when torch, the mask trainer or the refiner are
unavailable.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Sequence, Tuple, Union

import numpy as np

# --------------------------------------------------------------------------- #
# Optional project imports (defensive: this module must always import)
# --------------------------------------------------------------------------- #

try:  # Stage-1 trainer primitives
    from ..explanation.mask_trainer import (  # type: ignore
        DEFAULT_ALPHA,
        MaskEnv,
        MaskPPOConfig,
        MaskTrainer,
        RolloutBatch,
        compute_gae,
        make_mask_env,
    )

    _HAS_MASK_TRAINER = True
except Exception:  # pragma: no cover - degraded environment
    DEFAULT_ALPHA = 1e-4
    MaskEnv = None  # type: ignore
    MaskPPOConfig = None  # type: ignore
    MaskTrainer = object  # type: ignore
    RolloutBatch = None  # type: ignore
    compute_gae = None  # type: ignore
    make_mask_env = None  # type: ignore
    _HAS_MASK_TRAINER = False

try:  # mask primitives
    from ..explanation.mask_network import (  # type: ignore
        MASK_BLIND,
        MASK_KEEP,
        MaskNetwork,
        masked_action,
    )

    _HAS_MASK_NETWORK = True
except Exception:  # pragma: no cover
    MASK_BLIND = 1
    MASK_KEEP = 0
    MaskNetwork = object  # type: ignore
    masked_action = None  # type: ignore
    _HAS_MASK_NETWORK = False

try:  # critical-state selection (shared with RICE)
    from ..explanation.critical_state import (  # type: ignore
        CriticalState,
        CriticalStateSelector,
        identify_critical_state,
        roll_trajectory,
        top_k_critical_states,
    )

    _HAS_CRITICAL = True
except Exception:  # pragma: no cover
    CriticalState = None  # type: ignore
    CriticalStateSelector = object  # type: ignore
    identify_critical_state = None  # type: ignore
    roll_trajectory = None  # type: ignore
    top_k_critical_states = None  # type: ignore
    _HAS_CRITICAL = False

try:  # importance scoring (used by the explainer facade)
    from ..explanation.importance import (  # type: ignore
        ImportanceScorer,
        aggregate_importance,
        score_trajectory,
    )

    _HAS_IMPORTANCE = True
except Exception:  # pragma: no cover
    ImportanceScorer = None  # type: ignore
    aggregate_importance = None  # type: ignore
    score_trajectory = None  # type: ignore
    _HAS_IMPORTANCE = False

try:  # Stage-2 refiner (reset-to-critical + PPO)
    from ..refining.ppo_refine import (  # type: ignore
        PPORefiner,
        RefinePPOConfig,
        make_refiner,
        unpack_reset,
        unpack_step,
    )

    _HAS_REFINER = True
except Exception:  # pragma: no cover
    PPORefiner = object  # type: ignore
    RefinePPOConfig = None  # type: ignore
    make_refiner = None  # type: ignore
    unpack_reset = None  # type: ignore
    unpack_step = None  # type: ignore
    _HAS_REFINER = False

try:
    from ..utils.io import ensure_dir  # type: ignore
except Exception:  # pragma: no cover
    import os as _os

    def ensure_dir(path: str) -> str:  # type: ignore
        try:
            _os.makedirs(path, exist_ok=True)
        except Exception:
            pass
        return path


try:
    from ..utils.logging import get_logger  # type: ignore
except Exception:  # pragma: no cover
    import logging as _logging

    def get_logger(name: str = "rice", *args: Any, **kwargs: Any):  # type: ignore
        logger = _logging.getLogger(name)
        if not logger.handlers:
            logger.addHandler(_logging.StreamHandler())
        return logger


__all__ = [
    "StateMaskConfig",
    "StateMaskTrainer",
    "train_statemask_network",
    "StateMaskExplainer",
    "make_statemask_explainer",
    "StateMaskRefiner",
    "refine_from_critical_state",
    "StateMaskR",
    "statemask_r_baseline",
    "statemask_r",
    "make_statemask_r",
    "describe_statemask_r",
    "samples_for",
    "DEFAULT_DELTA",
    "DEFAULT_DUAL_LR",
    "DEFAULT_MASK_SAMPLES",
    "DEFAULT_SAMPLES",
]

logger = get_logger("rice.baselines.statemask_r")

# Table 4 (Appendix C.3): number of samples used for training the mask network.
DEFAULT_MASK_SAMPLES: Dict[str, int] = {
    "hopper": 300_000,
    "walker2d": 300_000,
    "reacher": 300_000,
    "halfcheetah": 300_000,
    "selfish_mining": 1_500_000,
    "cage2": 10_000_000,
    "autodriving": 2_443_260,
    "malware_mutation": 32_349,
}
DEFAULT_SAMPLES = 300_000

# Primal-dual (Lagrangian) defaults for reproducing StateMask's formulation
# ``min |eta(pi) - eta(pi_bar)|``.  The released StateMask code exposes the
# multiplier as ``alpha`` (the blinding coefficient); the paper reports
# ``alpha = 0.01`` in Sec. C.3 (Table 3 lists ``1e-4``; ``alpha`` is insensitive
# per Fig. 9 / Sec. 4.3, so either value reproduces the trend).
DEFAULT_DELTA = 0.1          # tolerated *relative* performance gap
DEFAULT_DUAL_LR = 1e-4       # dual (multiplier) step size
DEFAULT_ALPHA_MAX = 10.0
DEFAULT_ALPHA_MIN = 0.0


# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #


@dataclass
class StateMaskConfig:
    """Configuration of the StateMask explanation trainer (primal-dual).

    Mirrors the hyper-parameters of the released StateMask code
    (``nuwuxian/RL-state_mask``): a vanilla PPO inner loop over the binary mask
    actions with reward ``R + alpha * a_t^m``, plus an *adaptive* multiplier
    ``alpha`` that enforces the constraint ``|eta(pi) - eta(pi_bar)| <= delta``
    (the primal-dual reformulation StateMask uses instead of RICE's
    ``max eta(pi_bar)``).

    Fields
    ------
    alpha_init : float
        Initial blinding coefficient (Sec. C.3 uses 0.01).
    dual_lr : float
        Step size of the projected dual update on ``alpha``.
    delta : float
        Tolerated *relative* performance gap ``|eta(pi) - eta(pi_bar)| / |eta(pi)|``.
    alpha_min / alpha_max : float
        Box constraints for the multiplier (dual feasibility ``alpha >= 0``).
    dual_mode : str
        ``"enforce"`` (default): decrease ``alpha`` when the gap exceeds
        ``delta`` (blinding is over-rewarded), increase it when the gap is
        comfortably inside the tolerance.  ``"classic"``: textbook dual ascent
        ``alpha <- alpha + dual_lr * (gap - delta)`` clipped to the box.  Both
        are exposed because the released code does not document its schedule;
        only trends are compared.
    eval_episodes : int
        Number of mask-keep rollouts used to estimate ``eta(pi)`` (cached).
    refresh_every : int
        Re-estimate ``eta(pi)`` every N iterations (0 = never after the first).
    """

    # inner PPO (vanilla) -- inherits RICE/SB3 defaults
    lr: float = 3e-4
    gamma: float = 0.99
    gae_lambda: float = 0.95
    clip_range: float = 0.2
    clip_range_vf: Optional[float] = None
    n_epochs: int = 10
    batch_size: int = 64
    vf_coef: float = 0.5
    ent_coef: float = 0.01
    max_grad_norm: float = 0.5
    normalize_advantage: bool = True
    target_kl: Optional[float] = None
    n_steps: Optional[int] = None
    total_timesteps: int = DEFAULT_SAMPLES
    device: str = "cpu"
    seed: Optional[int] = None
    deterministic_policy: bool = False
    log_interval: int = 1

    # Stage-1 (StateMask specific) hyper-parameters
    alpha_init: float = 0.01
    dual_lr: float = DEFAULT_DUAL_LR
    delta: float = DEFAULT_DELTA
    alpha_min: float = DEFAULT_ALPHA_MIN
    alpha_max: float = DEFAULT_ALPHA_MAX
    dual_mode: str = "enforce"
    use_blinding_bonus: bool = True
    eval_episodes: int = 3
    refresh_every: int = 0
    reward_mode: str = "augmented"

    @classmethod
    def from_dict(cls, cfg: Optional[Any] = None, **overrides: Any) -> "StateMaskConfig":
        """Build from a (possibly nested) YAML/dict config.

        Accepts the sections ``statemask`` / ``state_mask`` / ``mask_trainer`` /
        ``explanation`` / ``mask`` and the aliases ``alpha``/``lambda``,
        ``lr``/``learning_rate``, ``clip``, and ``dual_learning_rate``.
        """
        data: Dict[str, Any] = {}
        if cfg is not None:
            if isinstance(cfg, StateMaskConfig):
                data.update(cfg.to_dict())
            elif hasattr(cfg, "to_dict"):
                try:
                    nested = cfg.to_dict()
                    if isinstance(nested, dict):
                        data.update(nested)
                except Exception:
                    pass
            if isinstance(cfg, dict):
                data.update(cfg)
                for sect in ("statemask", "state_mask", "mask_trainer", "explanation", "mask"):
                    inner = cfg.get(sect)
                    if isinstance(inner, dict):
                        data.update(inner)
        data.update({k: v for k, v in overrides.items() if v is not None})

        # aliases
        alias = {
            "learning_rate": "lr",
            "lr_mask": "lr",
            "clip": "clip_range",
            "alpha": "alpha_init",
            "lambda": "alpha_init",
            "lambda_": "alpha_init",
            "dual_learning_rate": "dual_lr",
            "tolerance": "delta",
            "budget": "delta",
        }
        for src, dst in alias.items():
            if src in data and dst not in data:
                data[dst] = data[src]

        valid = set(getattr(cls, "__dataclass_fields__", {}).keys())
        kwargs = {k: v for k, v in data.items() if k in valid}
        return cls(**kwargs)

    def to_dict(self) -> Dict[str, Any]:
        return {f: getattr(self, f) for f in getattr(self, "__dataclass_fields__", {})}

    # ---- convenience aliases -------------------------------------------------
    @property
    def alpha(self) -> float:
        """Current multiplier (kept for API symmetry with ``MaskPPOConfig``)."""
        return float(getattr(self, "_alpha", self.alpha_init))

    @alpha.setter
    def alpha(self, value: float) -> None:
        self._alpha = float(value)

    @property
    def samples(self) -> int:
        return int(self.total_timesteps)


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #


def samples_for(env_id: Optional[str], default: int = DEFAULT_SAMPLES) -> int:
    """Table-4 sample budget for the mask-network training of a given env."""
    key = str(env_id or "").split("-")[0].split("/")[-1].replace(".yaml", "").strip().lower()
    for name, value in DEFAULT_MASK_SAMPLES.items():
        if name in key:
            return int(value)
    return int(default)


def _mean(values: Sequence[float]) -> float:
    vals = [float(v) for v in values if v is not None and np.isfinite(v)]
    return float(np.mean(vals)) if vals else float("nan")


def _unpack_step(result: Any) -> Tuple[Any, float, bool, bool, Dict[str, Any]]:
    """Normalise 4-tuple / 5-tuple gym step outputs."""
    if unpack_step is not None:
        try:
            return unpack_step(result)  # type: ignore[misc]
        except Exception:
            pass
    if not isinstance(result, (tuple, list)):
        return result, 0.0, False, False, {}
    if len(result) == 5:
        obs, reward, terminated, truncated, info = result
        return obs, float(reward), bool(terminated), bool(truncated), dict(info or {})
    if len(result) == 4:
        obs, reward, done, info = result
        return obs, float(reward), bool(done), False, dict(info or {})
    raise ValueError(f"Unsupported step tuple of length {len(result)}")


def _unpack_reset(result: Any) -> Tuple[Any, Dict[str, Any]]:
    if isinstance(result, (tuple, list)) and len(result) == 2:
        obs, info = result
        return obs, dict(info or {})
    return result, {}


def _flat(obs: Any) -> np.ndarray:
    try:
        from ..explanation.mask_network import flatten_observation  # type: ignore

        return flatten_observation(obs)
    except Exception:
        arr = np.asarray(obs, dtype=np.float32)
        return arr.reshape(-1) if arr.ndim > 1 else arr


# --------------------------------------------------------------------------- #
# StateMask trainer (primal-dual)
# --------------------------------------------------------------------------- #


class StateMaskTrainer(MaskTrainer):  # type: ignore[misc]
    """StateMask explanation trainer: vanilla PPO inner loop + dual update on ``alpha``.

    This reproduces the *primal-dual* scheme the paper attributes to StateMask
    (``min |eta(pi) - eta(pi_bar)|``) as opposed to RICE's ``max eta(pi_bar)``
    reformulation (Sec. 3.3 / Theorem 3.3).  The mask-network parameters are
    optimized with vanilla PPO on the augmented reward
    ``R'_t = R(s_t, a_t) + alpha * a_t^m`` exactly like
    :class:`rice.explanation.mask_trainer.MaskTrainer`; the difference is that
    ``alpha`` is a *Lagrangian multiplier* recomputed after every iteration from
    the measured performance gap between the original policy and the perturbed
    (masked) policy — this extra dual optimisation is what makes StateMask
    slower than RICE for a fixed sample budget (Table 4: 16.8% on average).

    Parameters mirror :class:`MaskTrainer`; ``config`` may be a
    :class:`StateMaskConfig`, a dict, or a :class:`MaskPPOConfig`.
    """

    def __init__(
        self,
        env: Any,
        target_policy: Any,
        mask_net: Any = None,
        critic: Any = None,
        config: Optional[Any] = None,
        env_id: str = "default",
        device: str = "cpu",
        logger: Any = None,
        observation_space: Any = None,
        action_space: Any = None,
        discrete: Optional[bool] = None,
        seed: Optional[int] = None,
        store_dataset: bool = True,
        **kwargs: Any,
    ) -> None:
        if not _HAS_MASK_TRAINER:
            raise ImportError(
                "StateMaskTrainer requires rice.explanation.mask_trainer "
                "(PyTorch + the RICE explanation package)."
            )

        sm_cfg = (
            config
            if isinstance(config, StateMaskConfig)
            else StateMaskConfig.from_dict(config if config is not None else kwargs)
        )
        inner = (
            MaskPPOConfig.from_dict(sm_cfg.to_dict())
            if MaskPPOConfig is not None
            else sm_cfg
        )
        try:
            inner.alpha = float(sm_cfg.alpha_init)  # type: ignore[attr-defined]
        except Exception:
            pass

        super().__init__(  # type: ignore[misc]
            env=env,
            target_policy=target_policy,
            mask_net=mask_net,
            critic=critic,
            config=inner,
            env_id=env_id,
            device=device,
            logger=logger,
            observation_space=observation_space,
            action_space=action_space,
            discrete=discrete,
            seed=seed,
            store_dataset=store_dataset,
            **kwargs,
        )

        self.sm_config = sm_cfg
        self.delta = float(sm_cfg.delta)
        self.dual_lr = float(sm_cfg.dual_lr)
        self.alpha_min = float(sm_cfg.alpha_min)
        self.alpha_max = float(sm_cfg.alpha_max)
        self.dual_mode = str(sm_cfg.dual_mode)

        self.original_return: Optional[float] = None
        self.gap_history: List[float] = []
        self.alpha_history: List[float] = []
        self._gap_measurements = 0

        self._apply_alpha(float(sm_cfg.alpha_init))

    # ------------------------------------------------------------------ utils
    def _mask_env(self) -> Any:
        for attr in ("mask_env", "masked_env", "train_env"):
            env = getattr(self, attr, None)
            if env is not None:
                return env
        env = getattr(self, "env", None)
        if env is not None and MaskEnv is not None and isinstance(env, MaskEnv):
            return env
        return None

    def _apply_alpha(self, alpha: float) -> float:
        """Push the current multiplier into the trainer/config/mask-env."""
        self.alpha = float(np.clip(alpha, self.alpha_min, self.alpha_max))
        cfg = getattr(self, "config", None)
        if cfg is not None:
            try:
                cfg.alpha = self.alpha
            except Exception:
                pass
        env = self._mask_env()
        if env is not None:
            if hasattr(env, "set_alpha"):
                try:
                    env.set_alpha(self.alpha)
                except Exception:
                    env.alpha = self.alpha  # type: ignore[attr-defined]
            else:
                env.alpha = self.alpha  # type: ignore[attr-defined]
        self.alpha_history.append(self.alpha)
        return self.alpha

    # ------------------------------------------------- policy return estimates
    def measure_original_return(
        self,
        n_episodes: Optional[int] = None,
        max_steps: Optional[int] = None,
        deterministic: bool = False,
    ) -> float:
        """Estimate ``eta(pi)`` by rolling the frozen policy with mask = keep.

        Equivalent to evaluating the pre-trained policy: with ``a_t^m = 0`` the
        masked action equals the target action and the blinding bonus vanishes.
        """
        env = self._mask_env()
        if env is None:
            return float("nan")
        n_episodes = int(n_episodes or self.sm_config.eval_episodes)
        if max_steps is None:
            max_steps = int(getattr(self.config, "n_steps", None) or 1000)

        rewards: List[float] = []
        for ep in range(max(1, n_episodes)):
            try:
                if hasattr(env, "seed"):
                    env.seed(int(getattr(self, "seed", 0) or 0) + ep)
            except Exception:
                pass
            try:
                obs, _ = _unpack_reset(env.reset())
            except Exception:
                break
            ep_ret, steps, done = 0.0, 0, False
            while not done and steps < max_steps:
                obs, reward, terminated, truncated, info = _unpack_step(
                    env.step(MASK_KEEP)
                )
                ep_ret += float(info.get("task_reward", reward))
                done = bool(terminated or truncated)
                steps += 1
            rewards.append(ep_ret)

        self._gap_measurements += 1
        value = _mean(rewards)
        if np.isfinite(value):
            self.original_return = value
        return float(self.original_return if self.original_return is not None else value)

    def perturbed_return(self, batch: Any = None) -> float:
        """Estimate ``eta(pi_bar)`` from the freshly collected perturbed rollout."""
        if batch is not None:
            for attr in ("episode_task_returns", "episode_returns", "episode_augmented_returns"):
                values = getattr(batch, attr, None)
                if values is not None and len(values) > 0:
                    return _mean(values)
            task_rewards = getattr(batch, "task_rewards", None)
            if task_rewards is not None and len(task_rewards) > 0:
                n_steps = float(getattr(self.config, "n_steps", None) or 1000)
                n_ep = max(1.0, len(task_rewards) / n_steps)
                return float(np.sum(task_rewards) / n_ep)
        return float("nan")

    # ------------------------------------------------------------ dual update
    def dual_update(self, gap: float) -> float:
        """Projected (dual) update of the blinding multiplier ``alpha``.

        ``gap = eta(pi) - eta(pi_bar)`` (positive when perturbing hurts).
        Stored as a *relative* gap ``gap / |eta(pi)|`` so ``delta`` is
        scale-free across applications.
        """
        if not np.isfinite(gap):
            return self.alpha

        ref = self.original_return
        if ref is not None and np.isfinite(ref) and abs(float(ref)) > 1e-8:
            rel_gap = float(gap) / abs(float(ref))
        else:
            rel_gap = float(gap)

        violation = abs(rel_gap) - self.delta
        if self.dual_mode == "classic":
            new_alpha = self.alpha + self.dual_lr * violation
        else:  # "enforce" (default): blinding only pays while performance holds
            new_alpha = self.alpha - self.dual_lr * violation

        self.gap_history.append(float(rel_gap))
        self._apply_alpha(float(new_alpha))
        return self.alpha

    # -------------------------------------------------------------- main loop
    def train(  # type: ignore[override]
        self,
        total_timesteps: Optional[int] = None,
        total_iterations: Optional[int] = None,
        logger: Any = None,
        progress: bool = False,
        **kwargs: Any,
    ) -> List[Dict[str, Any]]:
        """StateMask training loop = RICE loop + per-iteration dual update."""
        log = logger or getattr(self, "logger", None) or globals()["logger"]
        steps_target = int(
            total_timesteps
            or getattr(self.config, "total_timesteps", DEFAULT_SAMPLES)
            or DEFAULT_SAMPLES
        )
        n_steps = int(getattr(self.config, "n_steps", None) or kwargs.get("n_steps") or 1000)
        if total_iterations is None:
            total_iterations = max(1, int(math.ceil(steps_target / max(1, n_steps))))

        # eta(pi) is a property of the frozen pre-trained policy: estimate once.
        self.measure_original_return()

        history: List[Dict[str, Any]] = []
        for iteration in range(int(total_iterations)):
            batch = self.collect_rollout()
            stats = dict(self.update(batch) or {})

            perturbed = self.perturbed_return(batch)
            if self.original_return is not None and np.isfinite(perturbed):
                gap: float = float(self.original_return) - float(perturbed)
            else:
                gap = float("nan")
            alpha_before = self.alpha
            self.dual_update(gap)

            stats.update(
                {
                    "statemask/iteration": iteration,
                    "statemask/alpha": float(self.alpha),
                    "statemask/alpha_before": float(alpha_before),
                    "statemask/dual_gap": float(gap),
                    "statemask/original_return": float(self.original_return or float("nan")),
                    "statemask/perturbed_return": float(perturbed),
                    "statemask/dual_step": float(self.alpha - alpha_before),
                }
            )
            history.append(stats)

            if self.sm_config.refresh_every and (iteration + 1) % int(self.sm_config.refresh_every) == 0:
                self.measure_original_return()

            if progress and self.sm_config.log_interval:
                try:
                    log.info(
                        "[StateMask] iter %d/%d alpha=%.5f gap=%.4f",
                        iteration + 1,
                        int(total_iterations),
                        self.alpha,
                        gap,
                    )
                except Exception:
                    pass

        return history

    # ------------------------------------------------------------- reporting
    def dual_report(self) -> Dict[str, Any]:
        return {
            "alpha_final": float(self.alpha),
            "alpha_init": float(self.sm_config.alpha_init),
            "alpha_history": [float(a) for a in self.alpha_history],
            "gap_history": [float(g) for g in self.gap_history],
            "mean_gap": _mean(self.gap_history),
            "original_return": (
                float(self.original_return) if self.original_return is not None else float("nan")
            ),
            "dual_mode": self.dual_mode,
            "delta": float(self.delta),
            "dual_lr": float(self.dual_lr),
            "n_dual_updates": len(self.gap_history),
        }

    def summary(self) -> Dict[str, Any]:  # type: ignore[override]
        try:
            base: Dict[str, Any] = dict(super().summary() or {})
        except Exception:
            base = {}
        base.update(self.dual_report())
        if hasattr(self, "time_report"):
            try:
                base.update(self.time_report())
            except Exception:
                pass
        return base


# --------------------------------------------------------------------------- #
# Training factory
# --------------------------------------------------------------------------- #


def train_statemask_network(
    env: Any,
    target_policy: Any,
    total_timesteps: Optional[int] = None,
    alpha: float = 0.01,
    env_id: str = "default",
    config: Optional[Any] = None,
    logger: Any = None,
    save_path: Optional[str] = None,
    seed: Optional[int] = None,
    device: str = "cpu",
    store_dataset: bool = False,
    progress: bool = False,
    mask_net: Any = None,
    critic: Any = None,
    **kwargs: Any,
) -> Tuple[Any, "StateMaskTrainer"]:
    """Train a StateMask-style mask network (primal-dual) and return ``(net, trainer)``.

    ``total_timesteps`` defaults to the Table-4 sample budget for ``env_id``
    (3x10^5 for the MuJoCo games).  ``alpha`` is the *initial* multiplier.
    """
    if not _HAS_MASK_TRAINER:
        raise ImportError("train_statemask_network requires rice.explanation.mask_trainer")

    cfg = StateMaskConfig.from_dict(config, **kwargs)
    cfg.alpha_init = float(alpha)
    if total_timesteps is None:
        total_timesteps = samples_for(env_id, int(cfg.total_timesteps or DEFAULT_SAMPLES))
    cfg.total_timesteps = int(total_timesteps)

    trainer = StateMaskTrainer(
        env=env,
        target_policy=target_policy,
        mask_net=mask_net,
        critic=critic,
        config=cfg,
        env_id=env_id,
        device=device,
        logger=logger,
        seed=seed,
        store_dataset=store_dataset,
    )
    trainer.train(total_timesteps=total_timesteps, progress=progress)

    if save_path:
        try:
            trainer.save(save_path)  # type: ignore[attr-defined]
        except Exception as exc:  # pragma: no cover
            (logger or globals()["logger"]).warning(
                "could not save StateMask checkpoint: %s", exc
            )

    return trainer.mask_net, trainer  # type: ignore[attr-defined]


# --------------------------------------------------------------------------- #
# Explanation facade (drop-in for the RICE explanation in the exp drivers)
# --------------------------------------------------------------------------- #


class StateMaskExplainer:
    """Explanation-method facade backed by a StateMask-trained mask network.

    Exposes the same surface as the RICE explanation
    (:class:`rice.explanation.importance.ImportanceScorer` +
    :class:`rice.explanation.critical_state.CriticalStateSelector`) so experiment
    drivers can swap ``{Random, StateMask, Ours}`` transparently
    (Sec. 4.2 Experiment III / Table 6).
    """

    name = "StateMask"

    def __init__(
        self,
        mask_net: Any = None,
        env: Any = None,
        policy: Any = None,
        env_id: str = "default",
        K: Optional[int] = None,
        deterministic_policy: bool = False,
        rng: Any = None,
        seed: Optional[int] = None,
        attach_scores: bool = True,
        batch_size: int = 4096,
        trainer: Any = None,
    ) -> None:
        self.mask_net = mask_net
        self.env = env
        self.policy = policy
        self.env_id = env_id
        self.K = K
        self.deterministic_policy = bool(deterministic_policy)
        self.rng = rng
        self.seed = seed
        self.trainer = trainer

        self.scorer: Any = None
        if _HAS_IMPORTANCE and mask_net is not None and ImportanceScorer is not None:
            try:
                self.scorer = ImportanceScorer(mask_net=mask_net, batch_size=batch_size)
            except Exception:
                self.scorer = None

        self.selector: Any = None
        if _HAS_CRITICAL and env is not None and CriticalStateSelector is not None:
            try:
                self.selector = CriticalStateSelector(  # type: ignore[misc]
                    env=env,
                    mask_net=mask_net,
                    K=K,
                    scorer=self.scorer,
                    deterministic_policy=self.deterministic_policy,
                    rng=rng,
                    attach_scores=attach_scores,
                )
            except Exception:
                self.selector = None

        self._history: List[Dict[str, Any]] = []

    # ------------------------------------------------------------------ scores
    def score(self, observations: Any) -> np.ndarray:
        """Step-level importance ``P(a_t^m = 0 | s_t)`` for each observation."""
        if self.mask_net is None:
            arr = np.asarray(observations)
            n = arr.shape[0] if arr.ndim > 1 else 1
            return np.ones(int(n), dtype=np.float64)
        if self.scorer is not None:
            try:
                return np.asarray(self.scorer.score(observations), dtype=np.float64)
            except Exception:
                pass
        try:
            from ..explanation.mask_network import state_importance  # type: ignore

            return np.asarray(state_importance(self.mask_net, observations), dtype=np.float64)
        except Exception:
            return np.ones(1, dtype=np.float64)

    def score_trajectory(self, trajectory: Any) -> np.ndarray:
        if _HAS_IMPORTANCE and score_trajectory is not None and self.mask_net is not None:
            try:
                return np.asarray(score_trajectory(self.mask_net, trajectory), dtype=np.float64)
            except Exception:
                pass
        obs = getattr(trajectory, "observations", trajectory)
        return self.score(obs)

    def importance_scores(self, trajectory: Any) -> np.ndarray:
        return self.score_trajectory(trajectory)

    def rank(self, trajectory: Any) -> np.ndarray:
        return np.argsort(-self.score_trajectory(trajectory), kind="mergesort")

    def top_k_states(self, trajectory: Any, k: int = 10) -> List[Any]:
        scores = self.score_trajectory(trajectory)
        order = np.argsort(-scores, kind="mergesort")[: max(1, int(k))]
        obs = getattr(trajectory, "observations", np.asarray(trajectory))
        return [np.asarray(obs[int(i)]) for i in order]

    # -------------------------------------------------------------- selection
    def rollout(self, policy: Any = None, K: Optional[int] = None, **kwargs: Any) -> Any:
        if self.selector is not None:
            return self.selector.rollout(policy=policy or self.policy, K=K or self.K, **kwargs)
        if _HAS_CRITICAL and roll_trajectory is not None and self.env is not None:
            return roll_trajectory(
                self.env,
                policy or self.policy,
                length=K or self.K,
                deterministic=self.deterministic_policy,
                **kwargs,
            )
        raise RuntimeError("StateMaskExplainer.rollout requires an environment")

    def select(
        self,
        policy: Any = None,
        K: Optional[int] = None,
        reset: bool = True,
        seed: Optional[int] = None,
        rollout: Any = None,
        **kwargs: Any,
    ) -> Any:
        """Critical state = argmax-importance state of a length-K ``pi`` rollout."""
        if self.selector is not None:
            critical = self.selector.select(
                policy=policy or self.policy,
                K=K or self.K,
                reset=reset,
                seed=seed,
                rollout=rollout,
            )
        elif _HAS_CRITICAL and identify_critical_state is not None and self.env is not None:
            critical = identify_critical_state(  # type: ignore[misc]
                self.env,
                policy or self.policy,
                mask_net=self.mask_net,
                K=K or self.K,
                deterministic=self.deterministic_policy,
                reset=reset,
                seed=seed,
            )
        else:
            raise RuntimeError("StateMaskExplainer.select requires an environment")
        self._history.append(
            {
                "env_id": self.env_id,
                "K": K or self.K,
                "impact": float(getattr(critical, "score", float("nan"))),
            }
        )
        return critical

    def select_top_k(
        self, k: int = 10, policy: Any = None, K: Optional[int] = None, **kwargs: Any
    ) -> List[Any]:
        rollout = self.rollout(policy=policy, K=K, **kwargs)
        if _HAS_CRITICAL and top_k_critical_states is not None:
            return top_k_critical_states(rollout, mask_net=self.mask_net, k=k)
        scores = self.score_trajectory(rollout)
        order = np.argsort(-scores, kind="mergesort")[: max(1, int(k))]
        obs = getattr(rollout, "observations", np.asarray(rollout))
        return [np.asarray(obs[int(i)]) for i in order]

    def identify(
        self, env: Any = None, policy: Any = None, K: Optional[int] = None, **kwargs: Any
    ) -> Any:
        self.env = env or self.env
        self.policy = policy or self.policy
        self.K = K or self.K
        if (
            self.selector is None
            and _HAS_CRITICAL
            and CriticalStateSelector is not None
            and self.env is not None
        ):
            try:
                self.selector = CriticalStateSelector(  # type: ignore[misc]
                    env=self.env,
                    mask_net=self.mask_net,
                    K=self.K,
                    scorer=self.scorer,
                    deterministic_policy=self.deterministic_policy,
                    rng=self.rng,
                )
            except Exception:
                self.selector = None
        return self.select(policy=self.policy, K=self.K, **kwargs)

    identify_critical_state = identify

    def reset_to(self, env: Any = None, critical: Any = None, **kwargs: Any) -> Any:
        if self.selector is not None and hasattr(self.selector, "reset_to"):
            return self.selector.reset_to(env or self.env, critical, **kwargs)
        target = env or self.env
        if target is not None and hasattr(target, "reset_to"):
            return target.reset_to(critical, **kwargs)
        if target is not None:
            return _unpack_reset(target.reset())
        raise RuntimeError("StateMaskExplainer.reset_to requires a resettable env")

    def statistics(self) -> Dict[str, Any]:
        stats: Dict[str, Any] = {
            "name": self.name,
            "env_id": self.env_id,
            "n_selections": len(self._history),
        }
        if self.selector is not None and hasattr(self.selector, "summary"):
            try:
                stats["selector"] = self.selector.summary()
            except Exception:
                pass
        if self.trainer is not None and hasattr(self.trainer, "dual_report"):
            try:
                stats["dual"] = self.trainer.dual_report()
            except Exception:
                pass
        return stats

    stats = statistics

    def describe(self) -> str:
        return (
            f"StateMask explanation (env={self.env_id}, "
            f"mask={'trained' if self.mask_net is not None else 'none'})"
        )


def make_statemask_explainer(
    env: Any = None,
    policy: Any = None,
    mask_net: Any = None,
    env_id: str = "default",
    K: Optional[int] = None,
    seed: Optional[int] = None,
    **kwargs: Any,
) -> StateMaskExplainer:
    return StateMaskExplainer(
        mask_net=mask_net, env=env, policy=policy, env_id=env_id, K=K, seed=seed, **kwargs
    )


# --------------------------------------------------------------------------- #
# Refining facade (reset-to-critical-state + continue PPO)
# --------------------------------------------------------------------------- #


class StateMaskRefiner:
    """StateMask refining baseline: **always** reset to the critical state.

    Paper (Sec. 4.1): "The second baseline is a refining method introduced by
    StateMask (Cheng et al., 2023), i.e., resetting to the critical state and
    continuing training from the critical state."  In the mixed-initial-state
    rule ``mu(s) = beta * d_rho^pihat(s) + (1 - beta) * rho(s)`` this is
    ``beta = 1`` (here ``p = 1``), with no RND exploration bonus and no ``rho``
    component (Sec. 4.2 Exp. IV: RICE's PPO switch with mixed init "breaks the
    bottleneck" whereas this baseline overfits and "does not always help").

    Per Sec. 4.2 (Experiment II) the *explanation* used here is the same as for
    every other refiner (RICE's mask net), which is why ``mask_net`` is the
    primary input.
    """

    name = "StateMask-R"

    def __init__(
        self,
        env: Any = None,
        policy: Any = None,
        mask_net: Any = None,
        config: Optional[Any] = None,
        env_id: str = "default",
        device: str = "cpu",
        logger: Any = None,
        sampler: Any = None,
        explainer: Any = None,
        use_rnd: bool = False,
        seed: Optional[int] = None,
        **kwargs: Any,
    ) -> None:
        if not _HAS_REFINER:
            raise ImportError("StateMaskRefiner requires rice.refining.ppo_refine (PPORefiner)")

        cfg = (
            RefinePPOConfig.from_dict(config, **kwargs)
            if (RefinePPOConfig is not None and not isinstance(config, RefinePPOConfig))
            else (config if config is not None else (RefinePPOConfig() if RefinePPOConfig else None))
        )
        # beta = 1  ->  always start from the critical state
        for attr, value in (
            ("p", 1.0),
            ("beta", 1.0),
            ("use_mixed_init", True),
            ("use_rnd", bool(use_rnd)),
            ("copy_policy", True),
        ):
            try:
                setattr(cfg, attr, value)
            except Exception:
                pass

        self.mask_net = mask_net
        self.explainer = explainer or (
            make_statemask_explainer(
                env=env, policy=policy, mask_net=mask_net, env_id=env_id, seed=seed
            )
            if env is not None
            else None
        )
        self.refiner = PPORefiner(  # type: ignore[misc]
            env=env,
            policy=policy,
            mask_net=mask_net,
            config=cfg,
            env_id=env_id,
            device=device,
            logger=logger,
            sampler=sampler,
            seed=seed,
            **kwargs,
        )
        try:
            self.refiner.set_p(1.0)
        except Exception:
            pass
        self.env_id = env_id

    # --------------------------------------------------------------- training
    def train(self, *args: Any, **kwargs: Any) -> Any:
        return self.refiner.train(*args, **kwargs)  # type: ignore[attr-defined]

    fit = train

    def evaluate(self, *args: Any, **kwargs: Any) -> Dict[str, float]:
        return self.refiner.evaluate(*args, **kwargs)  # type: ignore[attr-defined]

    @property
    def policy(self) -> Any:
        return getattr(self.refiner, "policy", None)

    def summary(self) -> Dict[str, Any]:
        out: Dict[str, Any] = {"name": self.name, "env_id": self.env_id, "p": 1.0}
        try:
            out.update(self.refiner.summary())  # type: ignore[attr-defined]
        except Exception:
            pass
        return out

    def save(self, path: str, extra: Optional[Dict[str, Any]] = None) -> str:
        return self.refiner.save(path, extra=extra)  # type: ignore[attr-defined]


def refine_from_critical_state(
    env: Any,
    policy: Any = None,
    mask_net: Any = None,
    total_timesteps: Optional[int] = None,
    total_iterations: Optional[int] = None,
    env_id: str = "default",
    config: Optional[Any] = None,
    logger: Any = None,
    save_path: Optional[str] = None,
    seed: Optional[int] = None,
    device: str = "cpu",
    progress: bool = False,
    evaluate: bool = False,
    eval_episodes: int = 10,
    use_rnd: bool = False,
    **kwargs: Any,
) -> Tuple[Any, "StateMaskRefiner"]:
    """StateMask-R refining: reset to the critical state and keep training PPO."""
    refiner = StateMaskRefiner(
        env=env,
        policy=policy,
        mask_net=mask_net,
        config=config,
        env_id=env_id,
        device=device,
        logger=logger,
        use_rnd=use_rnd,
        seed=seed,
        **kwargs,
    )
    train_kwargs: Dict[str, Any] = {"progress": progress}
    if total_timesteps is not None:
        train_kwargs["total_timesteps"] = int(total_timesteps)
    if total_iterations is not None:
        train_kwargs["total_iterations"] = int(total_iterations)
    refiner.train(**train_kwargs)

    if evaluate:
        try:
            refiner.evaluate(n_episodes=eval_episodes)
        except Exception as exc:  # pragma: no cover
            (logger or globals()["logger"]).warning("StateMask-R evaluation failed: %s", exc)

    if save_path:
        try:
            refiner.save(save_path)
        except Exception as exc:  # pragma: no cover
            (logger or globals()["logger"]).warning(
                "could not save StateMask-R checkpoint: %s", exc
            )

    return refiner.policy, refiner


# --------------------------------------------------------------------------- #
# Umbrella baseline (explanation + refining), mirroring the RICE pipeline
# --------------------------------------------------------------------------- #


class StateMaskR:
    """End-to-end StateMask-R baseline: StateMask explanation + reset-to-critical refining.

    Usage::

        baseline = StateMaskR(env_id="hopper")
        mask_net, trainer = baseline.train_explanation(env, target_policy)   # Stage 1
        policy, refiner = baseline.refine(env, target_policy, mask_net)      # Stage 2
    """

    name = "StateMask-R"

    def __init__(
        self,
        env_id: str = "default",
        config: Optional[Any] = None,
        seed: Optional[int] = None,
        device: str = "cpu",
        logger: Any = None,
        mask_samples: Optional[int] = None,
        alpha: float = 0.01,
        use_rnd: bool = False,
        **kwargs: Any,
    ) -> None:
        self.env_id = env_id
        self.config = config
        self.seed = seed
        self.device = device
        self.logger = logger
        self.alpha = float(alpha)
        self.use_rnd = bool(use_rnd)
        self.mask_samples = int(mask_samples if mask_samples is not None else samples_for(env_id))

        self.mask_net: Any = None
        self.trainer: Optional[StateMaskTrainer] = None
        self.explainer: Optional[StateMaskExplainer] = None
        self.refiner: Optional[StateMaskRefiner] = None
        self.refined_policy: Any = None
        self.history: List[Dict[str, Any]] = []

    # --------------------------------------------------------------- stage 1
    def train_explanation(
        self,
        env: Any,
        target_policy: Any,
        total_timesteps: Optional[int] = None,
        progress: bool = False,
        save_path: Optional[str] = None,
        **kwargs: Any,
    ) -> Tuple[Any, "StateMaskTrainer"]:
        self.mask_net, self.trainer = train_statemask_network(
            env=env,
            target_policy=target_policy,
            total_timesteps=total_timesteps or self.mask_samples,
            alpha=self.alpha,
            env_id=self.env_id,
            config=self.config,
            logger=self.logger,
            save_path=save_path,
            seed=self.seed,
            device=self.device,
            progress=progress,
            **kwargs,
        )
        # frozen pi identifies critical states for the explainer
        self.explainer = make_statemask_explainer(
            env=env,
            policy=getattr(self.trainer, "target_policy", target_policy),
            mask_net=self.mask_net,
            env_id=self.env_id,
            seed=self.seed,
            trainer=self.trainer,
        )
        self.history.append(self.trainer.dual_report())
        return self.mask_net, self.trainer

    # --------------------------------------------------------------- stage 2
    def refine(
        self,
        env: Any,
        target_policy: Any,
        mask_net: Any = None,
        total_timesteps: Optional[int] = None,
        total_iterations: Optional[int] = None,
        progress: bool = False,
        evaluate: bool = False,
        eval_episodes: int = 10,
        save_path: Optional[str] = None,
        **kwargs: Any,
    ) -> Tuple[Any, "StateMaskRefiner"]:
        self.refined_policy, self.refiner = refine_from_critical_state(
            env=env,
            policy=target_policy,
            mask_net=mask_net if mask_net is not None else self.mask_net,
            total_timesteps=total_timesteps,
            total_iterations=total_iterations,
            env_id=self.env_id,
            config=self.config,
            logger=self.logger,
            save_path=save_path,
            seed=self.seed,
            device=self.device,
            progress=progress,
            evaluate=evaluate,
            eval_episodes=eval_episodes,
            use_rnd=self.use_rnd,
            **kwargs,
        )
        return self.refined_policy, self.refiner

    # ----------------------------------------------------------- end to end
    def run(
        self,
        env: Any,
        target_policy: Any,
        mask_samples: Optional[int] = None,
        refine_timesteps: Optional[int] = None,
        refine_iterations: Optional[int] = None,
        progress: bool = False,
        evaluate: bool = True,
        eval_episodes: int = 10,
        save_dir: Optional[str] = None,
        **kwargs: Any,
    ) -> Dict[str, Any]:
        """Run both stages and report the before/after reward (Table 1 style)."""
        self.train_explanation(
            env=env,
            target_policy=target_policy,
            total_timesteps=mask_samples or self.mask_samples,
            progress=progress,
            save_path=(f"{ensure_dir(save_dir)}/statemask_mask.pt" if save_dir else None),
            **kwargs,
        )
        self.refine(
            env=env,
            target_policy=target_policy,
            total_timesteps=refine_timesteps,
            total_iterations=refine_iterations,
            progress=progress,
            evaluate=evaluate,
            eval_episodes=eval_episodes,
            save_path=(f"{ensure_dir(save_dir)}/statemask_r.pt" if save_dir else None),
        )

        result: Dict[str, Any] = {
            "method": self.name,
            "env_id": self.env_id,
            "mask_samples": self.mask_samples,
            "alpha_final": float(getattr(self.trainer, "alpha", float("nan"))),
        }
        try:
            result.update(self.trainer.time_report())  # type: ignore[union-attr]
        except Exception:
            pass
        try:
            result["refine"] = self.refiner.summary()  # type: ignore[union-attr]
        except Exception:
            pass
        return result

    def summary(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "env_id": self.env_id,
            "mask_samples": self.mask_samples,
            "alpha": self.alpha,
            "use_rnd": self.use_rnd,
            "history": self.history,
        }


# --------------------------------------------------------------------------- #
# Convenience entry points
# --------------------------------------------------------------------------- #


def statemask_r_baseline(
    env: Any,
    target_policy: Any,
    env_id: str = "default",
    mask_samples: Optional[int] = None,
    refine_timesteps: Optional[int] = None,
    refine_iterations: Optional[int] = None,
    config: Optional[Any] = None,
    seed: Optional[int] = None,
    device: str = "cpu",
    progress: bool = False,
    evaluate: bool = False,
    eval_episodes: int = 10,
    save_dir: Optional[str] = None,
    **kwargs: Any,
) -> Dict[str, Any]:
    """Run the full StateMask-R baseline (StateMask explanation + reset-to-critical refine)."""
    baseline = StateMaskR(
        env_id=env_id,
        config=config,
        seed=seed,
        device=device,
        mask_samples=mask_samples,
        **kwargs,
    )
    return baseline.run(
        env=env,
        target_policy=target_policy,
        mask_samples=mask_samples,
        refine_timesteps=refine_timesteps,
        refine_iterations=refine_iterations,
        progress=progress,
        evaluate=evaluate,
        eval_episodes=eval_episodes,
        save_dir=save_dir,
    )


# Alias used by the experiment drivers / registry.
statemask_r = statemask_r_baseline


def make_statemask_r(env_id: str = "default", **kwargs: Any) -> StateMaskR:
    """Factory used by the baseline registry."""
    return StateMaskR(env_id=env_id, **kwargs)


def describe_statemask_r(baseline: Optional[StateMaskR] = None) -> str:
    if baseline is None:
        return "StateMask-R (StateMask explanation + reset-to-critical refining)"
    return (
        f"StateMask-R(env={baseline.env_id}, mask_samples={baseline.mask_samples}, "
        f"alpha={baseline.alpha}, rnd={baseline.use_rnd})"
    )
