"""AIRS explanation adapter for RICE (Table 6 / Appendix C.3).

The RICE paper (Cheng et al., ICML 2024) uses AIRS (Yu et al., 2023) as one of the
*additional* explanation methods in the secondary comparison of Section C.3:

    "We investigate the impact of other explanation methods (i.e., AIRS (Yu et al.,
     2023) and Integrated Gradients (Sundararajan et al., 2017)) on four Mujoco games.
     we fix the refining method and use different explanation methods to identify
     critical steps for refinement. The results are reported in Table 6. We observe
     that using the explanation generated by our mask network, the refining achieves
     the best outcome across all four applications. Using other explanation methods
     (Integrated Gradients and AIRS), our framework still achieves better results than
     the random baseline, suggesting that our framework can work with different
     explanation method choices."

The paper only reports the *trend* (ours > AIRS > Integrated Gradients > Random, see
``TABLE6_ORDERING``) and does not specify AIRS' internals.  This module therefore
provides:

* an upstream hook -- if the original AIRS implementation/package is importable
  (``AIRS_UPSTREAM_MODULE`` env var or a package exposing ``airs``), it is used and
  wrapped;
* an *attention-based* backend that extracts per-state relevance from attention
  weights (or from a user supplied relevance hook) when the policy exposes them;
* a black-box fallback that follows the same spirit as AIRS while remaining
  architecture-independent (RICE's black-box assumption): smoothed input-gradient
  saliency (SmoothGrad-style, Sundararajan et al. 2017 / Smilkov et al. 2017) and,
  if no differentiable model is available, occlusion-based relevance.

All backends produce per-feature attributions ``(N, D)`` that are aggregated into a
per-state importance score ``(N,)`` -- exactly the same duck-typed surface as
``random_explanation.py``, ``statemask_adapter.py`` and ``integrated_gradients.py``
(``importance`` / ``score`` / ``mask_prob_zero`` / ``select_index`` /
``critical_state`` / ``state_dict`` ...), so the fidelity evaluator
(``rice.evaluation.fidelity_score``) and the refining loop
(``rice.algorithms.refine`` via ``rice.explanation``) can treat every explanation
identically.

Deviations from the paper (documented for the README, since the paper is silent):
    * number of smoothing/path samples             -> ``steps=16``
    * attribution backend when nothing is inferable -> ``"gradient"`` (else ``"occlusion"``)
    * aggregation rule for a state                  -> ``"sum_abs"``
    * normalization of the importance scores        -> min-max to ``[0, 1]``
"""

from __future__ import annotations

import importlib
import os
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple

import numpy as np

# --------------------------------------------------------------------------------------
# optional dependencies (never fatal)
# --------------------------------------------------------------------------------------
try:  # pragma: no cover - torch is optional at import time
    import torch  # type: ignore

    _TORCH_AVAILABLE = True
except Exception:  # pragma: no cover
    torch = None  # type: ignore
    _TORCH_AVAILABLE = False

try:  # pragma: no cover
    from ..algorithms.ppo import flatten_obs
except Exception:  # pragma: no cover
    try:
        from rice.algorithms.ppo import flatten_obs  # type: ignore
    except Exception:
        try:
            from rice.rice.algorithms.ppo import flatten_obs  # type: ignore
        except Exception:

            def flatten_obs(obs: Any) -> np.ndarray:  # type: ignore
                if isinstance(obs, dict):
                    parts = [np.asarray(obs[k], dtype=np.float32).ravel() for k in sorted(obs)]
                    return np.concatenate(parts) if parts else np.zeros(0, dtype=np.float32)
                return np.asarray(obs, dtype=np.float32).ravel()


try:  # pragma: no cover
    from ..utils.seeding import RNG
except Exception:  # pragma: no cover
    try:
        from rice.utils.seeding import RNG  # type: ignore
    except Exception:
        RNG = None  # type: ignore


__all__ = [
    "NAME",
    "ALIASES",
    "TABLE6_ORDERING",
    "AIRSConfig",
    "AIRSExplanation",
    "AIRSAdapter",
    "AIRSAttribution",
    "AIRSAttributionExplanation",
    "make_airs_explanation",
    "build_airs",
    "make_explanation",
    "make_airs",
    "build_airs_explanation",
    "resolve_attribution_fn",
    "upstream_available",
    "get_spec",
]

NAME = "airs"
ALIASES = (
    "airs",
    "airs_adapter",
    "airs-adapter",
    "attention",
    "attention_importance",
    "yu2023",
)

#: Trend reported in Table 6 of the paper (higher is better); we reproduce trends,
#: not the exact numbers (see addendum).
TABLE6_ORDERING: Tuple[str, ...] = ("ours", "airs", "integrated_gradients", "random")

#: Environment variable pointing at an upstream AIRS implementation (module path).
_UPSTREAM_ENV = "RICE_AIRS_UPSTREAM"
_UPSTREAM_MODULE = "airs"

_DEVICE_ALIASES = {"auto": "auto", "cpu": "cpu", "cuda": "cuda"}


# ======================================================================================
# config
# ======================================================================================
@dataclass
class AIRSConfig:
    """Configuration for the AIRS explanation adapter.

    The paper does not specify these hyper-parameters, so the defaults below are the
    documented reproduction choices (README).
    """

    task: Optional[str] = None
    backend: str = "auto"  # auto | upstream | attention | gradient | occlusion
    steps: int = 16  # smoothing / path samples (unspecified in the paper)
    noise_scale: float = 0.0  # SmoothGrad-style Gaussian noise std added to states
    baseline: str = "zeros"  # zeros | mean | min | max | <array>
    aggregate: str = "sum_abs"  # sum_abs | mean_abs | l2 | max_abs | sum_signed
    multiply_by_inputs: bool = False  # IG-style (x - baseline) factor
    normalize: bool = True  # min-max the per-state importance to [0, 1]
    internal_batch_size: int = 16
    occlusion_features: int = 0  # 0 = all features (occlusion backend only)
    attention_key: Optional[str] = None  # attribute name of a relevance hook, if any
    device: str = "auto"
    seed: Optional[int] = None
    model: Any = None
    policy: Any = None
    action: Any = None  # fixed action used to score states (optional)
    notes: str = ""
    extra: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "task": self.task,
            "backend": self.backend,
            "steps": self.steps,
            "noise_scale": self.noise_scale,
            "baseline": self.baseline,
            "aggregate": self.aggregate,
            "multiply_by_inputs": self.multiply_by_inputs,
            "normalize": self.normalize,
            "internal_batch_size": self.internal_batch_size,
            "occlusion_features": self.occlusion_features,
            "attention_key": self.attention_key,
            "device": self.device,
            "seed": self.seed,
            "notes": self.notes,
            "extra": dict(self.extra),
        }

    def clone(self, **overrides: Any) -> "AIRSConfig":
        data = {
            k: v
            for k, v in self.__dict__.items()
            if k not in ("model", "policy", "action", "extra")
        }
        data["extra"] = dict(self.extra)
        unknown: Dict[str, Any] = {}
        for key, value in overrides.items():
            if key in data:
                data[key] = value
            else:
                unknown[key] = value
        cfg = AIRSConfig(**data)
        cfg.extra.update(unknown)
        return cfg

    @classmethod
    def from_mapping(
        cls, mapping: Optional[Dict[str, Any]] = None, **overrides: Any
    ) -> "AIRSConfig":
        """Build from a (YAML-parsed) mapping; unknown keys land in ``extra``."""
        cfg = cls()
        data = dict(mapping or {})
        data.update(overrides)
        unknown: Dict[str, Any] = {}
        for key, value in data.items():
            if key in ("lambda", "lambda_"):
                continue
            if hasattr(cfg, key) and key not in ("extra",):
                setattr(cfg, key, value)
            else:
                unknown[key] = value
        cfg.extra.update(unknown)
        return cfg


# ======================================================================================
# helpers
# ======================================================================================
def _make_rng(seed: Optional[int] = None, rng: Any = None) -> Any:
    """Return an RNG exposing ``uniform``/``choice``/``integers``."""
    if rng is not None:
        return rng
    if RNG is not None:
        try:
            return RNG(seed)
        except Exception:
            pass
    return np.random.default_rng(seed)


def _resolve_device(device: str) -> str:
    """Resolve ``"auto"`` to ``cuda`` when available, else ``cpu``."""
    device = str(device or "auto").lower()
    if device not in _DEVICE_ALIASES:
        device = "auto"
    if device == "auto":
        if _TORCH_AVAILABLE:
            try:
                return "cuda" if torch.cuda.is_available() else "cpu"
            except Exception:  # pragma: no cover
                return "cpu"
        return "cpu"
    if device == "cuda" and _TORCH_AVAILABLE:
        try:
            if not torch.cuda.is_available():
                return "cpu"
        except Exception:  # pragma: no cover
            return "cpu"
    return device


def _as_states(states: Any) -> np.ndarray:
    """Coerce a list/array/tensor of states into a 2-D float32 array."""
    if states is None:
        return np.zeros((0, 0), dtype=np.float32)
    if isinstance(states, np.ndarray):
        arr = states
    elif _TORCH_AVAILABLE and isinstance(states, torch.Tensor):  # pragma: no cover
        arr = states.detach().cpu().numpy()
    elif isinstance(states, (Sequence, list, tuple)):
        if len(states) == 0:
            return np.zeros((0, 0), dtype=np.float32)
        first = states[0]
        if np.isscalar(first) or (isinstance(first, np.ndarray) and first.ndim == 0):
            arr = np.asarray(states, dtype=np.float32)
        else:
            arr = np.stack([flatten_obs(s) for s in states])
    else:
        arr = np.asarray(states, dtype=np.float32)
    arr = np.asarray(arr, dtype=np.float32)
    if arr.ndim == 1:
        arr = arr.reshape(1, -1)
    return arr


def _unpack_states(states: Any) -> Tuple[np.ndarray, bool, List[Any]]:
    """Return ``(flattened_states, was_batch, raw_list)``.

    ``was_batch`` is ``True`` when the input looked like a trajectory (list of states
    / 2-D array) rather than a single state.
    """
    was_batch = True
    raw: List[Any]
    if isinstance(states, (list, tuple)):
        raw = list(states)
        if len(states) == 0:
            return np.zeros((0, 0), dtype=np.float32), True, []
        first = states[0]
        if np.isscalar(first) or (hasattr(first, "ndim") and getattr(first, "ndim") == 0):
            raw = [states]
            was_batch = False
    elif isinstance(states, np.ndarray):
        raw = list(states)
        if states.ndim == 1:
            was_batch = False
    else:
        raw = [states]
        was_batch = False
    return _as_states(raw), was_batch, raw


def _model_from(obj: Any) -> Any:
    """Extract a callable neural module from a model / SB3 model / policy."""
    if obj is None:
        return None
    if hasattr(obj, "policy") and not callable(obj):  # SB3-like model object
        return obj.policy
    if hasattr(obj, "policy") and callable(obj):
        # both callable and has .policy -> prefer the inner policy when it is a module
        inner = getattr(obj, "policy")
        if _TORCH_AVAILABLE and isinstance(inner, torch.nn.Module):
            return inner
        if inner is not None:
            return inner
    return obj


def resolve_attribution_fn(model: Any) -> Optional[Callable[[Any], np.ndarray]]:
    """Normalize ``model`` into ``obs -> vector output`` (numpy in / numpy out).

    Accepts torch ``nn.Module`` objects, Stable-Baselines3 policies/models, or plain
    callables.  Returns ``None`` when nothing usable is available.
    """
    module = _model_from(model)
    if module is None:
        return None

    if _TORCH_AVAILABLE and isinstance(module, torch.nn.Module):

        def _fn(obs: Any) -> np.ndarray:  # noqa: D401
            with torch.no_grad():
                x = torch.as_tensor(_as_states(obs), dtype=torch.float32)
                out = module(x)
                if isinstance(out, (tuple, list)):
                    out = out[0]
                if isinstance(out, torch.distributions.Distribution):  # pragma: no cover
                    out = out.mean
                return out.detach().cpu().numpy()

        return _fn

    if callable(module):

        def _fn_callable(obs: Any) -> np.ndarray:  # noqa: D401
            out = module(_as_states(obs))
            if _TORCH_AVAILABLE and isinstance(out, torch.Tensor):  # pragma: no cover
                out = out.detach().cpu().numpy()
            if isinstance(out, (tuple, list)):
                out = out[0]
            return np.asarray(out, dtype=np.float32)

        return _fn_callable

    return None


def upstream_available() -> bool:
    """Whether an upstream AIRS implementation is importable."""
    candidate = os.environ.get(_UPSTREAM_ENV) or _UPSTREAM_MODULE
    try:
        importlib.import_module(candidate)
        return True
    except Exception:
        return False


def _load_upstream() -> Any:
    """Best-effort import of the original AIRS implementation (or ``None``)."""
    candidate = os.environ.get(_UPSTREAM_ENV) or _UPSTREAM_MODULE
    try:
        return importlib.import_module(candidate)
    except Exception:
        return None


# ======================================================================================
# main class
# ======================================================================================
class AIRSExplanation:
    """AIRS-style step-level explanation with a RICE-compatible interface.

    Parameters
    ----------
    model:
        Differentiable policy/module (torch ``nn.Module``), an SB3 model/policy, or a
        plain ``obs -> output`` callable.  Optional for the ``"occlusion"`` backend.
    config:
        :class:`AIRSConfig` or a mapping (parsed YAML).
    """

    def __init__(
        self,
        model: Any = None,
        config: Optional[Any] = None,
        device: str = "auto",
        seed: Optional[int] = None,
        rng: Any = None,
        task: Optional[str] = None,
        env: Any = None,
        policy: Any = None,
        **kwargs: Any,
    ) -> None:
        if config is None:
            self.config = AIRSConfig()
        elif isinstance(config, AIRSConfig):
            self.config = config.clone()
        elif isinstance(config, dict):
            self.config = AIRSConfig.from_mapping(config)
        else:  # dataclass-like object
            self.config = AIRSConfig.from_mapping(
                {k: v for k, v in vars(config).items() if not k.startswith("_")}
            )

        if kwargs:
            self.config = self.config.clone(**kwargs)
        if task is not None:
            self.config.task = task
        if seed is not None:
            self.config.seed = seed
        if device:
            self.config.device = device

        self.task = self.config.task
        self.device = _resolve_device(self.config.device)
        self._device = self.device
        self.seed = self.config.seed
        self.rng = _make_rng(self.config.seed, rng)
        self.env = env

        # optional fixed action to score states under
        self.action = self.config.action

        self._model: Any = None
        self._model_kind: Optional[str] = None
        self._upstream: Any = None
        self._upstream_attr: Optional[str] = None
        self._data: Any = None
        self.set_model(model if model is not None else (policy or self.config.policy))

        if self.config.backend in ("upstream", "auto"):
            self._initialise_upstream()

        self.decisions: List[int] = []
        self.history: List[float] = []

    # ------------------------------------------------------------------ setup
    def _initialise_upstream(self) -> None:
        mod = _load_upstream()
        if mod is None:
            return
        self._upstream = mod
        for attr in ("AIRS", "AIRSExplainer", "AIRSExplanation", "Explainer", "airs"):
            if hasattr(mod, attr):
                self._upstream_attr = attr
                break

    def set_model(self, model: Any, action: Any = None) -> "AIRSExplanation":
        """Attach the model used for attributions; returns ``self``."""
        self._model = _model_from(model)
        if action is not None:
            self.action = action
        if self._model is None:
            self._model_kind = None
        elif _TORCH_AVAILABLE and isinstance(self._model, torch.nn.Module):
            self._model_kind = "torch"
        elif callable(self._model):
            self._model_kind = "callable"
        else:
            self._model_kind = "unknown"
        return self

    # ------------------------------------------------------------- properties
    @property
    def available(self) -> bool:
        """Whether a usable attribution backend is wired up."""
        if self.config.backend == "occlusion":
            return True
        if self.config.backend == "upstream":
            return self._upstream is not None
        if callable(self._model) and self._model_kind == "callable":
            return True
        if self._model_kind == "torch" and _TORCH_AVAILABLE:
            return True
        return False

    @property
    def backend(self) -> str:
        """The resolved backend actually used (``auto`` is resolved lazily)."""
        return self._resolve_backend()

    def _resolve_backend(self) -> str:
        requested = str(self.config.backend or "auto").lower()
        if requested == "auto":
            if self._upstream_attr is not None or hasattr(self._upstream or {}, "airs"):
                return "upstream"
            if self._attention_hook() is not None:
                return "attention"
            if self._model_kind == "torch" and _TORCH_AVAILABLE:
                return "gradient"
            if callable(self._model):
                return "occlusion"
            return "uniform"
        if requested == "upstream" and self._upstream is None:
            return self._resolve_backend_fallback()
        if requested == "attention" and self._attention_hook() is None:
            return self._resolve_backend_fallback()
        if requested == "gradient" and not (_model_available := True):
            return "uniform"
        return requested

    def _resolve_backend_fallback(self) -> str:
        if self._model_kind == "torch" and _TORCH_AVAILABLE:
            return "gradient"
        if callable(self._model):
            return "occlusion"
        return "uniform"

    # --------------------------------------------------------- model handling
    def _apply_model(self, x: Any) -> Any:
        """Apply the raw module to a torch tensor, returning a tensor (or tuple)."""
        out = self._model(x)
        if isinstance(out, (tuple, list)):
            out = out[0]
        if isinstance(out, dict):  # pragma: no cover - exotic policies
            out = next(iter(out.values()))
        return out

    # ------------------------------------------------------ relevance backends
    def _gradient_attributions(self, states: np.ndarray, baseline: np.ndarray) -> np.ndarray:
        """Smoothed input-gradient saliency (Riemann path toward ``baseline``)."""
        if not _TORCH_AVAILABLE or self._model_kind != "torch":
            return self._occlusion_attributions(states, baseline)

        n_samples = max(1, int(self.config.steps))
        noise = float(self.config.noise_scale or 0.0)
        batch = max(1, int(self.config.internal_batch_size))
        out = np.zeros_like(states, dtype=np.float32)

        for start in range(0, states.shape[0], batch):
            chunk = states[start : start + batch]
            base = baseline[start : start + batch]
            x = torch.as_tensor(chunk, dtype=torch.float32, device=self._device)
            b = torch.as_tensor(base, dtype=torch.float32, device=self._device)
            acc = torch.zeros_like(x)
            for i in range(n_samples):
                alpha = float(i + 1) / float(n_samples)
                x_in = (b + alpha * (x - b)).clone().detach().requires_grad_(True)
                if noise > 0.0:
                    x_in = x_in + noise * torch.randn_like(x_in)
                target = self._apply_model(x_in)
                if not isinstance(target, torch.Tensor):
                    target = torch.as_tensor(target, dtype=torch.float32, device=self._device)
                target = target.reshape(target.shape[0], -1).abs().sum(dim=-1)
                grads = torch.autograd.grad(target.sum(), x_in, retain_graph=False)[0]
                acc = acc + grads.detach().abs()
            acc = acc / float(n_samples)
            if self.config.multiply_by_inputs:
                acc = acc * (x - b).detach().abs()
            out[start : start + batch] = acc.detach().cpu().numpy()
        return out

    def _occlusion_attributions(self, states: np.ndarray, baseline: np.ndarray) -> np.ndarray:
        """Occlusion relevance: change in output when a feature is replaced."""
        fn = resolve_attribution_fn(self._model)
        if fn is None:
            return np.zeros_like(states, dtype=np.float32)

        n_features = states.shape[1]
        n_occ = int(self.config.occlusion_features or 0)
        if 0 < n_occ < n_features:
            idx = np.sort(self.rng.choice(n_features, size=n_occ, replace=False))
            features = list(np.asarray(idx).ravel().astype(int))
        else:
            features = list(range(n_features))
        if not features:
            return np.zeros_like(states, dtype=np.float32)

        base_out = np.asarray(fn(states), dtype=np.float32)
        base_out = base_out.reshape(base_out.shape[0], -1)
        attrs = np.zeros_like(states, dtype=np.float32)
        for f in features:
            occluded = np.array(states, copy=True)
            occluded[:, f] = baseline[:, f]
            new_out = np.asarray(fn(occluded), dtype=np.float32)
            new_out = new_out.reshape(new_out.shape[0], -1)
            diff = np.abs(base_out - new_out).sum(axis=-1)
            attrs[:, f] = diff
        return attrs

    def _upstream_attributions(self, states: np.ndarray) -> Optional[np.ndarray]:
        """Use the original AIRS implementation when available."""
        if self._upstream is None or self._upstream_attr is None:
            return None
        cls_or_fn = getattr(self._upstream, self._upstream_attr, None)
        if cls_or_fn is None:
            return None
        try:
            if isinstance(cls_or_fn, type):
                obj = cls_or_fn(self._model)  # type: ignore[call-arg]
            else:
                obj = cls_or_fn
            for attr in ("attributions", "attribute", "explain", "importance", "score"):
                if hasattr(obj, attr):
                    result = getattr(obj, attr)(states)
                    arr = np.asarray(result, dtype=np.float32)
                    if arr.ndim == 2 and arr.shape == states.shape:
                        return arr
                    if arr.ndim == 1 and arr.shape[0] == states.shape[0]:
                        return np.repeat(arr.reshape(-1, 1), states.shape[1], axis=1)
            if callable(obj):
                result = obj(states)
                arr = np.asarray(result, dtype=np.float32)
                if arr.ndim == 2 and arr.shape == states.shape:
                    return arr
        except Exception:
            return None
        return None

    def _attention_hook(self) -> Optional[Callable[[np.ndarray], np.ndarray]]:
        """A user-supplied relevance hook (``attention_key`` attr on the model)."""
        key = self.config.attention_key
        if not key:
            return None
        target = self._model
        for attr in (key, key + "_importance", key + "_relevance"):
            if target is not None and hasattr(target, attr):
                fn = getattr(target, attr)
                if callable(fn):
                    return fn
        return None

    def _attention_attributions(self, states: np.ndarray) -> Optional[np.ndarray]:
        hook = self._attention_hook()
        if hook is None:
            return None
        try:
            arr = np.asarray(hook(states), dtype=np.float32)
        except Exception:
            return None
        if arr.ndim == 2 and arr.shape == states.shape:
            return arr
        if arr.ndim == 1 and arr.shape[0] == states.shape[0]:
            return np.repeat(arr.reshape(-1, 1), states.shape[1], axis=1)
        if arr.ndim == 2 and arr.shape[0] == states.shape[0]:
            arr = np.abs(arr).sum(axis=-1, keepdims=True)
            return np.repeat(arr, states.shape[1], axis=1)
        return None

    # ---------------------------------------------------------- public classes
    def _baseline_array(self, states: np.ndarray, baseline: Any = None) -> np.ndarray:
        baseline = self.config.baseline if baseline is None else baseline
        n = states.shape[0]
        if isinstance(baseline, str):
            key = baseline.lower()
            if key == "zeros":
                return np.zeros_like(states, dtype=np.float32)
            if key == "mean":
                return np.repeat(states.mean(axis=0, keepdims=True), n, axis=0)
            if key == "min":
                return np.repeat(states.min(axis=0, keepdims=True), n, axis=0)
            if key == "max":
                return np.repeat(states.max(axis=0, keepdims=True), n, axis=0)
            return np.zeros_like(states, dtype=np.float32)
        arr = np.asarray(baseline, dtype=np.float32)
        if arr.ndim == 1:
            arr = np.repeat(arr.reshape(1, -1), n, axis=0)
        if arr.shape[0] != n:
            arr = np.repeat(arr[:1], n, axis=0)
        return arr

    def attributions(
        self,
        states: Any,
        actions: Any = None,
        baseline: Any = None,
        **kwargs: Any,
    ) -> np.ndarray:
        """Return per-feature attributions ``(N, D)`` for the given states."""
        arr, _was_batch, _raw = _unpack_states(states)
        if arr.size == 0:
            return np.zeros_like(arr, dtype=np.float32)
        backend = self._resolve_backend()

        result: Optional[np.ndarray] = None
        if backend == "upstream":
            result = self._upstream_attributions(arr)
            if result is None:
                backend = self._resolve_backend_fallback()
        if result is None and backend == "attention":
            result = self._attention_attributions(arr)
            if result is None:
                backend = self._resolve_backend_fallback()
        if result is None and backend == "occlusion":
            result = self._occlusion_attributions(arr, self._baseline_array(arr, baseline))
        if result is None and backend == "gradient":
            result = self._gradient_attributions(arr, self._baseline_array(arr, baseline))
        if result is None:
            # Last resort: uniform relevance (equivalent to the Random baseline).
            result = np.ones_like(arr, dtype=np.float32)
        return np.asarray(result, dtype=np.float32)

    def _aggregate(self, attrs: np.ndarray, aggregate: Optional[str] = None) -> np.ndarray:
        mode = (aggregate or self.config.aggregate or "sum_abs").lower()
        a = np.abs(attrs)
        if mode == "sum_abs":
            return a.sum(axis=-1)
        if mode == "mean_abs":
            return a.mean(axis=-1)
        if mode == "l2":
            return np.sqrt((attrs ** 2).sum(axis=-1))
        if mode == "max_abs":
            return a.max(axis=-1)
        if mode == "sum_signed":
            return attrs.sum(axis=-1)
        return a.sum(axis=-1)

    def importance(
        self,
        states: Any,
        actions: Any = None,
        aggregate: Optional[str] = None,
        normalize: Optional[bool] = None,
        **kwargs: Any,
    ) -> np.ndarray:
        """Per-state importance score ``(N,)`` used for critical-state selection.

        Definition (this adapter): the aggregated AIRS relevance of state ``s_t``,
        optionally min-max normalized to ``[0, 1]`` for parity with the mask
        network's ``P(a^m = 0 | s)``.
        """
        arr, _was_batch, _raw = _unpack_states(states)
        if arr.size == 0:
            return np.zeros(arr.shape[0], dtype=np.float32)
        attrs = self.attributions(arr, actions=actions, **kwargs)
        scores = self._aggregate(np.asarray(attrs, dtype=np.float32), aggregate)
        scores = np.nan_to_num(np.asarray(scores, dtype=np.float32), nan=0.0, posinf=0.0, neginf=0.0)
        scores = np.abs(scores) if (aggregate or self.config.aggregate) == "sum_signed" else np.maximum(scores, 0.0)
        self.history.extend(float(s) for s in np.ravel(scores)[:1024])

        do_normalize = self.config.normalize if normalize is None else bool(normalize)
        if do_normalize and scores.size:
            lo = float(np.min(scores))
            hi = float(np.max(scores))
            if hi - lo > 1e-12:
                scores = (scores - lo) / (hi - lo)
            else:
                scores = np.zeros_like(scores)
        return scores

    # aliases so any consumer's duck-typing works
    score = importance
    mask_prob_zero = importance

    def __call__(self, states: Any, **kwargs: Any) -> np.ndarray:
        return self.importance(states, **kwargs)

    # ------------------------------------------------- state selection helpers
    def select_index(self, states: Any, rng: Any = None, **kwargs: Any) -> int:
        """Index (earliest tie) of the most critical state in the trajectory."""
        scores = self.importance(states, **kwargs)
        if scores.size == 0:
            return 0
        idx = int(np.argmax(scores))
        self.decisions.append(idx)
        return idx

    def best_index(self, states: Any, rng: Any = None, **kwargs: Any) -> int:
        """Alias of :meth:`select_index` (mask-network-compatible naming)."""
        return self.select_index(states, rng=rng, **kwargs)

    def critical_state(
        self, states: Any, rng: Any = None, return_index: bool = False, **kwargs: Any
    ) -> Any:
        """Most critical state of the trajectory (Algorithm 2's ``argmax``)."""
        scores = self.importance(states, **kwargs)
        raw_states = states
        if isinstance(states, np.ndarray):
            raw_states = list(states)
        raw_states = list(raw_states) if isinstance(raw_states, (list, tuple)) else [raw_states]
        if not raw_states:
            return (None, 0) if return_index else None
        idx = int(np.argmax(scores)) if scores.size else 0
        self.decisions.append(idx)
        state = raw_states[idx]
        return (state, idx) if return_index else state

    def critical_states_batch(
        self, trajectories: Sequence[Any], rng: Any = None, **kwargs: Any
    ) -> List[Any]:
        """One critical state per trajectory in ``trajectories``."""
        return [self.critical_state(t, rng=rng, **kwargs) for t in trajectories]

    def select_top_k(
        self, states: Any, k: int = 1, **kwargs: Any
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Top-``k`` states by importance (and their scores)."""
        scores = self.importance(states, **kwargs)
        raw_states = states
        if isinstance(states, np.ndarray):
            raw_states = list(states)
        raw_states = list(raw_states) if isinstance(raw_states, (list, tuple)) else [raw_states]
        if not raw_states or scores.size == 0:
            return np.zeros((0, 0), dtype=np.float32), np.zeros(0, dtype=np.float32)
        k = int(max(1, min(k, len(raw_states))))
        order = np.argsort(-np.asarray(scores, dtype=np.float64))[:k]
        picked = np.stack([flatten_obs(raw_states[i]) for i in order])
        return picked, np.asarray(scores)[order]

    # ------------------------------------------------------------- lifecycle
    def reset(self, seed: Optional[int] = None) -> None:
        """Re-seed the module (called per episode/fidelity trajectory)."""
        if seed is not None:
            self.seed = seed
            self.rng = _make_rng(seed)
        self.decisions = []

    def update(self, *args: Any, **kwargs: Any) -> None:
        """No-op: AIRS needs no training (kept for API parity with the mask net)."""
        return None

    # -------------------------------------------------------------- metadata
    def describe(self) -> Dict[str, Any]:
        return {
            "name": NAME,
            "task": self.task,
            "backend": self.backend,
            "available": self.available,
            "steps": int(self.config.steps),
            "aggregate": self.config.aggregate,
            "normalize": bool(self.config.normalize),
            "upstream": bool(self._upstream is not None),
            "notes": self.config.notes,
        }

    def as_dict(self) -> Dict[str, Any]:
        data = self.describe()
        data["config"] = self.config.to_dict()
        return data

    def state_dict(self) -> Dict[str, Any]:
        state: Dict[str, Any] = {
            "seed": self.seed,
            "decisions": list(self.decisions),
            "history": list(self.history),
        }
        try:  # keep reproducibility of stochastic backends across resumes
            state["rng_state"] = np.random.Generator.bit_generator.state  # type: ignore[attr-defined]
        except Exception:
            pass
        try:
            if hasattr(self.rng, "bit_generator"):
                state["rng_state"] = self.rng.bit_generator.state
            elif hasattr(self.rng, "_rng"):
                state["rng_state"] = self.rng._rng.bit_generator.state
        except Exception:
            pass
        return state

    def load_state_dict(self, state: Optional[Dict[str, Any]]) -> "AIRSExplanation":
        if not state:
            return self
        self.seed = state.get("seed", self.seed)
        self.decisions = list(state.get("decisions", []))
        self.history = list(state.get("history", []))
        rng_state = state.get("rng_state")
        if rng_state is not None:
            try:
                if hasattr(self.rng, "bit_generator"):
                    self.rng.bit_generator.state = rng_state
                elif hasattr(self.rng, "_rng"):
                    self.rng._rng.bit_generator.state = rng_state
            except Exception:
                pass
        return self

    def __repr__(self) -> str:  # pragma: no cover - cosmetic
        return (
            f"AIRSExplanation(backend={self.backend!r}, available={self.available}, "
            f"task={self.task!r})"
        )


# aliases used by the explanation registry
AIRSAdapter = AIRSExplanation
AIRSAttribution = AIRSExplanation
AIRSAttributionExplanation = AIRSExplanation


# ======================================================================================
# factories
# ======================================================================================
def make_airs_explanation(
    model: Any = None,
    config: Optional[Any] = None,
    env: Any = None,
    policy: Any = None,
    **kwargs: Any,
) -> AIRSExplanation:
    """Build an :class:`AIRSExplanation` (registry factory for ``"airs"``)."""
    return AIRSExplanation(model=model, config=config, env=env, policy=policy, **kwargs)


def build_airs(model: Any = None, config: Optional[Any] = None, **kwargs: Any) -> AIRSExplanation:
    """Alias of :func:`make_airs_explanation`."""
    return make_airs_explanation(model=model, config=config, **kwargs)


def build_airs_explanation(**kwargs: Any) -> AIRSExplanation:
    """Alias of :func:`make_airs_explanation`."""
    return make_airs_explanation(**kwargs)


def make_airs(**kwargs: Any) -> AIRSExplanation:
    """Alias of :func:`make_airs_explanation`."""
    return make_airs_explanation(**kwargs)


def make_explanation(**kwargs: Any) -> AIRSExplanation:
    """Local dispatch alias used by ``rice.explanation``."""
    return make_airs_explanation(**kwargs)


def get_spec() -> Dict[str, Any]:
    """Registry metadata for the AIRS explanation provider."""
    return {
        "name": NAME,
        "aliases": ALIASES,
        "factory": "make_airs_explanation",
        "module": "airs_adapter",
        "description": (
            "AIRS (Yu et al. 2023) explanation adapter; attention/gradient/occlusion "
            "attribution with a black-box fallback (Table 6 secondary comparison)."
        ),
        "upstream_available": upstream_available(),
        "table6_ordering": TABLE6_ORDERING,
    }
