"""Neural networks for Montezuma's Revenge (PPO + Random Network Distillation).

Reproduces the architecture described in Appendix B.2 of *Fine-tuning Reinforcement
Learning Models is Secretly a Forgetting Mitigation Problem* (Wołczyk et al., 2024):

    "we use a PPO agent with a Random Network Distillation (RND) mechanism
     (Burda et al., 2018) for exploration boost. It achieves this by employing two
     neural networks: a randomly initialized target network and a prediction network.
     Both networks receive observation as an input and return a vector with size 512.
     The prediction network is trained to predict the random outputs generated by the
     target network."

Concretely this module provides:

* :class:`NatureCNN` – the convolutional trunk used by both the PPO actor-critic and
  the RND target/predictor networks (84x84x4 inputs -> ``feature_dim`` features,
  default 512, matching the paper).
* :class:`PolicyNetwork` – shared-trunk PPO actor-critic with a categorical policy
  head over the 18 ALE actions and a scalar value head.
* :class:`RNDModel` – fixed random *target* network plus trainable *predictor*
  network; the intrinsic reward is the prediction error and the predictor is trained
  by regression onto the target outputs.
* :class:`RunningMeanStd`, :class:`ObsNormalizer`, :class:`RewardForwardFilter` and
  :class:`IntrinsicRewardNormalizer` – running statistics used for (optional)
  observation normalisation (``UseNorm`` / ``ObsNormStep`` in Table 2) and for
  normalising the intrinsic reward stream.
* :class:`MontezumaModelConfig` – dataclass mirroring Table 2's model-related
  hyperparameters with ``from_config`` support for ``configs/montezuma.yaml``.

All hyperparameter defaults follow Table 2 of the paper:

=========================  =========================
Hyperparameter             Value
=========================  =========================
MaxStepPerEpisode          4500
ExtCoef                    2.0
LearningRate               1e-4
NumEnv                     128
NumStep                    128
Gamma                      0.999
IntGamma                   0.99
Lambda                     0.95
StableEps                  1e-8
StateStackSize             4
PreProcHeight / Width      84
UseGAE                     True
UseNorm                    False
UseNoisyNet                False
ClipGradNorm               0.5
Entropy                    0.001
Epoch                      4
MiniBatch                  4
PPOEps                     0.1
IntCoef                    1.0
StickyAction               True
ActionProb                 0.25
UpdateProportion           0.25
LifeDone                   False
ObsNormStep                50
=========================  =========================

Torch is imported defensively so that the surrounding pipeline (data bookkeeping,
configs, tests that only exercise Montezuma's *environment*) stays importable in
environments without PyTorch.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any, Dict, Mapping, Optional, Sequence, Tuple, Union

try:  # pragma: no cover - exercised implicitly by every user of this module
    import numpy as np
except Exception:  # pragma: no cover
    np = None  # type: ignore

try:  # pragma: no cover
    import torch
    import torch.nn as nn
    import torch.nn.functional as F
    from torch.distributions import Categorical

    _HAS_TORCH = True
except Exception:  # pragma: no cover
    torch = None  # type: ignore
    nn = object  # type: ignore
    F = None  # type: ignore
    Categorical = None  # type: ignore
    _HAS_TORCH = False


__all__ = [
    # constants
    "OBS_SHAPE",
    "NUM_ACTIONS",
    "FRAME_STACK",
    "FRAME_SIZE",
    "FEATURE_DIM",
    "RND_FEATURE_DIM",
    "TABLE2_DEFAULTS",
    # config
    "MontezumaModelConfig",
    # statistics
    "RunningMeanStd",
    "ObsNormalizer",
    "RewardForwardFilter",
    "IntrinsicRewardNormalizer",
    # networks
    "NatureCNN",
    "PolicyNetwork",
    "RNDModel",
    # factories / helpers
    "build_policy",
    "build_rnd",
    "build_models",
    "count_parameters",
    "save_model_state",
    "load_model_state",
    "main",
]


# --------------------------------------------------------------------------------------
# Constants (Table 2 + Appendix B.2)
# --------------------------------------------------------------------------------------

FRAME_STACK = 4
FRAME_SIZE = 84
OBS_SHAPE: Tuple[int, int, int] = (FRAME_STACK, FRAME_SIZE, FRAME_SIZE)  # channel-first
NUM_ACTIONS = 18  # MontezumaRevengeNoFrameskip-v4 action set size
FEATURE_DIM = 512  # "return a vector with size 512" (Appendix B.2)
RND_FEATURE_DIM = 512

#: Model-relevant hyperparameters of Table 2, used as the dataclass defaults.
TABLE2_DEFAULTS: Dict[str, Any] = {
    "max_steps_per_episode": 4500,
    "ext_coef": 2.0,
    "int_coef": 1.0,
    "learning_rate": 1e-4,
    "num_env": 128,
    "num_step": 128,
    "gamma": 0.999,
    "int_gamma": 0.99,
    "lam": 0.95,
    "stable_eps": 1e-8,
    "state_stack_size": 4,
    "preproc_height": 84,
    "preproc_width": 84,
    "use_gae": True,
    "use_gpu": True,
    "use_norm": False,
    "use_noisy_net": False,
    "clip_grad_norm": 0.5,
    "entropy": 0.001,
    "epoch": 4,
    "mini_batch": 4,
    "ppo_eps": 0.1,
    "sticky_action": True,
    "action_prob": 0.25,
    "update_proportion": 0.25,
    "life_done": False,
    "obs_norm_step": 50,
}


# --------------------------------------------------------------------------------------
# Config
# --------------------------------------------------------------------------------------


@dataclass
class MontezumaModelConfig:
    """Model / optimisation hyperparameters for the Montezuma PPO + RND pipeline.

    Defaults follow Table 2 of the paper (see :data:`TABLE2_DEFAULTS`).  The values are
    identical for the M1 (PPO + RND, trained from scratch until ~7000 return) and the
    M2 fine-tuning stages, except ``use_rnd`` which is typically disabled once the
    agent has learned the first rooms and fine-tuning focuses on the full game.
    """

    # --- environment / observation ---
    obs_shape: Tuple[int, int, int] = OBS_SHAPE
    num_actions: int = NUM_ACTIONS
    state_stack_size: int = FRAME_STACK
    preproc_height: int = FRAME_SIZE
    preproc_width: int = FRAME_SIZE

    # --- PPO (Table 2) ---
    learning_rate: float = 1e-4
    num_env: int = 128
    num_step: int = 128
    gamma: float = 0.999
    int_gamma: float = 0.99
    lam: float = 0.95
    stable_eps: float = 1e-8
    use_gae: bool = True
    clip_grad_norm: float = 0.5
    entropy: float = 0.001
    epoch: int = 4
    mini_batch: int = 4
    ppo_eps: float = 0.1
    ext_coef: float = 2.0
    int_coef: float = 1.0
    update_proportion: float = 0.25
    max_steps_per_episode: int = 4500

    # --- normalisation / architectures knobs ---
    use_norm: bool = False
    use_noisy_net: bool = False
    obs_norm_step: int = 50
    normalize_obs: bool = True  # divide uint8 frames by 255 before the network
    shared_backbone: bool = True
    feature_dim: int = FEATURE_DIM
    rnd_feature_dim: int = RND_FEATURE_DIM
    use_rnd: bool = True

    # --- behavioral cloning (M2 / Figure 13) ---
    bc_kl_weight: float = 1.0

    # --- misc ---
    device: str = "cpu"
    seed: Optional[int] = None
    extras: Dict[str, Any] = field(default_factory=dict)

    # ---------------------------------------------------------------- construction
    @classmethod
    def from_config(cls, cfg: Any = None, **overrides: Any) -> "MontezumaModelConfig":
        """Build from ``configs/montezuma.yaml`` (or any mapping / namespace).

        Accepts the ``ppo`` / ``model`` / ``bc`` sub-blocks used by the config file and
        silently ignores unknown keys, so the config file may evolve independently.
        """
        values: Dict[str, Any] = {}
        if cfg is not None:
            ppo = _get_block(cfg, "ppo") or {}
            model = _get_block(cfg, "model") or {}
            env = _get_block(cfg, "env") or {}
            rnd = _get_block(cfg, "rnd") or {}
            bc = _get_block(cfg, "bc") or {}

            values.update(
                _filter_fields(
                    cls,
                    {
                        "learning_rate": _first(ppo, "learning_rate", "lr"),
                        "num_env": _first(ppo, "num_env", "num_envs"),
                        "num_step": _first(ppo, "num_step", "rollout_length"),
                        "gamma": _first(ppo, "gamma", "discount"),
                        "int_gamma": _first(rnd, "int_gamma", "intrinsic_gamma"),
                        "lam": _first(ppo, "lam", "lambda", "gae_lambda"),
                        "stable_eps": _first(ppo, "stable_eps", "eps"),
                        "use_gae": _first(ppo, "use_gae", "gae"),
                        "clip_grad_norm": _first(ppo, "clip_grad_norm", "max_grad_norm"),
                        "entropy": _first(ppo, "entropy", "entropy_coef"),
                        "epoch": _first(ppo, "epoch", "epochs"),
                        "mini_batch": _first(ppo, "mini_batch", "num_mini_batch"),
                        "ppo_eps": _first(ppo, "ppo_eps", "clip_ratio"),
                        "ext_coef": _first(ppo, "ext_coef", "extrinsic_coef"),
                        "int_coef": _first(rnd, "int_coef", "intrinsic_coef"),
                        "update_proportion": _first(rnd, "update_proportion"),
                        "max_steps_per_episode": _first(
                            _get_block(cfg, "env") or ppo, "max_steps", "max_steps_per_episode"
                        ),
                        "state_stack_size": _first(env, "frame_stack", "state_stack_size", "stack_size"),
                        "use_norm": _first(_get_block(cfg, "obs_norm") or {}, "use_norm", "enabled"),
                        "use_noisy_net": _first(model, "use_noisy_net"),
                        "obs_norm_step": _first(_get_block(cfg, "obs_norm") or {}, "obs_norm_step", "steps"),
                        "feature_dim": _first(model, "feature_dim", "hidden_dim"),
                        "rnd_feature_dim": _first(rnd, "output_size", "feature_dim"),
                        "shared_backbone": _first(model, "shared_backbone"),
                        "use_rnd": _first(rnd, "enabled", "use_rnd"),
                        "bc_kl_weight": _first(bc, "kl_weight", "kl_coef", "coef"),
                        "device": _first(cfg, "device"),
                        "seed": _first(cfg, "seed"),
                    },
                )
            )

        # Explicit overrides win over everything read from the config.
        values.update(_filter_fields(cls, overrides))
        return cls(**values)

    def to_dict(self) -> Dict[str, Any]:
        """Serialisable view of the model hyperparameters (for logging/checkpoints)."""
        out: Dict[str, Any] = {}
        for key, value in self.__dict__.items():
            if key == "extras":
                continue
            out[key] = list(value) if isinstance(value, tuple) else value
        return out

    @property
    def observation_shape(self) -> Tuple[int, int, int]:
        return self.obs_shape

    def with_overrides(self, **kwargs: Any) -> "MontezumaModelConfig":
        merged = self.to_dict()
        merged.update({k: v for k, v in kwargs.items() if k in merged})
        return MontezumaModelConfig(**merged)


# --------------------------------------------------------------------------------------
# Running statistics
# --------------------------------------------------------------------------------------


class RunningMeanStd:
    """Welford-style running mean/variance, matching the RND reference implementation.

    Works with scalars or NumPy arrays.  ``update`` accepts either a single value or a
    batch; NumPy is optional so this remains usable (with pure-Python maths) in
    dependency-light tests.
    """

    def __init__(self, shape: Union[int, Sequence[int]] = (), epsilon: float = 1e-4, name: str = "rms"):
        self.shape = tuple(shape) if not isinstance(shape, int) else (shape,)
        self.epsilon = float(epsilon)
        self.name = name
        self.mean = self._zeros(self.shape)
        self.var = self._ones(self.shape)
        self.count = float(self.epsilon)

    # ---------------------------------------------------------------- helpers
    @staticmethod
    def _zeros(shape: Tuple[int, ...]) -> Any:
        if np is not None:
            return np.zeros(shape, dtype=np.float64)
        return 0.0 if shape == () else [0.0 for _ in range(int(shape[0]))]

    @staticmethod
    def _ones(shape: Tuple[int, ...]) -> Any:
        if np is not None:
            return np.ones(shape, dtype=np.float64)
        return 1.0 if shape == () else [1.0 for _ in range(int(shape[0]))]

    def update(self, x: Any) -> None:
        """Incorporate a new sample (array-like) into the running statistics."""
        if x is None:
            return
        if np is None:  # pragma: no cover - pure-Python fallback
            value = float(x)
            self.count += 1.0
            delta = value - self.mean
            self.mean = self.mean + delta / self.count
            self.var = self.var + delta * (value - self.mean)
            return

        batch = np.asarray(x, dtype=np.float64)
        if batch.ndim == 0:
            batch = batch.reshape(1)
        elif self.shape and batch.shape[0] == self.shape[0] and batch.ndim > len(self.shape):
            # (T, *shape) -> fold the leading time axis into the batch dimension
            batch = batch.reshape(-1, *batch.shape[-len(self.shape):])

        batch_mean = batch.mean(axis=0)
        batch_var = batch.var(axis=0)
        batch_count = batch.shape[0] if batch.ndim else 1

        self._update_from_moments(batch_mean, batch_var, batch_count)

    def _update_from_moments(self, batch_mean: Any, batch_var: Any, batch_count: float) -> None:
        delta = batch_mean - self.mean
        tot_count = self.count + batch_count
        new_mean = self.mean + delta * batch_count / tot_count
        m_a = self.var * self.count
        m_b = batch_var * batch_count
        m2 = m_a + m_b + (delta ** 2) * self.count * batch_count / tot_count
        self.mean = new_mean
        self.var = m2 / tot_count
        self.count = float(tot_count)

    # ---------------------------------------------------------------- usage
    @property
    def std(self) -> Any:
        if np is not None:
            return np.sqrt(np.maximum(self.var, 1e-12))
        return math.sqrt(max(self.var, 1e-12))

    def normalize(self, x: Any, clip: Optional[float] = 10.0) -> Any:
        value = (x - self.mean) / (self.std + 1e-8)
        if clip is not None:
            if np is not None:
                value = np.clip(value, -clip, clip)
            else:  # pragma: no cover
                value = max(-clip, min(clip, value))
        return value

    def state_dict(self) -> Dict[str, Any]:
        return {
            "mean": _tolist(self.mean),
            "var": _tolist(self.var),
            "count": self.count,
            "shape": list(self.shape),
            "epsilon": self.epsilon,
        }

    def load_state_dict(self, state: Mapping[str, Any]) -> None:
        if not state:
            return
        self.mean = _fromlist(state.get("mean"), self.shape)
        self.var = _fromlist(state.get("var"), self.shape)
        self.count = float(state.get("count", self.count))

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"RunningMeanStd(name={self.name!r}, count={self.count:.1f})"


class ObsNormalizer:
    """Optional observation normalisation (``UseNorm`` / ``ObsNormStep`` in Table 2).

    The paper follows Burda et al. (2018) and *disables* it (``UseNorm=False``), but
    the mechanism is provided because the reference implementation supports it and the
    M1/M2 runs may enable it.  When ``normalize_obs`` is used the network simply sees
    frames scaled to ``[0, 1]``.
    """

    def __init__(
        self,
        shape: Union[int, Sequence[int]] = (FRAME_STACK, FRAME_SIZE, FRAME_SIZE),
        enabled: bool = False,
        update_steps: int = TABLE2_DEFAULTS["obs_norm_step"],
        clip: float = 10.0,
    ):
        self.shape = tuple(shape) if not isinstance(shape, int) else (shape,)
        self.enabled = bool(enabled)
        self.update_steps = int(update_steps)
        self.clip = float(clip)
        self.rms = RunningMeanStd(self.shape, name="obs")
        self.steps = 0

    def update(self, obs: Any) -> None:
        if not self.enabled:
            return
        if self.update_steps and self.steps >= self.update_steps:
            return
        self.rms.update(obs)
        self.steps += 1

    def __call__(self, obs: Any) -> Any:
        if not self.enabled:
            return obs
        return self.rms.normalize(obs, clip=self.clip)

    def state_dict(self) -> Dict[str, Any]:
        return {"rms": self.rms.state_dict(), "steps": self.steps, "enabled": self.enabled}

    def load_state_dict(self, state: Mapping[str, Any]) -> None:
        if not state:
            return
        self.rms.load_state_dict(state.get("rms") or {})
        self.steps = int(state.get("steps", self.steps))
        self.enabled = bool(state.get("enabled", self.enabled))


class RewardForwardFilter:
    """Discounted running average of the intrinsic reward stream.

    Implements the ``RewardForwardFilter`` used by RND reference implementations:

    ``rff_t = gamma_int * rff_{t-1} + r_t``

    The normalised intrinsic reward is then ``r_t / sqrt(Var(RFF))`` applied by
    :class:`IntrinsicRewardNormalizer`.
    """

    def __init__(self, num_env: int = TABLE2_DEFAULTS["num_env"], int_gamma: float = TABLE2_DEFAULTS["int_gamma"]):
        self.num_env = int(num_env)
        self.int_gamma = float(int_gamma)
        self.rewems = _zeros([self.num_env])

    def update(self, rewards: Any) -> Any:
        """``rewards`` shape ``(num_env,)`` -> updated accumulators (same shape)."""
        rewards_arr = _as_array(rewards).reshape(-1)
        if rewards_arr.size < self.num_env:
            pad = self.num_env - rewards_arr.size
            rewards_arr = _concat(rewards_arr, _zeros([pad]))
        self.rewems = self.rewems * self.int_gamma + rewards_arr[: self.num_env]
        return self.rewems

    def reset(self) -> None:
        self.rewems = _zeros([self.num_env])

    def state_dict(self) -> Dict[str, Any]:
        return {"rewems": _tolist(self.rewems), "num_env": self.num_env, "int_gamma": self.int_gamma}

    def load_state_dict(self, state: Mapping[str, Any]) -> None:
        if not state:
            return
        if state.get("rewems") is not None:
            self.rewems = _fromlist(state["rewems"], (self.num_env,))


class IntrinsicRewardNormalizer:
    """Normalise the RND prediction error by its running standard deviation.

    This is the standard "intrinsic reward normalization" from Burda et al. (2018):
    ``r_int <- r_int / std(RFF)`` where RFF is a discounted running average of the raw
    prediction errors.
    """

    def __init__(
        self,
        num_env: int = TABLE2_DEFAULTS["num_env"],
        int_gamma: float = TABLE2_DEFAULTS["int_gamma"],
        enabled: bool = True,
    ):
        self.enabled = bool(enabled)
        self.num_env = int(num_env)
        self.filter = RewardForwardFilter(num_env=num_env, int_gamma=int_gamma)
        self.rms = RunningMeanStd((), name="int_reward")
        self.discounted_rms = RunningMeanStd((), name="int_reward_discounted")

    def update(self, intrinsic_rewards: Any) -> None:
        rewards = _as_array(intrinsic_rewards).reshape(-1)
        if rewards.size == 0:
            return
        self.rms.update(rewards)
        if self.enabled:
            disc = self.filter.update(rewards)
            self.discounted_rms.update(_as_array(disc).reshape(-1))

    def __call__(self, intrinsic_rewards: Any) -> Any:
        rewards = _as_array(intrinsic_rewards)
        if not self.enabled or self.discounted_rms.count <= 1.0:
            return intrinsic_rewards
        return rewards / (self.discounted_rms.std + 1e-8)

    def state_dict(self) -> Dict[str, Any]:
        return {
            "enabled": self.enabled,
            "rms": self.rms.state_dict(),
            "discounted_rms": self.discounted_rms.state_dict(),
            "filter": self.filter.state_dict(),
        }

    def load_state_dict(self, state: Mapping[str, Any]) -> None:
        if not state:
            return
        self.enabled = bool(state.get("enabled", self.enabled))
        self.rms.load_state_dict(state.get("rms") or {})
        self.discounted_rms.load_state_dict(state.get("discounted_rms") or {})
        self.filter.load_state_dict(state.get("filter") or {})


# --------------------------------------------------------------------------------------
# Networks
# --------------------------------------------------------------------------------------


class NatureCNN(nn.Module):
    """Nature-DQN style convolutional trunk (Mnih et al., 2015).

    ``(C, 84, 84)`` uint8 observation -> ``feature_dim`` features (512 by default, as
    used for both the PPO trunk and the RND target/predictor in Appendix B.2).

    Architecture: ``Conv(8x8, s4, 32) - Conv(4x4, s2, 64) - Conv(3x3, s1, 64) - FC``.
    The Montezuma implementation used by the paper (jcwleo's RND repository, cited in
    Table 2) uses ``LeakyReLU`` inside the RND networks; the PPO trunk uses ``ReLU``.
    """

    def __init__(
        self,
        in_channels: int = FRAME_STACK,
        feature_dim: int = FEATURE_DIM,
        activation: str = "relu",
        width_scale: float = 1.0,
    ):
        _require_torch()
        super().__init__()
        c1 = max(1, int(round(32 * width_scale)))
        c2 = max(1, int(round(64 * width_scale)))
        c3 = max(1, int(round(64 * width_scale)))

        self.in_channels = int(in_channels)
        self.feature_dim = int(feature_dim)
        self.activation_name = activation
        self.activation = _make_activation(activation)

        self.conv1 = nn.Conv2d(self.in_channels, c1, kernel_size=8, stride=4)
        self.conv2 = nn.Conv2d(c1, c2, kernel_size=4, stride=2)
        self.conv3 = nn.Conv2d(c2, c3, kernel_size=3, stride=1)

        self._conv_out_dim = self._infer_conv_out_dim()
        self.fc = nn.Linear(self._conv_out_dim, self.feature_dim)
        self._init_weights()

    # ---------------------------------------------------------------- helpers
    def _infer_conv_out_dim(self, size: int = FRAME_SIZE) -> int:
        """Shape of the flattened convolution output for an ``size x size`` input."""
        with torch.no_grad():  # type: ignore[union-attr]
            dummy = torch.zeros(1, self.in_channels, size, size)  # type: ignore[union-attr]
            out = self.activation(self.conv3(self.activation(self.conv2(self.activation(self.conv1(dummy))))))
        return int(out.numel())

    def _init_weights(self) -> None:
        for module in self.modules():
            if isinstance(module, (nn.Conv2d, nn.Linear)):
                nn.init.orthogonal_(module.weight, gain=math.sqrt(2.0))
                if module.bias is not None:
                    nn.init.constant_(module.bias, 0.0)

    @property
    def conv_out_dim(self) -> int:
        return self._conv_out_dim

    # ---------------------------------------------------------------- forward
    def conv_features(self, obs: Any) -> Any:
        x = _prepare_obs(obs, in_channels=self.in_channels)
        x = self.activation(self.conv1(x))
        x = self.activation(self.conv2(x))
        x = self.activation(self.conv3(x))
        return x.flatten(1)

    def forward(self, obs: Any) -> Any:
        features = self.conv_features(obs)
        return self.activation(self.fc(features))

    def extra_repr(self) -> str:  # pragma: no cover
        return f"in_channels={self.in_channels}, feature_dim={self.feature_dim}, conv_out={self._conv_out_dim}"


class PolicyNetwork(nn.Module):
    """PPO actor-critic for Montezuma's Revenge (18 discrete actions).

    The convolutional trunk is shared between the policy and value heads (the standard
    setup for Atari PPO, and what the reference RND implementation uses).  Setting
    ``shared_backbone=False`` instantiates two independent trunks.
    """

    def __init__(
        self,
        obs_shape: Tuple[int, int, int] = OBS_SHAPE,
        num_actions: int = NUM_ACTIONS,
        feature_dim: int = FEATURE_DIM,
        activation: str = "relu",
        shared_backbone: bool = True,
        normalize_obs: bool = True,
        init_log_std: float = 0.0,
    ):
        _require_torch()
        super().__init__()
        in_channels = int(obs_shape[0])
        self.obs_shape = tuple(obs_shape)
        self.num_actions = int(num_actions)
        self.feature_dim = int(feature_dim)
        self.normalize_obs = bool(normalize_obs)
        self.shared_backbone = bool(shared_backbone)

        self.backbone = NatureCNN(in_channels=in_channels, feature_dim=feature_dim, activation=activation)
        self.value_backbone = (
            None
            if self.shared_backbone
            else NatureCNN(in_channels=in_channels, feature_dim=feature_dim, activation=activation)
        )

        self.policy_head = nn.Linear(feature_dim, self.num_actions)
        self.value_head = nn.Linear(feature_dim, 1)

        # Fixed log-standard-deviation for optional Gaussian-style parameterisation of
        # the discrete policy.  The PPO objective itself uses Categorical, but the
        # analysis utilities (expert log-likelihood) can consume `logits` directly.
        self.log_std = nn.Parameter(torch.full((self.num_actions,), float(init_log_std)))

        self._init_weights()

    # ---------------------------------------------------------------- helpers
    def _init_weights(self) -> None:
        for module in (self.policy_head, self.value_head):
            nn.init.orthogonal_(module.weight, gain=0.01)
            nn.init.constant_(module.bias, 0.0)

    def encode(self, obs: Any) -> Any:
        """Shared trunk features (used by CKA/analysis utilities)."""
        x = _prepare_obs(obs, in_channels=self.obs_shape[0], normalize=self.normalize_obs)
        return self.backbone(x)

    # ---------------------------------------------------------------- core API
    def forward(self, obs: Any) -> Tuple[Any, Any]:
        """Return ``(logits, value)`` with ``value`` shaped ``(batch,)``."""
        features = self.encode(obs)
        logits = self.policy_head(features)
        value_source = features if self.shared_backbone else self.value_backbone(
            _prepare_obs(obs, in_channels=self.obs_shape[0], normalize=self.normalize_obs)
        )
        value = self.value_head(value_source).squeeze(-1)
        return logits, value

    def distribution(self, obs: Any) -> Any:
        """Categorical action distribution ``pi(a|s)``."""
        logits, _ = self.forward(obs)
        return Categorical(logits=logits)

    def log_prob(self, obs: Any, actions: Any) -> Any:
        dist = self.distribution(obs)
        return dist.log_prob(_as_long(actions))

    def entropy(self, obs: Any) -> Any:
        return self.distribution(obs).entropy()

    def pi_value(self, obs: Any, actions: Any, detach: bool = False) -> Tuple[Any, Any, Any]:
        """Evaluate ``(log pi(a|s), entropy, V(s))`` for a batch (PPO update step)."""
        logits, value = self.forward(obs)
        dist = Categorical(logits=logits)
        actions_long = _as_long(actions)
        log_prob = dist.log_prob(actions_long)
        entropy = dist.entropy()
        if detach:
            log_prob = log_prob.detach()
            entropy = entropy.detach()
        return log_prob, entropy, value

    # ---------------------------------------------------------------- acting
    @torch.no_grad() if _HAS_TORCH else (lambda f: f)  # type: ignore[misc]
    def act(
        self,
        obs: Any,
        deterministic: bool = False,
        return_log_prob: bool = False,
        return_value: bool = False,
    ) -> Any:
        """Sample an action for a *single* observation (or batch of observations).

        Returns the action (``int`` for a single observation, tensor for a batch), or a
        dict with additional ``log_prob`` / ``value`` / ``logits`` entries when
        requested.  This mirrors the duck-typed ``.act`` interface used by
        ``src.montezuma.env`` and the RoboticSequence SAC policy.
        """
        single = _is_single_obs(obs)
        batch = _batchify(obs) if single else obs
        logits, value = self.forward(batch)
        dist = Categorical(logits=logits)
        action = logits.argmax(dim=-1) if deterministic else dist.sample()

        if not (return_log_prob or return_value):
            return int(action.item()) if single else action

        out: Dict[str, Any] = {"action": action}
        if return_log_prob:
            out["log_prob"] = dist.log_prob(action)
        if return_value:
            out["value"] = value
        out["logits"] = logits
        if single:
            out["action"] = int(action.item())
            out["log_prob"] = out["log_prob"].item()
            out["value"] = out["value"].item()
        return out

    def greedy_action(self, obs: Any) -> Any:
        result = self.act(obs, deterministic=True)
        return result

    def sample_action(self, obs: Any, deterministic: bool = False, **kwargs: Any) -> Any:
        return self.act(obs, deterministic=deterministic, **kwargs)

    # ---------------------------------------------------------------- persistence
    def state_dict(self, *args: Any, **kwargs: Any) -> Dict[str, Any]:  # type: ignore[override]
        return super().state_dict(*args, **kwargs)

    def describe(self) -> Dict[str, Any]:
        return {
            "obs_shape": list(self.obs_shape),
            "num_actions": self.num_actions,
            "feature_dim": self.feature_dim,
            "shared_backbone": self.shared_backbone,
            "parameters": count_parameters(self),
        }


class RNDModel(nn.Module):
    """Random Network Distillation (Burda et al., 2018) as used in Appendix B.2.

    * ``target`` – randomly initialised and *frozen* network.
    * ``predictor`` – trainable network regressing onto the target's outputs.

    Both networks "receive observation as an input and return a vector with size 512"
    (Appendix B.2).  The intrinsic reward is the (optionally normalised) prediction
    error ``||target(s) - predictor(s)||^2``.
    """

    def __init__(
        self,
        obs_shape: Tuple[int, int, int] = OBS_SHAPE,
        output_size: int = RND_FEATURE_DIM,
        predictor_extra_layers: int = 0,
        activation: str = "leaky_relu",
        normalize_obs: bool = True,
        hidden_dim: Optional[int] = None,
    ):
        _require_torch()
        super().__init__()
        in_channels = int(obs_shape[0])
        self.obs_shape = tuple(obs_shape)
        self.output_size = int(output_size)
        self.normalize_obs = bool(normalize_obs)

        self.target = NatureCNN(in_channels=in_channels, feature_dim=output_size, activation=activation)
        self.predictor = NatureCNN(in_channels=in_channels, feature_dim=output_size, activation=activation)

        extra = int(predictor_extra_layers or 0)
        self.predictor_extra = None
        if extra > 0:
            layers = []
            prev = output_size
            hidden = int(hidden_dim or output_size)
            for _ in range(extra):
                layers.append(nn.Linear(prev, hidden))
                layers.append(_make_activation(activation))
                prev = hidden
            self.predictor_extra = nn.Sequential(*layers)

        # The target is never optimised.
        for param in self.target.parameters():
            param.requires_grad_(False)
        self.target.eval()

    # ---------------------------------------------------------------- forward
    def target_features(self, obs: Any) -> Any:
        return self.target(_prepare_obs(obs, in_channels=self.obs_shape[0], normalize=self.normalize_obs))

    def predictor_features(self, obs: Any) -> Any:
        features = self.predictor(_prepare_obs(obs, in_channels=self.obs_shape[0], normalize=self.normalize_obs))
        if self.predictor_extra is not None:
            features = self.predictor_extra(features)
        return features

    def forward(self, obs: Any) -> Tuple[Any, Any]:
        """Return ``(prediction, target)`` feature vectors."""
        with torch.no_grad():  # type: ignore[union-attr]
            target = self.target_features(obs)
        prediction = self.predictor_features(obs)
        return prediction, target

    def prediction_error(self, obs: Any) -> Any:
        """Per-sample squared prediction error (the raw intrinsic reward)."""
        prediction, target = self(obs)
        return ((prediction - target) ** 2).mean(dim=-1)

    def intrinsic_reward(self, obs: Any) -> Any:
        return self.prediction_error(obs)

    def loss(self, obs: Any, weights: Any = None, reduction: str = "mean") -> Any:
        """RND regression loss ``||target(s) - predictor(s)||^2``.

        ``weights`` implements the paper's ``UpdateProportion=0.25`` behaviour: only a
        random quarter of each mini-batch contributes to the gradient (this is the
        convention of the reference implementation).
        """
        prediction, target = self(obs)
        loss = ((prediction - target) ** 2).mean(dim=-1)
        if weights is not None:
            weights = weights.reshape(-1).to(loss.dtype)
            loss = loss * weights
            denom = weights.sum().clamp(min=1e-8)
            if reduction == "sum":
                return loss.sum()
            return loss.sum() / denom
        if reduction == "none":
            return loss
        if reduction == "sum":
            return loss.sum()
        return loss.mean()

    def update_proportion_mask(self, batch_size: int, proportion: float, device: Any = None) -> Any:
        """Bernoulli mask enforcing ``UpdateProportion`` (Table 2: 0.25)."""
        proportion = float(proportion)
        if proportion >= 1.0:
            return torch.ones(batch_size, device=device)  # type: ignore[union-attr]
        return (torch.rand(batch_size, device=device) < proportion).float()  # type: ignore[union-attr]

    # ---------------------------------------------------------------- persistence
    def state_dict(self, *args: Any, **kwargs: Any) -> Dict[str, Any]:  # type: ignore[override]
        return super().state_dict(*args, **kwargs)

    def describe(self) -> Dict[str, Any]:
        return {
            "obs_shape": list(self.obs_shape),
            "output_size": self.output_size,
            "parameters": count_parameters(self),
            "predictor_parameters": count_parameters(self.predictor),
            "target_parameters": count_parameters(self.target),
        }


# --------------------------------------------------------------------------------------
# Factories / utilities
# --------------------------------------------------------------------------------------


def build_policy(
    cfg: Any = None,
    obs_shape: Optional[Tuple[int, int, int]] = None,
    num_actions: Optional[int] = None,
    device: Optional[Union[str, Any]] = None,
    **overrides: Any,
) -> "PolicyNetwork":
    """Build a :class:`PolicyNetwork` from a config (mapping/dataclass) or defaults."""
    model_cfg = _coerce_config(cfg, **overrides)
    obs_shape = tuple(obs_shape or model_cfg.obs_shape)
    num_actions = int(num_actions or model_cfg.num_actions)
    policy = PolicyNetwork(
        obs_shape=obs_shape,
        num_actions=num_actions,
        feature_dim=model_cfg.feature_dim,
        shared_backbone=model_cfg.shared_backbone,
        normalize_obs=model_cfg.normalize_obs,
    )
    dev = device if device is not None else model_cfg.device
    if dev is not None:
        policy = policy.to(_resolve_device(dev))
    return policy


def build_rnd(
    cfg: Any = None,
    obs_shape: Optional[Tuple[int, int, int]] = None,
    device: Optional[Union[str, Any]] = None,
    **overrides: Any,
) -> "RNDModel":
    """Build an :class:`RNDModel` (target + predictor) from a config or defaults."""
    model_cfg = _coerce_config(cfg, **overrides)
    obs_shape = tuple(obs_shape or model_cfg.obs_shape)
    rnd = RNDModel(
        obs_shape=obs_shape,
        output_size=model_cfg.rnd_feature_dim,
        normalize_obs=model_cfg.normalize_obs,
    )
    dev = device if device is not None else model_cfg.device
    if dev is not None:
        rnd = rnd.to(_resolve_device(dev))
    return rnd


def build_models(
    cfg: Any = None,
    obs_shape: Optional[Tuple[int, int, int]] = None,
    num_actions: Optional[int] = None,
    device: Optional[Union[str, Any]] = None,
    **overrides: Any,
) -> Dict[str, Any]:
    """Convenience factory returning ``{"policy", "rnd", "config", "device"}``."""
    model_cfg = _coerce_config(cfg, **overrides)
    policy = build_policy(model_cfg, obs_shape=obs_shape, num_actions=num_actions, device=device)
    rnd = None
    if model_cfg.use_rnd:
        rnd = build_rnd(model_cfg, obs_shape=obs_shape, device=device)
    return {
        "policy": policy,
        "rnd": rnd,
        "config": model_cfg,
        "device": _resolve_device(device if device is not None else model_cfg.device),
    }


def count_parameters(module: Any) -> int:
    """Number of trainable parameters of a module."""
    if module is None or not _HAS_TORCH:
        return 0
    return int(sum(p.numel() for p in module.parameters() if p.requires_grad))


def save_model_state(path: str, policy: Any = None, rnd: Any = None, extra: Optional[Mapping[str, Any]] = None) -> str:
    """Save policy / RND weights (plus any extra payload) to ``path``."""
    _require_torch()
    import os

    state: Dict[str, Any] = dict(extra or {})
    if policy is not None:
        state["policy"] = policy.state_dict()
    if rnd is not None:
        state["rnd"] = rnd.state_dict()
    directory = os.path.dirname(os.path.abspath(path))
    if directory:
        os.makedirs(directory, exist_ok=True)
    torch.save(state, path)  # type: ignore[union-attr]
    return path


def load_model_state(path: str, policy: Any = None, rnd: Any = None, map_location: str = "cpu") -> Dict[str, Any]:
    """Load weights saved by :func:`save_model_state` into ``policy`` / ``rnd``."""
    _require_torch()
    state = torch.load(path, map_location=map_location)  # type: ignore[union-attr]
    if policy is not None and isinstance(state, Mapping) and state.get("policy") is not None:
        policy.load_state_dict(state["policy"])
    if rnd is not None and isinstance(state, Mapping) and state.get("rnd") is not None:
        rnd.load_state_dict(state["rnd"])
    return state if isinstance(state, Mapping) else {"state": state}


# --------------------------------------------------------------------------------------
# Internal helpers
# --------------------------------------------------------------------------------------


def _require_torch() -> None:
    if not _HAS_TORCH:
        raise RuntimeError(
            "PyTorch is required to build the Montezuma networks. Install torch "
            "(>= 2.1) to use src.montezuma.model."
        )


def _make_activation(name: str) -> Any:
    name = (name or "relu").lower()
    if name in ("relu",):
        return nn.ReLU(inplace=False)
    if name in ("leaky_relu", "leakyrelu", "lrelu"):
        return nn.LeakyReLU(negative_slope=0.01, inplace=False)
    if name == "elu":
        return nn.ELU(inplace=False)
    if name == "tanh":
        return nn.Tanh()
    raise ValueError(f"Unsupported activation: {name!r}")


def _prepare_obs(obs: Any, in_channels: int = FRAME_STACK, normalize: bool = True) -> Any:
    """Coerce a batch of observations into a float ``(B, C, H, W)`` tensor."""
    _require_torch()
    if isinstance(obs, Mapping):  # Meta-World-style dict (not used for Atari)
        obs = next(iter(obs.values()))
    if not isinstance(obs, torch.Tensor):  # type: ignore[union-attr]
        obs = torch.as_tensor(_as_array(obs))  # type: ignore[union-attr]
    if obs.dim() == 3:
        obs = obs.unsqueeze(0)
    if obs.dim() != 4:
        raise ValueError(f"Expected a 3-D or 4-D observation, got shape {tuple(obs.shape)}")
    # (B, H, W, C) -> (B, C, H, W) when the channels are last and obviously so.
    if obs.shape[-1] == in_channels and obs.shape[1] != in_channels:
        obs = obs.permute(0, 3, 1, 2)
    obs = obs.float()
    if normalize and float(obs.max()) > 1.5:
        obs = obs / 255.0
    return obs


def _is_single_obs(obs: Any) -> bool:
    if obs is None:
        return False
    shape = getattr(obs, "shape", None)
    if shape is None:
        return True
    return len(tuple(shape)) == 3


def _batchify(obs: Any) -> Any:
    if isinstance(obs, Mapping):
        obs = next(iter(obs.values()))
    if not isinstance(obs, torch.Tensor):  # type: ignore[union-attr]
        obs = torch.as_tensor(_as_array(obs))  # type: ignore[union-attr]
    if obs.dim() == 3:
        obs = obs.unsqueeze(0)
    return obs


def _as_long(actions: Any) -> Any:
    if isinstance(actions, torch.Tensor):  # type: ignore[union-attr]
        return actions.long().reshape(-1)
    return torch.as_tensor(_as_array(actions)).long().reshape(-1)  # type: ignore[union-attr]


def _resolve_device(device: Any) -> Any:
    if not _HAS_TORCH:
        return device
    if device is None:
        return torch.device("cpu")  # type: ignore[union-attr]
    if isinstance(device, torch.device):  # type: ignore[union-attr]
        return device
    device_str = str(device)
    if device_str.startswith("cuda") and not torch.cuda.is_available():  # type: ignore[union-attr]
        return torch.device("cpu")  # type: ignore[union-attr]
    return torch.device(device_str)  # type: ignore[union-attr]


def _as_array(x: Any) -> Any:
    if x is None:
        return _zeros((0,))
    if isinstance(x, torch.Tensor):  # type: ignore[union-attr]
        x = x.detach().cpu().numpy()
    if np is not None:
        return np.asarray(x)
    return x  # pragma: no cover


def _zeros(shape: Sequence[int]) -> Any:
    if np is not None:
        return np.zeros(tuple(shape), dtype=np.float64)
    return [0.0 for _ in range(int(shape[0]))]


def _concat(a: Any, b: Any) -> Any:
    if np is not None:
        return np.concatenate([np.asarray(a).reshape(-1), np.asarray(b).reshape(-1)])
    return list(a) + list(b)  # pragma: no cover


def _tolist(value: Any) -> Any:
    if np is not None and isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, (list, tuple)):
        return [float(v) for v in value]
    try:
        return float(value)
    except Exception:  # pragma: no cover
        return value


def _fromlist(value: Any, shape: Tuple[int, ...]) -> Any:
    if value is None:
        return RunningMeanStd._zeros(shape)
    if np is not None:
        return np.array(value, dtype=np.float64).reshape(shape) if shape else np.asarray(value, dtype=np.float64)
    return float(value)  # pragma: no cover


def _coerce_config(cfg: Any, **overrides: Any) -> MontezumaModelConfig:
    """Accept a :class:`MontezumaModelConfig`, a config mapping, or ``None``."""
    if isinstance(cfg, MontezumaModelConfig):
        return cfg.with_overrides(**overrides) if overrides else cfg
    return MontezumaModelConfig.from_config(cfg, **overrides)


def _get_block(cfg: Any, key: str) -> Optional[Any]:
    if cfg is None:
        return None
    if isinstance(cfg, Mapping):
        value = cfg.get(key)
    else:
        value = getattr(cfg, key, None)
    if value is None:
        return None
    if isinstance(value, Mapping):
        return value
    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return value


def _first(block: Any, *keys: str) -> Any:
    """First present key of ``block`` (mapping or object), else ``None``."""
    if not block:
        return None
    for key in keys:
        if isinstance(block, Mapping):
            if key in block and block[key] is not None:
                return block[key]
        else:
            value = getattr(block, key, None)
            if value is not None:
                return value
    return None


def _filter_fields(cls: Any, values: Mapping[str, Any]) -> Dict[str, Any]:
    """Keep only keys that correspond to dataclass fields (and are not ``None``)."""
    names = set(getattr(cls, "__dataclass_fields__", {}).keys())
    out: Dict[str, Any] = {}
    for key, value in values.items():
        if key in names and value is not None:
            out[key] = value
    return out


# --------------------------------------------------------------------------------------
# CLI (smoke test / parameter report)
# --------------------------------------------------------------------------------------


def main(argv: Optional[Sequence[str]] = None) -> int:
    """Print a short parameter report and run a forward-pass smoke test."""
    import argparse

    parser = argparse.ArgumentParser(description="Montezuma PPO + RND model utilities")
    parser.add_argument("--config", type=str, default=None, help="optional YAML config")
    parser.add_argument("--set", nargs="*", default=[], help="config overrides key=value")
    parser.add_argument("--device", type=str, default="cpu")
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--no-smoke-test", action="store_true")
    args = parser.parse_args(argv)

    cfg = None
    if args.config:
        try:
            from src.common.config import load_config

            cfg = load_config(args.config, args.set)
        except Exception as exc:  # pragma: no cover - CLI convenience
            print(f"Could not load config ({exc}); continuing with defaults.")

    if not _HAS_TORCH:
        print("PyTorch is not installed: reporting default hyperparameters only.")
        print(MontezumaModelConfig.from_config(cfg).to_dict())
        return 0

    built = build_models(cfg, device=args.device)
    policy, rnd, model_cfg = built["policy"], built["rnd"], built["config"]
    print("Policy:", policy.describe())
    if rnd is not None:
        print("RND:   ", rnd.describe())

    if not args.no_smoke_test:
        obs = torch.zeros(args.batch_size, *model_cfg.obs_shape)  # type: ignore[union-attr]
        obs = (obs + torch.rand_like(obs) * 255.0).to(built["device"])  # type: ignore[union-attr]
        logits, value = policy(obs)
        print("policy forward:", tuple(logits.shape), tuple(value.shape))
        actions = logits.argmax(dim=-1)
        log_prob, entropy, value2 = policy.pi_value(obs, actions)
        print("log_prob/entropy/value:", tuple(log_prob.shape), tuple(entropy.shape), tuple(value2.shape))
        if rnd is not None:
            intrinsic = rnd.intrinsic_reward(obs)
            loss = rnd.loss(obs)
            print("rnd error/loss:", tuple(intrinsic.shape), float(loss.detach().cpu()))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
