"""Goal-reaching ("random singleton function") prior reward distribution.

Paper references
----------------
Section 4.2 (Random Functions as a Prior Reward Distribution), verbatim:

    "The particular mixture we use consists of random singleton functions
    (corresponding to "goal reaching" rewards), random neural networks (MLPs
    with two linear layers), and random linear functions [...] A uniform mixture
    of the three function classes are used during training."

Appendix B (Training Details), verbatim:

    "Random goal-reaching functions are generated by sampling random goals from
    the offline dataset. Specifically we utilize a hindsight experience
    relabelling (Andrychowicz et al., 2017) distribution in accordance with
    (Park et al., 2023a). Given a random selected state, we utilize this state as
    the goal with a 0.2 chance, a future state within the trajectory with a 0.5
    chance, and a completely random state with a 0.3 chance. Reward is set to -1
    for every timestep that the goal is not achieved. A done mask is set to True
    when the goal is achieved. We ensure that at least one of the samples
    contains the goal state during the encoding process."

Design notes
------------
* The reward is ``-1`` for every timestep the goal is not achieved and ``0``
  once it is (the paper's goal-reaching convention; this is also the convention
  used by the AntMaze evaluation tasks, Appendix "Ant Maze evaluation tasks").
  The done mask is set ``True`` when the goal is achieved.
* Distances are computed in the observation space actually used for the goal
  metric, i.e. the (optionally std-normalized) raw environment observation --
  for ExORL, "Augmented information is not utilized when calculating goal
  distance" (Appendix C.2).
* This module also hosts the small shared :class:`RewardFunction` /
  :class:`RewardPrior` interface implemented by all prior reward classes
  (goal-reaching, linear, random MLP); the other prior modules import it from
  here so that a single internal convention is used everywhere.

Not specified in the paper (documented defaults)
------------------------------------------------
* The goal metric is the (optionally weighted) Euclidean distance; the paper
  only states the goal is a *state* drawn from the dataset. The AntMaze
  goal-reaching evaluation uses a distance of 2 with XY discretization
  (Appendix C.1); the training prior uses the identity metric.
* For the hindsight-relabelled "future state within the trajectory" we use the
  standard geometric distribution ``Geom(1 - p)`` over the remaining trajectory
  steps (Andrychowicz et al., 2017; Park et al., 2023a). The paper does not give
  the geometric parameter; a sensible default of ``0.2`` (mean lookahead 5) is
  used and exposed as a constructor argument.
* The goal is considered achieved at a distance ``<= threshold`` (inclusive);
  the paper's "less than 0.1" for ExORL is realized with ``threshold=0.1``.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

try:  # the replay buffer is optional at import time (allows standalone testing)
    from fre.data.replay import ReplayBuffer
except Exception:  # pragma: no cover - defensive, only used for annotations
    ReplayBuffer = Any  # type: ignore

__all__ = [
    "RewardFunction",
    "RewardPrior",
    "GoalReachingReward",
    "GoalReachingPrior",
    "make_goal_reaching_prior",
    "as_numpy_2d",
    "euclidean_distance",
    "P_GOAL_CURRENT",
    "P_GOAL_FUTURE",
    "P_GOAL_RANDOM",
]

# Hindsight-experience-relabelling probabilities, Appendix B:
# "this state as the goal with a 0.2 chance, a future state within the
#  trajectory with a 0.5 chance, and a completely random state with a 0.3 chance"
P_GOAL_CURRENT = 0.2
P_GOAL_FUTURE = 0.5
P_GOAL_RANDOM = 0.3

# Geometric distribution parameter for the "future state" branch (not specified
# in the paper; matches the common HER formulation of Park et al., 2023a).
DEFAULT_GEOMETRIC_P = 0.2

# Reward convention of the goal-reaching prior (Appendix B).
REWARD_UNREACHED = -1.0
REWARD_REACHED = 0.0


# --------------------------------------------------------------------------- #
# small numeric helpers shared by the prior reward classes
# --------------------------------------------------------------------------- #
def as_numpy_2d(states: Any) -> np.ndarray:
    """Return ``states`` as a 2D float32 array ``(num_states, state_dim)``.

    A flat ``(state_dim,)`` input is promoted to ``(1, state_dim)`` so reward
    functions can be applied to single evaluation states as well as to training
    batches. Torch tensors are detached and moved to the CPU.
    """
    if states is None:
        raise ValueError("states must not be None")
    if hasattr(states, "detach"):  # torch.Tensor
        states = states.detach().cpu().numpy()
    arr = np.asarray(states, dtype=np.float32)
    if arr.ndim == 1:
        arr = arr[None, :]
    if arr.ndim != 2:
        raise ValueError(f"states must be 1D or 2D, got shape {arr.shape}")
    return arr


def euclidean_distance(
    states: np.ndarray,
    goal: np.ndarray,
    weights: Optional[np.ndarray] = None,
) -> np.ndarray:
    """Per-state Euclidean distance between ``states`` and a single ``goal``.

    ``weights`` optionally pre-scales every dimension (the paper normalizes
    ExORL state dimensions by the offline dataset standard deviation, which can
    equivalently be applied to the stored states).
    """
    states = as_numpy_2d(states)
    goal = np.asarray(goal, dtype=np.float32).reshape(-1)
    if states.shape[-1] != goal.shape[-1]:
        raise ValueError(
            f"state dim {states.shape[-1]} does not match goal dim {goal.shape[-1]}"
        )
    delta = states - goal[None, :]
    if weights is not None:
        weights = np.asarray(weights, dtype=np.float32).reshape(-1)
        if weights.shape[0] != goal.shape[0]:
            raise ValueError(
                f"weights dim {weights.shape[0]} does not match state dim {goal.shape[0]}"
            )
        delta = delta * weights[None, :]
    return np.sqrt(np.sum(delta * delta, axis=-1) + 1e-12).astype(np.float32)


# --------------------------------------------------------------------------- #
# shared reward-function interface
# --------------------------------------------------------------------------- #
class RewardFunction(ABC):
    """One sampled reward function ``eta`` from the prior ``p(eta)``.

    Subclasses implement :meth:`_rewards_and_dones`; the public :meth:`label`
    entry point adds the optional "at least one sample contains the goal"
    guarantee required for the encoding set (Appendix B).
    """

    name: str = "reward-function"
    reward_min: float = REWARD_UNREACHED
    reward_max: float = REWARD_REACHED

    @abstractmethod
    def _rewards_and_dones(
        self, states: np.ndarray
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Return ``(rewards, dones)`` for a 2D array of states."""

    def describe(self) -> Dict[str, Any]:
        """Metadata about the sampled function (logging only)."""
        return {
            "name": self.name,
            "reward_min": float(self.reward_min),
            "reward_max": float(self.reward_max),
        }

    def label(
        self,
        states: Any,
        ensure_goal: bool = False,
        rng: Optional[np.random.Generator] = None,
        in_place: bool = True,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Label ``states`` with this reward function.

        Parameters
        ----------
        states : array-like, shape (num_states, state_dim)
        ensure_goal : bool
            For goal-reaching functions, overwrite (per row) one entry with the
            goal so the guarantee of Appendix B holds. Ignored by function
            classes without an explicit target.
        rng : np.random.Generator, optional
            Randomness for the ``ensure_goal`` placement.
        in_place : bool
            Whether ``ensure_goal`` may overwrite entries of the given array.

        Returns
        -------
        rewards : np.ndarray, shape (num_states,), float32
        dones : np.ndarray, shape (num_states,), bool
        """
        arr = as_numpy_2d(states)
        if ensure_goal:
            arr = self.ensure_goal_in_set(arr, rng=rng, in_place=in_place)
        rewards, dones = self._rewards_and_dones(arr)
        return (
            np.asarray(rewards, dtype=np.float32).reshape(-1),
            np.asarray(dones, dtype=bool).reshape(-1),
        )

    def ensure_goal_in_set(
        self,
        states: np.ndarray,
        rng: Optional[np.random.Generator] = None,
        in_place: bool = True,
    ) -> np.ndarray:
        """Force at least one state in each row to attain the target (no-op here)."""
        return states

    def __call__(self, states: Any) -> np.ndarray:
        """Reward values ``eta(s)`` only."""
        rewards, _ = self.label(states)
        return rewards


class RewardPrior(ABC):
    """Distribution ``p(eta)`` over reward functions of one class."""

    name: str = "reward-prior"

    @abstractmethod
    def sample(self, rng: Optional[np.random.Generator] = None) -> RewardFunction:
        """Draw one reward function from ``p(eta)``."""

    def sample_many(
        self, num_samples: int = 1, rng: Optional[np.random.Generator] = None
    ) -> List[RewardFunction]:
        return [self.sample(rng=rng) for _ in range(int(num_samples))]

    def describe(self) -> Dict[str, Any]:
        return {"name": self.name}

    def __call__(self, rng: Optional[np.random.Generator] = None) -> RewardFunction:
        return self.sample(rng=rng)


# --------------------------------------------------------------------------- #
# goal-reaching reward function
# --------------------------------------------------------------------------- #
class GoalReachingReward(RewardFunction):
    """Singleton reward function: ``eta(s) = 0`` if ``s`` reaches the goal else ``-1``.

    Appendix B: "Reward is set to -1 for every timestep that the goal is not
    achieved. A done mask is set to True when the goal is achieved."
    """

    name = "goal-reaching"

    def __init__(
        self,
        goal: np.ndarray,
        threshold: float = 0.0,
        metric_weights: Optional[np.ndarray] = None,
        reward_unreached: float = REWARD_UNREACHED,
        reward_reached: float = REWARD_REACHED,
        terminate_on_success: bool = True,
    ) -> None:
        """
        Parameters
        ----------
        goal : np.ndarray, shape (state_dim,)
            Target state sampled from the offline dataset.
        threshold : float
            Success radius. ``threshold=0.0`` (the training-prior default) means
            the goal is attained only at the exact goal state; evaluation tasks
            use larger radii (2 for AntMaze goal-reaching, 0.1 for ExORL goals).
        metric_weights : np.ndarray, optional
            Optional per-dimension weights for the distance metric.
        reward_unreached / reward_reached : float
            Reward before / after the goal is attained (-1 and 0 by default).
        terminate_on_success : bool
            Whether the done mask is set when the goal is attained (True per
            Appendix B).
        """
        self.goal = np.asarray(goal, dtype=np.float32).reshape(-1)
        self.threshold = float(threshold)
        self.metric_weights = (
            None
            if metric_weights is None
            else np.asarray(metric_weights, dtype=np.float32).reshape(-1)
        )
        self.reward_unreached = float(reward_unreached)
        self.reward_reached = float(reward_reached)
        self.terminate_on_success = bool(terminate_on_success)
        self.reward_min = min(self.reward_unreached, self.reward_reached)
        self.reward_max = max(self.reward_unreached, self.reward_reached)

    # ------------------------------------------------------------------ #
    def distance(self, states: Any) -> np.ndarray:
        """Per-state distance to the goal."""
        return euclidean_distance(states, self.goal, weights=self.metric_weights)

    def _rewards_and_dones(
        self, states: np.ndarray
    ) -> Tuple[np.ndarray, np.ndarray]:
        achieved = self.distance(states) <= self.threshold
        rewards = np.where(
            achieved, self.reward_reached, self.reward_unreached
        ).astype(np.float32)
        dones = achieved.astype(bool) if self.terminate_on_success else np.zeros_like(
            achieved, dtype=bool
        )
        return rewards, dones

    def ensure_goal_in_set(
        self,
        states: np.ndarray,
        rng: Optional[np.random.Generator] = None,
        in_place: bool = True,
    ) -> np.ndarray:
        """Guarantee the encoding set contains the goal state (Appendix B).

        "We ensure that at least one of the samples contains the goal state
        during the encoding process." One randomly chosen row is replaced by the
        goal state. If every row already attains the goal the array is returned
        unchanged.
        """
        states = as_numpy_2d(states).copy() if not in_place else as_numpy_2d(states)
        num_states = states.shape[0]
        if num_states == 0:
            return states
        if np.any(self.distance(states) <= self.threshold):
            return states
        if rng is None:
            rng = np.random.default_rng()
        index = int(rng.integers(0, num_states))
        states[index, :] = self.goal
        return states

    def describe(self) -> Dict[str, Any]:
        info = super().describe()
        info.update(
            {
                "threshold": self.threshold,
                "goal": self.goal.tolist(),
                "reward_unreached": self.reward_unreached,
                "reward_reached": self.reward_reached,
            }
        )
        return info


# --------------------------------------------------------------------------- #
# goal-reaching sampler (HER distribution, Appendix B)
# --------------------------------------------------------------------------- #
class GoalReachingPrior(RewardPrior):
    """Samples random singleton goal-reaching reward functions from the dataset.

    Goals are drawn with the hindsight experience relabelling distribution of
    Appendix B: the current state with probability 0.2, a future state within
    the same trajectory with probability 0.5, and a completely random dataset
    state with probability 0.3.
    """

    name = "goal-reaching"

    def __init__(
        self,
        replay_buffer: ReplayBuffer,
        threshold: float = 0.0,
        metric_weights: Optional[np.ndarray] = None,
        p_current: float = P_GOAL_CURRENT,
        p_future: float = P_GOAL_FUTURE,
        p_random: float = P_GOAL_RANDOM,
        geometric_p: float = DEFAULT_GEOMETRIC_P,
        reward_unreached: float = REWARD_UNREACHED,
        reward_reached: float = REWARD_REACHED,
        terminate_on_success: bool = True,
        seed: int = 0,
    ) -> None:
        self.buffer = replay_buffer
        self.threshold = float(threshold)
        self.metric_weights = (
            None
            if metric_weights is None
            else np.asarray(metric_weights, dtype=np.float32).reshape(-1)
        )
        total = float(p_current) + float(p_future) + float(p_random)
        if total <= 0:
            raise ValueError("goal probabilities must sum to a positive value")
        self.p_current = float(p_current) / total
        self.p_future = float(p_future) / total
        self.p_random = float(p_random) / total
        self.geometric_p = float(geometric_p)
        self.reward_unreached = float(reward_unreached)
        self.reward_reached = float(reward_reached)
        self.terminate_on_success = bool(terminate_on_success)
        self._rng = np.random.default_rng(seed)

    # ------------------------------------------------------------------ #
    def _rng_for(self, rng: Optional[np.random.Generator]) -> np.random.Generator:
        return self._rng if rng is None else rng

    def sample_goal(
        self, rng: Optional[np.random.Generator] = None
    ) -> Tuple[np.ndarray, str]:
        """Draw one goal state and report which HER branch produced it.

        Returns ``(goal, branch)`` with ``branch`` in
        ``{"current", "future", "random"}``.
        """
        rng = self._rng_for(rng)
        # Reference (relabelling) state drawn uniformly from the dataset.
        states, traj_index, step_index = self.buffer.sample_states_with_metadata(
            1, rng=rng
        )
        reference = states[0]
        branch_draw = float(rng.random())

        if branch_draw < self.p_current:
            return reference.astype(np.float32), "current"

        if branch_draw < self.p_current + self.p_future:
            # Future state within the same trajectory (geometric lookahead).
            length = int(self.buffer.trajectory_length(int(traj_index[0])))
            start = int(step_index[0])
            if length <= 0:
                return reference.astype(np.float32), "current"
            offset = int(rng.geometric(self.geometric_p)) if self.geometric_p > 0 else 1
            future_step = min(start + max(offset, 1), length - 1)
            goal = self.buffer.state_at(int(traj_index[0]), future_step)
            if goal is None:
                return reference.astype(np.float32), "current"
            return np.asarray(goal, dtype=np.float32), "future"

        random_states = self.buffer.sample_states(1, rng=rng)
        return np.asarray(random_states[0], dtype=np.float32), "random"

    def sample(self, rng: Optional[np.random.Generator] = None) -> GoalReachingReward:
        """Draw one goal-reaching reward function ``eta``."""
        goal, _ = self.sample_goal(rng=rng)
        return GoalReachingReward(
            goal=goal,
            threshold=self.threshold,
            metric_weights=self.metric_weights,
            reward_unreached=self.reward_unreached,
            reward_reached=self.reward_reached,
            terminate_on_success=self.terminate_on_success,
        )

    def label(
        self,
        states: Any,
        rng: Optional[np.random.Generator] = None,
        ensure_goal: bool = True,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Convenience: sample a function and immediately label ``states``."""
        function = self.sample(rng=rng)
        return function.label(states, ensure_goal=ensure_goal, rng=rng)

    def describe(self) -> Dict[str, Any]:
        info = super().describe()
        info.update(
            {
                "p_current": self.p_current,
                "p_future": self.p_future,
                "p_random": self.p_random,
                "geometric_p": self.geometric_p,
                "threshold": self.threshold,
                "reward_unreached": self.reward_unreached,
                "reward_reached": self.reward_reached,
            }
        )
        return info


def make_goal_reaching_prior(
    replay_buffer: ReplayBuffer,
    threshold: float = 0.0,
    metric_weights: Optional[np.ndarray] = None,
    seed: int = 0,
    **kwargs: Any,
) -> GoalReachingPrior:
    """Factory matching the other prior factories (``make_*_prior``)."""
    return GoalReachingPrior(
        replay_buffer=replay_buffer,
        threshold=threshold,
        metric_weights=metric_weights,
        seed=seed,
        **kwargs,
    )
