"""GC-IQL baseline: goal-conditioned implicit Q-learning.

Paper specification (Addendum, "Additional Details on GC-IQL"):

    "GC-IQL is just IQL with the additional goal state.

     Specifically, given a random state, a random goal state is sampled from
     1) future states in the trajectory using a geometric distribution,
     2) a random goal in the dataset, or 3) the current state is the goal,
     in which case the reward is 0 and the mask/terminal flag is True. In
     other cases, reward is -1.  The ratio is p_randomgoal=0.3,
     p_geometric_goal=0.5, p_current_goal=0.2.

     To give the information to the neural network, goals and observations are
     concatenated.

     No environment rewards are used to train GC-IQL.  The reward passed to IQL
     are the goal-conditioned rewards generated by the preprocessor as
     described above, which is 0 if the state==goal and -1 otherwise.

     Evaluation: the goal-conditioned agent is given the ground-truth goal that
     the specific evaluation task contains, to condition on."

Implementation notes
--------------------
* The goal is supplied to the shared IQL implementation
  (:class:`fre.rl.iql.IQL`) through its ``z`` argument: IQL concatenates ``z``
  to the observation, which is *exactly* "goals and observations are
  concatenated" from the addendum.  ``latent_dim`` is therefore set to the goal
  dimension instead of FRE's 128-dim task latent.
* Hindsight relabeling is implemented on flat dataset indices so the geometric
  goal really is a *future state of the same trajectory* as the anchor state
  (this is what the "geometric distribution over future states" means).  A
  trajectory index is derived from ``terminals``/``timeouts`` when the replay
  buffer does not expose one.
* For AntMaze the ground-truth goals live on the same 32-bin XY grid that FRE,
  GC-BC and OPAL are evaluated on, so goal achievement can be checked with
  exact equality (shared discretization, see ``fre/envs/antmaze_eval.py``).
  For continuous domains a small equality tolerance is used.
"""

from __future__ import annotations

import inspect
import os
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple

import numpy as np
import torch

from fre.rl.iql import IQL

__all__ = [
    "P_RANDOM_GOAL",
    "P_GEOMETRIC_GOAL",
    "P_CURRENT_GOAL",
    "GEOMETRIC_P",
    "GOAL_TYPES",
    "GoalBatch",
    "FlatTrajectoryIndex",
    "GoalSampler",
    "GCIQL",
    "make_gc_iql",
    "train_gc_iql",
    "make_gc_policy_fn",
    "goal_rewards_and_dones",
]

# ---------------------------------------------------------------------------
# Paper-exact constants (Addendum: "Additional Details on GC-IQL")
# ---------------------------------------------------------------------------
P_RANDOM_GOAL = 0.3
P_GEOMETRIC_GOAL = 0.5
P_CURRENT_GOAL = 0.2

# The addendum says "a geometric distribution" without giving its parameter.
# p = 0.5 (i.e. mean offset of 2 steps) is the value used by the
# controllable_agent / HIQL style goal samplers; documented default.
GEOMETRIC_P = 0.5

# Goal types, in the canonical order used by `GoalSampler`.
GOAL_TYPES = ("current", "geometric", "random")
_CURRENT, _GEOMETRIC, _RANDOM = 0, 1, 2


# ---------------------------------------------------------------------------
# Reward / done preprocessor
# ---------------------------------------------------------------------------
def goal_rewards_and_dones(
    states: np.ndarray,
    goals: np.ndarray,
    tolerance: float = 0.0,
) -> Tuple[np.ndarray, np.ndarray]:
    """Goal-conditioned reward preprocessor of the GC-IQL baseline.

    ``reward = 0`` if ``state == goal`` (within ``tolerance``), else ``-1``;
    the terminal/done flag is ``True`` exactly when the goal is achieved.

    Returns ``(rewards, dones)`` both of shape ``(B,)`` (float32 / bool).
    """
    states = np.asarray(states, dtype=np.float64)
    goals = np.asarray(goals, dtype=np.float64)
    if states.shape != goals.shape:
        states = np.reshape(states, goals.shape)
    if tolerance and tolerance > 0.0:
        distance = np.linalg.norm(states - goals, axis=-1)
        reached = distance <= tolerance
    else:
        reached = np.all(states == goals, axis=-1)
    rewards = np.where(reached, 0.0, -1.0).astype(np.float32)
    dones = reached.astype(bool)
    return rewards, dones


@dataclass
class GoalBatch:
    """A batch of hindsight-relabelled goals for GC-IQL."""

    states: np.ndarray           # (B, obs_dim) anchor states
    goals: np.ndarray            # (B, goal_dim)
    rewards: np.ndarray          # (B,)  0 if s == g else -1
    dones: np.ndarray            # (B,)  bool
    types: np.ndarray            # (B,)  int, index into GOAL_TYPES
    dataset_indices: Optional[np.ndarray] = None

    def __len__(self) -> int:
        return int(self.states.shape[0])

    @property
    def batch_size(self) -> int:
        return len(self)

    def type_counts(self) -> Dict[str, int]:
        counts = {name: 0 for name in GOAL_TYPES}
        for t in np.asarray(self.types).reshape(-1):
            counts[GOAL_TYPES[int(t)]] += 1
        return counts

    def as_dict(self) -> Dict[str, Any]:
        return {
            "states": self.states,
            "goals": self.goals,
            "rewards": self.rewards,
            "dones": self.dones,
            "types": self.types,
        }


# ---------------------------------------------------------------------------
# Trajectory bookkeeping (needed for "future states in the trajectory")
# ---------------------------------------------------------------------------
class FlatTrajectoryIndex:
    """Flat dataset arrays plus trajectory boundaries.

    Provides everything the geometric goal sampler needs:
    ``observations``, ``actions``, ``next_observations``, ``terminals`` and,
    per flat index, the id of the episode it belongs to and the last index of
    that episode.

    Built from a :class:`fre.rl.replay_buffer.ReplayBuffer`-like object; every
    access is defensive because the buffer may expose either attributes or
    properties (or neither).
    """

    def __init__(
        self,
        observations: np.ndarray,
        actions: Optional[np.ndarray] = None,
        next_observations: Optional[np.ndarray] = None,
        terminals: Optional[np.ndarray] = None,
        trajectory_ids: Optional[np.ndarray] = None,
        timeouts: Optional[np.ndarray] = None,
    ) -> None:
        observations = np.asarray(observations)
        if observations.ndim != 2:
            raise ValueError(
                f"FlatTrajectoryIndex expects (N, D) observations, got {observations.shape}"
            )
        self.observations = observations.astype(np.float32)
        n = self.observations.shape[0]

        self.actions = None if actions is None else np.asarray(actions, dtype=np.float32)
        if next_observations is None:
            # Reconstruct by shifting within trajectories (fall back to self).
            nxt = self.observations.copy()
            if n > 1:
                nxt[:-1] = self.observations[1:]
            self.next_observations = nxt
        else:
            self.next_observations = np.asarray(next_observations, dtype=np.float32)

        if terminals is None:
            self.terminals = np.zeros(n, dtype=bool)
        else:
            self.terminals = np.asarray(terminals).reshape(-1).astype(bool)

        if timeouts is None:
            self.timeouts = np.zeros(n, dtype=bool)
        else:
            self.timeouts = np.asarray(timeouts).reshape(-1).astype(bool)

        if trajectory_ids is None:
            trajectory_ids = self._infer_trajectory_ids()
        self.trajectory_ids = np.asarray(trajectory_ids).reshape(-1).astype(np.int64)

        self.traj_starts, self.traj_ends, self.traj_lengths = self._boundaries()

    # -- construction helpers ------------------------------------------------
    def _infer_trajectory_ids(self) -> np.ndarray:
        """Episode ids from terminals/timeouts (either flag ends an episode)."""
        n = self.observations.shape[0]
        if n == 0:
            return np.zeros(0, dtype=np.int64)
        ends = self.terminals | self.timeouts
        if not np.any(ends):
            # A single (very long) trajectory.
            return np.zeros(n, dtype=np.int64)
        new_episode = np.concatenate([[True], ends[:-1]])
        return np.cumsum(new_episode).astype(np.int64) - 1

    def _boundaries(self) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        ids = self.trajectory_ids
        n = ids.shape[0]
        if n == 0:
            empty = np.zeros(0, dtype=np.int64)
            return empty, empty, empty
        num_traj = int(ids.max()) + 1
        starts = np.full(num_traj, n, dtype=np.int64)
        ends = np.full(num_traj, -1, dtype=np.int64)
        for i in range(n):
            t = int(ids[i])
            if i < starts[t]:
                starts[t] = i
            if i > ends[t]:
                ends[t] = i
        lengths = ends - starts + 1
        return starts, ends, np.maximum(lengths, 0)

    # -- sampling ------------------------------------------------------------
    @property
    def num_transitions(self) -> int:
        return int(self.observations.shape[0])

    @property
    def obs_dim(self) -> int:
        return int(self.observations.shape[1])

    def sample_indices(self, num: int, rng: Optional[np.random.Generator] = None) -> np.ndarray:
        rng = np.random.default_rng() if rng is None else rng
        return rng.integers(0, self.num_transitions, size=int(num))

    def future_indices(
        self,
        indices: np.ndarray,
        geometric_p: float = GEOMETRIC_P,
        rng: Optional[np.random.Generator] = None,
    ) -> np.ndarray:
        """Geometric-distributed future index inside the same trajectory."""
        rng = np.random.default_rng() if rng is None else rng
        indices = np.asarray(indices, dtype=np.int64).reshape(-1)
        offsets = rng.geometric(p=float(geometric_p), size=indices.shape[0])
        candidate = indices + offsets
        end = self.traj_ends[self.trajectory_ids[indices]]
        return np.minimum(candidate, end)

    def transitions(self, indices: np.ndarray) -> Dict[str, np.ndarray]:
        """Materialise a transition batch for the given flat indices."""
        indices = np.asarray(indices, dtype=np.int64).reshape(-1)
        batch: Dict[str, np.ndarray] = {
            "observations": self.observations[indices],
            "next_observations": self.next_observations[indices],
            "terminals": self.terminals[indices].astype(np.float32),
            "dones": self.terminals[indices].astype(np.float32),
            "timeouts": self.timeouts[indices].astype(np.float32),
        }
        if self.actions is not None:
            batch["actions"] = self.actions[indices]
        # Aliases used by fre.rl.iql.IQL.
        batch["obs"] = batch["observations"]
        batch["next_obs"] = batch["next_observations"]
        return batch

    # -- factory -------------------------------------------------------------
    @classmethod
    def from_dataset(cls, dataset: Any) -> "FlatTrajectoryIndex":
        def _get(*names: str) -> Optional[Any]:
            for name in names:
                value = getattr(dataset, name, None)
                if value is None:
                    continue
                if callable(value):
                    try:
                        value = value()
                    except TypeError:
                        continue
                return value
            return None

        observations = _get("observations", "states", "obs")
        if observations is None:
            raise ValueError(
                "Dataset does not expose flat 'observations'/'states' arrays; cannot "
                "build a FlatTrajectoryIndex."
            )
        actions = _get("actions")
        next_observations = _get("next_observations", "next_states")
        terminals = _get("terminals", "dones")
        timeouts = _get("timeouts")
        trajectory_ids = _get("trajectory_ids", "episode_ids")
        return cls(
            observations=observations,
            actions=actions,
            next_observations=next_observations,
            terminals=terminals,
            trajectory_ids=trajectory_ids,
            timeouts=timeouts,
        )


# ---------------------------------------------------------------------------
# Goal sampler
# ---------------------------------------------------------------------------
class GoalSampler:
    """HER goal sampling with the GC-IQL ratios 0.2 / 0.5 / 0.3.

    * ``current``  (p = 0.2): the goal *is* the anchor state -> reward 0, done.
    * ``geometric``(p = 0.5): a future state of the same trajectory, sampled
      from a geometric distribution (clipped to the end of the episode).
    * ``random``   (p = 0.3): a uniformly random state from the dataset.
    """

    def __init__(
        self,
        dataset: Any = None,
        traj_index: Optional[FlatTrajectoryIndex] = None,
        p_current_goal: float = P_CURRENT_GOAL,
        p_geometric_goal: float = P_GEOMETRIC_GOAL,
        p_random_goal: float = P_RANDOM_GOAL,
        geometric_p: float = GEOMETRIC_P,
        tolerance: float = 0.0,
        seed: Optional[int] = None,
    ) -> None:
        self.dataset = dataset
        if traj_index is None and dataset is not None:
            try:
                traj_index = FlatTrajectoryIndex.from_dataset(dataset)
            except (ValueError, AttributeError, TypeError):
                traj_index = None
        self.traj_index = traj_index

        total = float(p_current_goal + p_geometric_goal + p_random_goal)
        if total <= 0:
            raise ValueError("Goal sampling probabilities must sum to a positive value.")
        self.probs = np.asarray(
            [
                float(p_current_goal) / total,
                float(p_geometric_goal) / total,
                float(p_random_goal) / total,
            ]
        )
        self.geometric_p = float(geometric_p)
        self.tolerance = float(tolerance)
        self.rng = np.random.default_rng(seed)

    # -- random goal source --------------------------------------------------
    def _random_states(self, num: int) -> np.ndarray:
        if self.traj_index is not None:
            idx = self.traj_index.sample_indices(num, rng=self.rng)
            return self.traj_index.observations[idx]
        # Fallback: ask the dataset for random states.
        if hasattr(self.dataset, "sample_states"):
            states = self.dataset.sample_states(int(num))
            return np.asarray(states, dtype=np.float32)
        if hasattr(self.dataset, "observations"):
            obs = np.asarray(self.dataset.observations)
            idx = self.rng.integers(0, obs.shape[0], size=int(num))
            return obs[idx]
        raise ValueError("Cannot sample random goal states from the given dataset.")

    def _future_states(self, anchor_indices: np.ndarray, anchor_states: np.ndarray) -> np.ndarray:
        if self.traj_index is not None:
            future = self.traj_index.future_indices(
                anchor_indices, geometric_p=self.geometric_p, rng=self.rng
            )
            return self.traj_index.observations[future]
        # Fallback (no trajectory structure available): approximate the future
        # goal with an independent random dataset state.
        return self._random_states(anchor_states.shape[0])

    # -- main API ------------------------------------------------------------
    def sample(
        self,
        states: np.ndarray,
        indices: Optional[np.ndarray] = None,
        goals: Optional[np.ndarray] = None,
    ) -> GoalBatch:
        """Sample goals for the given anchor ``states`` ``(B, obs_dim)``."""
        states = np.asarray(states, dtype=np.float32)
        batch_size = int(states.shape[0])
        types = self.rng.choice(3, size=batch_size, p=self.probs).astype(np.int64)
        if goals is None:
            goals = np.array(states, dtype=np.float32, copy=True)

        if indices is None:
            indices = np.full(batch_size, -1, dtype=np.int64)
        else:
            indices = np.asarray(indices, dtype=np.int64).reshape(-1)

        # current goals: goal := state (already set).
        geom_mask = types == _GEOMETRIC
        rand_mask = types == _RANDOM

        if np.any(geom_mask):
            geom_idx = indices[geom_mask]
            if np.any(geom_idx < 0) and self.traj_index is not None:
                geom_idx = self.traj_index.sample_indices(int(geom_mask.sum()), rng=self.rng)
            goals[geom_mask] = self._future_states(geom_idx, states[geom_mask])

        if np.any(rand_mask):
            goals[rand_mask] = self._random_states(int(rand_mask.sum()))

        rewards, dones = goal_rewards_and_dones(states, goals, tolerance=self.tolerance)
        return GoalBatch(
            states=states,
            goals=goals,
            rewards=rewards,
            dones=dones,
            types=types,
            dataset_indices=indices if np.all(indices >= 0) else None,
        )


# ---------------------------------------------------------------------------
# GC-IQL agent
# ---------------------------------------------------------------------------
class GCIQL:
    """Goal-conditioned IQL baseline.

    Thin wrapper around :class:`fre.rl.iql.IQL` in which the ``z`` slot carries
    the ground-truth goal (concatenated to the observation, as the addendum
    prescribes).  Rewards are the hindsight goal-conditioned rewards
    (0 if ``s == g`` else -1); environment rewards are never used.
    """

    def __init__(
        self,
        obs_dim: int,
        action_dim: int,
        goal_dim: Optional[int] = None,
        hidden_layers: Sequence[int] = (512, 512, 512),
        activation: str = "relu",
        expectile: float = 0.8,
        temperature: float = 3.0,
        discount: float = 0.88,
        target_update_rate: float = 0.001,
        learning_rate: float = 1e-4,
        grad_clip_norm: float = 10.0,
        tanh_squash: bool = True,
        num_qs: int = 2,
        layernorm: bool = False,
        device: str = "cpu",
        p_current_goal: float = P_CURRENT_GOAL,
        p_geometric_goal: float = P_GEOMETRIC_GOAL,
        p_random_goal: float = P_RANDOM_GOAL,
        geometric_p: float = GEOMETRIC_P,
        equality_tolerance: float = 0.0,
        discretize_fn: Optional[Callable[[np.ndarray], np.ndarray]] = None,
        seed: int = 0,
        **iql_kwargs: Any,
    ) -> None:
        self.obs_dim = int(obs_dim)
        self.action_dim = int(action_dim)
        self.goal_dim = int(goal_dim) if goal_dim is not None else self.obs_dim
        self.target_update_rate = float(target_update_rate)
        self.equality_tolerance = float(equality_tolerance)
        self.discretize_fn = discretize_fn
        self.device = device
        self.rng = np.random.default_rng(seed)

        kwargs: Dict[str, Any] = dict(
            hidden_layers=tuple(hidden_layers),
            activation=activation,
            expectile=expectile,
            temperature=temperature,
            discount=discount,
            target_update_rate=target_update_rate,
            learning_rate=learning_rate,
            grad_clip_norm=grad_clip_norm,
            tanh_squash=tanh_squash,
            num_qs=num_qs,
            layernorm=layernorm,
            device=device,
        )
        kwargs.update(iql_kwargs)
        self.agent = IQL(
            obs_dim=self.obs_dim,
            action_dim=self.action_dim,
            latent_dim=self.goal_dim,
            **kwargs,
        )
        self.agent.to(device)

        self.goal_sampler = GoalSampler(
            dataset=None,
            p_current_goal=p_current_goal,
            p_geometric_goal=p_geometric_goal,
            p_random_goal=p_random_goal,
            geometric_p=geometric_p,
            tolerance=equality_tolerance,
            seed=seed,
        )

    # -- observation preprocessing ------------------------------------------
    def prepare(self, states: np.ndarray) -> np.ndarray:
        """Apply the shared observation preprocessing (e.g. 32-bin AntMaze XY)."""
        states = np.asarray(states, dtype=np.float32)
        if self.discretize_fn is not None:
            states = np.asarray(self.discretize_fn(states), dtype=np.float32)
        return states

    def attach_dataset(self, dataset: Any) -> "GCIQL":
        """Attach the offline dataset so that hindsight goals can be sampled."""
        self.goal_sampler.dataset = dataset
        try:
            self.goal_sampler.traj_index = FlatTrajectoryIndex.from_dataset(dataset)
        except (ValueError, AttributeError, TypeError):
            self.goal_sampler.traj_index = None
        return self

    # -- goal-conditioned reward --------------------------------------------
    def reward_and_done(self, states: np.ndarray, goals: np.ndarray):
        return goal_rewards_and_dones(
            states, goals, tolerance=self.equality_tolerance
        )

    def sample_goals(
        self, states: np.ndarray, indices: Optional[np.ndarray] = None
    ) -> GoalBatch:
        batch = self.goal_sampler.sample(self.prepare(states), indices=indices)
        return batch

    # -- training ------------------------------------------------------------
    def _sample_batch(self, dataset: Any, batch_size: int) -> Tuple[Dict[str, np.ndarray], np.ndarray]:
        """Sample transitions; prefer flat arrays so indices stay available."""
        traj_index = self.goal_sampler.traj_index
        if traj_index is not None and traj_index.actions is not None:
            indices = traj_index.sample_indices(batch_size, rng=self.rng)
            batch = traj_index.transitions(indices)
            batch["rewards"] = self.reward_and_done(
                batch["observations"], batch["observations"]
            )[0]  # placeholder, replaced by goal-conditioned rewards below
            return batch, indices

        # Fall back to the replay buffer's own transition sampler.
        batch = None
        if hasattr(dataset, "sample_transitions"):
            try:
                batch = dataset.sample_transitions(batch_size)
            except TypeError:
                batch = dataset.sample_transitions(batch_size, )
        if batch is None:
            raise ValueError("Dataset does not support transition sampling.")
        batch = dict(batch)
        obs = batch.get("observations", batch.get("obs"))
        batch["observations"] = np.asarray(obs, dtype=np.float32)
        batch["obs"] = batch["observations"]
        nxt = batch.get("next_observations", batch.get("next_obs"))
        batch["next_observations"] = np.asarray(nxt, dtype=np.float32)
        batch["next_obs"] = batch["next_observations"]
        dones = batch.get("terminals", batch.get("dones"))
        if dones is None:
            dones = np.zeros(batch_size, dtype=np.float32)
        batch["terminals"] = np.asarray(dones, dtype=np.float32).reshape(-1)
        batch["dones"] = batch["terminals"]
        return batch, np.full(batch_size, -1, dtype=np.int64)

    def update(
        self,
        dataset: Any,
        batch_size: int = 512,
        target_update: bool = True,
        states: Optional[np.ndarray] = None,
    ) -> Dict[str, float]:
        """One IQL update on goal-relabelled transitions."""
        if states is None:
            batch, indices = self._sample_batch(dataset, batch_size)
            obs = batch["observations"]
            next_obs = batch["next_observations"]
            anchors = obs
        else:
            anchors = self.prepare(np.asarray(states, dtype=np.float32))
            obs, next_obs, indices = anchors, anchors, None
            batch = {
                "observations": obs,
                "obs": obs,
                "next_observations": next_obs,
                "next_obs": next_obs,
                "terminals": np.zeros(anchors.shape[0], dtype=np.float32),
                "dones": np.zeros(anchors.shape[0], dtype=np.float32),
            }
            if hasattr(dataset, "sample_actions"):
                batch["actions"] = dataset.sample_actions(anchors.shape[0])

        goals = self.sample_goals(obs, indices=indices)
        # Goal-conditioned rewards of the GC-IQL preprocessor.
        rewards, dones = self.reward_and_done(obs, goals.goals)
        # Current-goal rows terminate immediately (reward 0, mask True).
        batch = dict(batch)
        batch["terminals"] = dones.astype(np.float32)
        batch["dones"] = dones.astype(np.float32)

        info: Dict[str, float] = {}
        call_kwargs: Dict[str, Any] = {
            "batch": batch,
            "rewards": rewards.astype(np.float32),
            "z": goals.goals.astype(np.float32),
            "next_z": goals.goals.astype(np.float32),
        }
        signature = None
        try:
            signature = inspect.signature(self.agent.update)
        except (TypeError, ValueError):  # pragma: no cover - exotic callables
            signature = None
        if signature is not None and "target_update" in signature.parameters:
            parameter = signature.parameters["target_update"]
            default = parameter.default
            if isinstance(default, float):
                call_kwargs["target_update"] = self.target_update_rate
            elif default is inspect.Parameter.empty:
                call_kwargs["target_update"] = target_update
            else:
                call_kwargs["target_update"] = bool(target_update)
            explicit_polyak = True
        else:
            explicit_polyak = False

        result = self.agent.update(**call_kwargs)
        if isinstance(result, dict):
            info.update(
                {
                    k: float(v)
                    for k, v in result.items()
                    if isinstance(v, (int, float, np.floating))
                }
            )
        if not explicit_polyak and target_update and hasattr(self.agent, "update_targets"):
            self.agent.update_targets(self.target_update_rate)

        counts = goals.type_counts()
        info.setdefault("gc_iql/reward_mean", float(np.mean(rewards)))
        info.setdefault("gc_iql/fraction_success", float(np.mean(dones)))
        for name, count in counts.items():
            info[f"gc_iql/goal_{name}"] = float(count) / max(len(goals), 1)
        return info

    def train_steps(
        self,
        dataset: Any,
        steps: int,
        batch_size: int = 512,
        log_interval: int = 1000,
        logger: Any = None,
        prefix: str = "gc_iql",
    ) -> List[Dict[str, float]]:
        self.attach_dataset(dataset)
        history: List[Dict[str, float]] = []
        for step in range(int(steps)):
            info = self.update(dataset, batch_size=batch_size)
            if (step + 1) % max(int(log_interval), 1) == 0:
                history.append({"step": float(step + 1), **info})
                if logger is not None:
                    try:
                        logger.log_metrics(info, step=step + 1, prefix=prefix)
                    except TypeError:
                        logger.log_metrics({f"{prefix}/{k}": v for k, v in info.items()}, step=step + 1)
        return history

    # -- evaluation helpers --------------------------------------------------
    def select_action(
        self,
        obs: np.ndarray,
        goal: np.ndarray,
        deterministic: bool = True,
        clip: bool = True,
    ) -> np.ndarray:
        obs = self.prepare(np.asarray(obs, dtype=np.float32))
        goal = self.prepare(np.asarray(goal, dtype=np.float32))
        if obs.ndim == 1:
            single = True
            obs_b = obs[None]
        else:
            single = False
            obs_b = obs
        if goal.ndim == 1:
            goal_b = np.broadcast_to(goal[None], (obs_b.shape[0], goal.shape[0])).copy()
        else:
            goal_b = np.broadcast_to(goal, (obs_b.shape[0], goal.shape[-1])).copy()
        action = self.agent.select_action(
            obs_b, goal_b, deterministic=deterministic, clip=clip
        )
        action = np.asarray(action, dtype=np.float32)
        return action[0] if single else action

    def value_of(self, obs: np.ndarray, goal: np.ndarray) -> np.ndarray:
        obs = self.prepare(np.asarray(obs, dtype=np.float32))
        goal = self.prepare(np.asarray(goal, dtype=np.float32))
        return np.asarray(self.agent.value_of(obs, goal), dtype=np.float32)

    # -- persistence ---------------------------------------------------------
    def state_dict(self) -> Dict[str, Any]:
        state = {
            "agent": self.agent.state_dict(),
            "obs_dim": self.obs_dim,
            "action_dim": self.action_dim,
            "goal_dim": self.goal_dim,
        }
        return state

    def save(self, path: str) -> str:
        directory = os.path.dirname(os.path.abspath(path))
        if directory:
            os.makedirs(directory, exist_ok=True)
        torch.save(self.state_dict(), path)
        return path

    def load(self, path: str, map_location: Optional[str] = None) -> "GCIQL":
        payload = torch.load(path, map_location=map_location or self.device)
        state = payload.get("agent", payload)
        if hasattr(self.agent, "load_state_dict"):
            self.agent.load_state_dict(state)
        return self

    def to(self, device: str) -> "GCIQL":
        self.device = device
        self.agent.to(device)
        return self

    # -- factory -------------------------------------------------------------
    @classmethod
    def from_config(
        cls,
        config: Any,
        obs_dim: int,
        action_dim: int,
        goal_dim: Optional[int] = None,
        discretize_fn: Optional[Callable[[np.ndarray], np.ndarray]] = None,
        **overrides: Any,
    ) -> "GCIQL":
        def _cfg(name: str, default: Any) -> Any:
            return getattr(config, name, default)

        kwargs: Dict[str, Any] = dict(
            obs_dim=obs_dim,
            action_dim=action_dim,
            goal_dim=goal_dim,
            hidden_layers=tuple(_cfg("rl_hidden_layers", (512, 512, 512))),
            activation=_cfg("rl_activation", "relu"),
            expectile=_cfg("iql_expectile", 0.8),
            temperature=_cfg("iql_temperature", 3.0),
            discount=_cfg("discount", 0.88),
            target_update_rate=_cfg("target_update_rate", 0.001),
            learning_rate=_cfg("learning_rate", 1e-4),
            grad_clip_norm=_cfg("grad_clip_norm", 10.0),
            tanh_squash=_cfg("rl_tanh_squash", True),
            num_qs=_cfg("rl_num_qs", 2),
            layernorm=_cfg("rl_layernorm", False),
            device=_cfg("device", "cpu"),
            p_current_goal=_cfg("gc_p_current_goal", P_CURRENT_GOAL),
            p_geometric_goal=_cfg("gc_p_geometric_goal", P_GEOMETRIC_GOAL),
            p_random_goal=_cfg("gc_p_random_goal", P_RANDOM_GOAL),
            geometric_p=_cfg("gc_geometric_p", GEOMETRIC_P),
            equality_tolerance=_cfg("gc_equality_tolerance", 0.0),
            discretize_fn=discretize_fn,
            seed=_cfg("seed", 0),
        )
        kwargs.update(overrides)
        return cls(**kwargs)


def make_gc_iql(
    config: Any,
    obs_dim: int,
    action_dim: int,
    goal_dim: Optional[int] = None,
    discretize_fn: Optional[Callable[[np.ndarray], np.ndarray]] = None,
    **overrides: Any,
) -> GCIQL:
    """Build a GC-IQL baseline from a ``fre.config.default.Config``-like object."""
    return GCIQL.from_config(
        config,
        obs_dim,
        action_dim,
        goal_dim=goal_dim,
        discretize_fn=discretize_fn,
        **overrides,
    )


def train_gc_iql(
    config: Any,
    dataset: Any,
    obs_dim: int,
    action_dim: int,
    steps: Optional[int] = None,
    batch_size: Optional[int] = None,
    log_interval: int = 1000,
    logger: Any = None,
    discretize_fn: Optional[Callable[[np.ndarray], np.ndarray]] = None,
    **overrides: Any,
) -> Tuple[GCIQL, List[Dict[str, float]]]:
    """Train the GC-IQL baseline on an offline dataset (convenience driver)."""
    agent = make_gc_iql(
        config,
        obs_dim,
        action_dim,
        discretize_fn=discretize_fn,
        **overrides,
    )
    agent.attach_dataset(dataset)
    if steps is None:
        steps = int(getattr(config, "policy_steps", lambda: 850_000)()) if callable(
            getattr(config, "policy_steps", None)
        ) else int(getattr(config, "policy_steps", 850_000))
    if batch_size is None:
        batch_size = int(getattr(config, "batch_size", 512))
    history = agent.train_steps(
        dataset, steps=int(steps), batch_size=int(batch_size),
        log_interval=log_interval, logger=logger,
    )
    return agent, history


def make_gc_policy_fn(
    agent: GCIQL,
    goal: np.ndarray,
    deterministic: bool = True,
    clip: bool = True,
    discretize: bool = True,
) -> Callable[[np.ndarray], np.ndarray]:
    """Wrap a trained GC-IQL agent into ``act_fn(obs) -> action``.

    The agent is given the ground-truth goal of the evaluation task, exactly as
    the addendum describes.
    """
    goal_arr = np.asarray(goal, dtype=np.float32)

    def act_fn(obs: np.ndarray) -> np.ndarray:
        if discretize:
            return agent.select_action(obs, goal_arr, deterministic=deterministic, clip=clip)
        obs = np.asarray(obs, dtype=np.float32)
        obs_b = obs[None] if obs.ndim == 1 else obs
        goal_b = np.broadcast_to(goal_arr[None], (obs_b.shape[0], goal_arr.shape[-1]))
        action = np.asarray(
            agent.agent.select_action(obs_b, goal_b, deterministic=deterministic, clip=clip),
            dtype=np.float32,
        )
        return action[0] if obs.ndim == 1 else action

    return act_fn
