"""Kickstarting (KS) knowledge-retention loss.

Paper: "Fine-tuning Reinforcement Learning Models is Secretly a Forgetting
Mitigation Problem".

Section 2 (Knowledge retention)::

    L_KS(theta) = E_{s ~ pi_theta}[ D_KL( pi_*(s) || pi_theta(s) ) ]

Appendix C.2 ("Distillation-based methods") defines the per-state divergence

    D_KL^s(p || q) = E_{a ~ p(.|s)} [ log( p(a|s) / q(a|s) ) ]

and the kickstarting objective

    L_KS(theta) = E_{s ~ B_theta}[ D_KL^s( pi_*(.|s) || pi_theta(.|s) ) ]

where ``B_theta`` is a buffer of data gathered by the *online* policy
``pi_theta`` (in contrast to behavioral cloning, whose expectation is over a
buffer of pre-training states).  Note that the KL direction is
``KL(teacher || student)`` -- the teacher ``pi_*`` samples the actions and the
student's log-probability of those actions is maximised (an advantage-weighted
cross-entropy / "kickstarting" distillation objective).

Appendix B.1 (NetHack fine-tuning), *Fine-tuning + KS*:

    "we compute the auxiliary loss on data generated by the online policy.  We
    scaled the loss by a factor of 0.5 and used exponential decay 0.99998,
    where the coefficient was decayed every train step."

Following Wołczyk et al. (2022) knowledge retention is applied to the **actor
only**; the critic coefficient is always 0.

This module provides

* :class:`RolloutBuffer` (alias :data:`OnlineBuffer`) -- a ring buffer of states
  visited by the current policy, optionally storing teacher log-probabilities
  computed at collection time (cheap: no teacher forward pass at update time);
* :class:`Kickstarting` -- the actor-only auxiliary loss with a per-step
  multiplicative coefficient decay (0.5 * 0.99998^t for NetHack);
* :func:`kickstarting_loss` / :func:`ks_loss` -- the functional objective;
* :func:`ks_coef_for` / :func:`ks_config_for` -- the paper's per-environment
  scale (and decay) constants.
"""

from __future__ import annotations

import math
from typing import (
    Any,
    Callable,
    Dict,
    Iterable,
    List,
    Mapping,
    Optional,
    Sequence,
    Tuple,
    Union,
)

try:  # pragma: no cover - torch is optional for docs/tests of the formulas
    import torch
    from torch import Tensor
    import torch.nn as nn
except Exception:  # pragma: no cover
    torch = None  # type: ignore
    Tensor = Any  # type: ignore
    nn = None  # type: ignore


# ---------------------------------------------------------------------------
# Shared helpers (CoefficientSchedule, D_KL^s estimators) live in
# src/retention/behavioral_cloning.py so that BC and KS use exactly the same
# KL estimators and decay machinery.
# ---------------------------------------------------------------------------
_SHARED_IMPORT_ERROR: Optional[BaseException] = None
try:  # relative import when used as part of the ``src.retention`` package
    from .behavioral_cloning import (  # type: ignore
        CoefficientSchedule,
        kl_s_divergence,
        sampled_kl,
        _find_distribution,
        _select_distribution,
        _forward_actor,
    )

    _HAS_SHARED = True
except Exception as _exc:  # pragma: no cover - fallback below
    try:
        from src.retention.behavioral_cloning import (  # type: ignore
            CoefficientSchedule,
            kl_s_divergence,
            sampled_kl,
            _find_distribution,
            _select_distribution,
            _forward_actor,
        )

        _HAS_SHARED = True
    except Exception as _exc2:  # pragma: no cover
        _SHARED_IMPORT_ERROR = _exc
        _HAS_SHARED = False
        CoefficientSchedule = None  # type: ignore
        _DIST_KEYS = ("dist", "distribution", "action_dist", "policy_dist", "distributions")
        _LOGITS_KEYS = ("logits", "action_logits", "policy_logits", "action_head", "pi_logits")

        def kl_s_divergence(p_log_prob, q_log_prob):  # type: ignore
            """``D_KL^s(p||q) = E_{a~p}[log p(a|s) - log q(a|s)]`` (per sample)."""
            if torch is None:
                raise RuntimeError("torch is required for kl_s_divergence")
            return p_log_prob - q_log_prob

        def sampled_kl(student_dist, teacher_dist, direction="forward", actions=None, reparameterize=True):  # type: ignore
            """Monte-Carlo estimate of ``D_KL^s`` from two torch distributions."""
            if torch is None:
                raise RuntimeError("torch is required for sampled_kl")
            sample_dist = teacher_dist if direction == "reverse" else student_dist
            if actions is None:
                if reparameterize and getattr(sample_dist, "has_rsample", False):
                    actions = sample_dist.rsample()
                else:
                    actions = sample_dist.sample()
            teacher_lp = teacher_dist.log_prob(actions)
            student_lp = student_dist.log_prob(actions)
            log_ratio = student_lp - teacher_lp
            if direction == "forward":
                return log_ratio
            return -log_ratio

        def _find_distribution(output, obs=None, forward_fn=None):  # type: ignore
            raise NotImplementedError(
                "behavioral_cloning helpers unavailable; pass a distribution to kickstarting_loss"
            )

        def _select_distribution(output):  # type: ignore
            return _find_distribution(output)

        def _forward_actor(actor, obs, forward_fn=None):  # type: ignore
            if forward_fn is not None:
                return forward_fn(actor, obs)
            return actor(obs)


# ---------------------------------------------------------------------------
# Per-step exponential decay (paper: 0.5 * 0.99998^t, decayed every train step)
# ---------------------------------------------------------------------------
class PerStepDecay:
    """Multiplicative coefficient decay applied once per train step.

    ``value_at(step) = max(min_value, value * decay ** step)``.

    ``decay=None`` gives a constant coefficient (no decay), matching the BC
    protocol of Appendix B.1.
    """

    kind = "per_step"

    def __init__(
        self,
        value: float = 1.0,
        decay: Optional[float] = None,
        min_value: float = 0.0,
        per_step: bool = True,
    ) -> None:
        self.value = float(value)
        self.decay = None if decay is None else float(decay)
        self.min_value = float(min_value)
        self.per_step = bool(per_step)
        self._step = 0

    # -- coefficient ------------------------------------------------------
    def value_at(self, step: int) -> float:
        if self.decay is None:
            return self.value
        coeff = self.value * (self.decay ** max(0, int(step)))
        return max(self.min_value, coeff)

    @property
    def coefficient(self) -> float:
        return self.value_at(self._step)

    @property
    def factor(self) -> float:
        """Current multiplicative factor relative to ``value`` (diagnostics)."""
        if self.decay is None or self.value == 0.0:
            return 1.0
        return self.coefficient / self.value

    # -- bookkeeping ------------------------------------------------------
    def step(self, n: int = 1) -> float:
        self._step += int(n)
        return self.coefficient

    def reset(self) -> None:
        self._step = 0

    @property
    def step_count(self) -> int:
        return self._step

    def state_dict(self) -> Dict[str, Any]:
        return {
            "value": self.value,
            "decay": self.decay,
            "min_value": self.min_value,
            "step": self._step,
        }

    def load_state_dict(self, state: Mapping[str, Any]) -> None:
        if not state:
            return
        self.value = float(state.get("value", self.value))
        decay = state.get("decay", self.decay)
        self.decay = None if decay is None else float(decay)
        self.min_value = float(state.get("min_value", self.min_value))
        self._step = int(state.get("step", self._step))

    def __repr__(self) -> str:  # pragma: no cover - cosmetic
        return (
            f"PerStepDecay(value={self.value}, decay={self.decay}, "
            f"min_value={self.min_value}, step={self._step})"
        )


def _as_schedule(
    schedule: Optional[Any] = None,
    coef: Optional[float] = None,
    decay: Optional[float] = None,
    decay_type: str = "exponential",
    min_coef: float = 0.0,
) -> Any:
    """Normalise the different ways of specifying a coefficient schedule.

    Accepts (in priority order):

    1. an explicit schedule object exposing ``value_at``/``step`` (e.g. the
       shared :class:`~src.retention.behavioral_cloning.CoefficientSchedule`
       or :class:`PerStepDecay`);
    2. ``decay`` given as a float -> per-step multiplicative decay;
    3. ``decay`` given as a callable -> wrapped in ``_CallableSchedule``;
    4. nothing -> constant coefficient.
    """
    if schedule is not None and hasattr(schedule, "value_at"):
        return schedule
    value = 1.0 if coef is None else float(coef)
    if callable(decay):
        return _CallableSchedule(value=value, fn=decay, min_value=min_coef)
    return PerStepDecay(value=value, decay=decay, min_value=min_coef)


class _CallableSchedule:
    """Thin adapter turning ``decay(step) -> float`` into a schedule object."""

    kind = "callable"

    def __init__(self, value: float = 1.0, fn: Optional[Callable[[int], float]] = None,
                 min_value: float = 0.0) -> None:
        self.value = float(value)
        self.fn = fn
        self.min_value = float(min_value)
        self._step = 0

    def value_at(self, step: int) -> float:
        if self.fn is None:
            return self.value
        return max(self.min_value, float(self.fn(int(step))))

    @property
    def coefficient(self) -> float:
        return self.value_at(self._step)

    def step(self, n: int = 1) -> float:
        self._step += int(n)
        return self.coefficient

    def reset(self) -> None:
        self._step = 0

    def state_dict(self) -> Dict[str, Any]:
        return {"value": self.value, "min_value": self.min_value, "step": self._step}

    def load_state_dict(self, state: Mapping[str, Any]) -> None:
        if not state:
            return
        self._step = int(state.get("step", self._step))


# ---------------------------------------------------------------------------
# Online rollout buffer B_theta
# ---------------------------------------------------------------------------
class RolloutBuffer:
    """Buffer ``B_theta`` of states gathered by the online policy.

    Kickstarting's expectation is taken over states visited by the *student*
    (Appendix C.2), so the buffer is fed with the observations produced by the
    acting policy.  Because it is only used for distillation targets, no
    returns/advantages are stored.

    Teacher outputs may be pre-computed at insertion time (``store_teacher``)
    which avoids a teacher forward pass during every update; this matters for
    the Sample-Factory style NetHack runner where actor/critic share a
    backbone.  When pre-computed teacher log-probabilities (or teacher actions)
    are present, the exact reverse KL is
    ``mean( log pi_*(a|s) - log pi_theta(a|s) )`` with gradients flowing only
    through the student term.

    Args:
        capacity: maximum number of transitions kept (ring buffer semantics).
            ``None`` keeps everything.
        store_teacher: whether teacher outputs are stored per sample.
        device: device on which sampled tensors are returned.
        seed: optional seed for the internal sampler.
        obs_key: key under which observations are stored/returned.
    """

    def __init__(
        self,
        capacity: Optional[int] = None,
        store_teacher: bool = False,
        device: Optional[Any] = None,
        seed: Optional[int] = None,
        obs_key: str = "obs",
    ) -> None:
        self.capacity = None if capacity is None else int(capacity)
        self.store_teacher = bool(store_teacher)
        self.device = device
        self.obs_key = obs_key
        self._obs: List[Any] = []
        self._teacher_output: List[Any] = []
        self._teacher_log_prob: List[Any] = []
        self._teacher_action: List[Any] = []
        self._action: List[Any] = []
        self._log_prob: List[Any] = []
        self._weight: List[Any] = []
        self._size = 0
        self._generator: Optional[Any] = None
        if torch is not None:
            self._generator = torch.Generator()
            if seed is not None:
                self._generator.manual_seed(int(seed))

    # -- insertion --------------------------------------------------------
    def add(
        self,
        obs: Any,
        teacher_output: Any = None,
        teacher_log_prob: Any = None,
        teacher_action: Any = None,
        action: Any = None,
        log_prob: Any = None,
        weight: Any = None,
    ) -> None:
        """Append a batch of online-policy observations (and optional targets)."""
        self._obs.append(_to_tensor(obs))
        self._append_optional(self._teacher_output, teacher_output)
        self._append_optional(self._teacher_log_prob, teacher_log_prob)
        self._append_optional(self._teacher_action, teacher_action)
        self._append_optional(self._action, action)
        self._append_optional(self._log_prob, log_prob)
        self._append_optional(self._weight, weight, default=1.0, like=obs)
        self._size += _lead_dim(obs)
        self._trim()

    def _append_optional(self, store: List[Any], value: Any, default: Any = None,
                         like: Any = None) -> None:
        if value is None:
            if default is None:
                store.append(None)
                return
            value = _constant_like(like, default)
        store.append(_to_tensor(value))

    def extend(self, transitions: Any, **kwargs: Any) -> None:
        """Add many transitions.

        ``transitions`` may be a mapping of stacked arrays, a sequence of
        per-transition mappings, or a sequence of objects with attributes
        (e.g. the Sample-Factory trajectory samplers).
        """
        if isinstance(transitions, Mapping):
            self.add(**{k: transitions[k] for k in transitions.keys()}, **kwargs)
            return
        keys = ("obs", "teacher_output", "teacher_log_prob", "teacher_action",
                "action", "log_prob", "weight")
        for item in transitions:
            if isinstance(item, Mapping):
                payload = dict(kwargs)
                payload.update({k: item[k] for k in item.keys()})
            else:
                payload = dict(kwargs)
                for k in keys:
                    if hasattr(item, k):
                        payload[k] = getattr(item, k)
            self.add(**payload)

    def _trim(self) -> None:
        if self.capacity is None or self._size <= self.capacity:
            return
        while self._obs and self._size - _lead_dim(self._obs[0]) >= self.capacity:
            removed = self._obs.pop(0)
            self._size -= _lead_dim(removed)
            for store in (
                self._teacher_output,
                self._teacher_log_prob,
                self._teacher_action,
                self._action,
                self._log_prob,
                self._weight,
            ):
                if store:
                    store.pop(0)

    # -- access -----------------------------------------------------------
    def all_states(self) -> Any:
        return _concat(self._obs)

    @property
    def observations(self) -> Any:
        return self.all_states()

    def clear(self) -> None:
        self._obs.clear()
        self._teacher_output.clear()
        self._teacher_log_prob.clear()
        self._teacher_action.clear()
        self._action.clear()
        self._log_prob.clear()
        self._weight.clear()
        self._size = 0

    def __len__(self) -> int:
        return self._size

    @property
    def store_teacher_log_prob(self) -> bool:
        return self.store_teacher and any(t is not None for t in self._teacher_log_prob)

    # -- sampling ---------------------------------------------------------
    def sample(self, batch_size: Optional[int] = None,
               generator: Optional[Any] = None) -> Dict[str, Any]:
        """Uniformly sample a batch of stored states and their targets."""
        if self._size == 0:
            raise RuntimeError("RolloutBuffer is empty; add online policy data first")
        n = self._size if batch_size is None else min(int(batch_size), self._size)
        gen = generator if generator is not None else self._generator
        if torch is not None and gen is not None:
            idx = torch.randint(0, self._size, (n,), generator=gen)
        elif torch is not None:
            idx = torch.randint(0, self._size, (n,))
        else:  # pragma: no cover
            raise RuntimeError("torch is required for sampling")

        out: Dict[str, Any] = {}
        out[self.obs_key] = self._gather(self._obs, idx)
        for key, store in (
            ("teacher_output", self._teacher_output),
            ("teacher_log_prob", self._teacher_log_prob),
            ("teacher_action", self._teacher_action),
            ("action", self._action),
            ("log_prob", self._log_prob),
            ("weights", self._weight),
        ):
            if not store or all(x is None for x in store):
                continue
            filled = [x if x is not None else _zeros_like(self._obs[i]) for i, x in enumerate(store)]
            out[key] = self._gather(filled, idx)
        out["indices"] = idx
        return out

    def _gather(self, store: Sequence[Any], idx: Any) -> Any:
        if len(store) == 1:
            value = store[0][idx]
        else:
            flat = _concat(store)
            value = flat[idx]
        return _move(value, self.device)

    # -- persistence ------------------------------------------------------
    def state_dict(self) -> Dict[str, Any]:
        return {
            "obs": self._obs,
            "teacher_output": self._teacher_output,
            "teacher_log_prob": self._teacher_log_prob,
            "teacher_action": self._teacher_action,
            "action": self._action,
            "log_prob": self._log_prob,
            "weight": self._weight,
            "size": self._size,
            "capacity": self.capacity,
        }

    def load_state_dict(self, state: Mapping[str, Any]) -> None:
        if not state:
            return
        for key in ("obs", "teacher_output", "teacher_log_prob", "teacher_action",
                    "action", "log_prob", "weight"):
            store = list(state.get(key, []) or [])
            setattr(self, "_" + key, store)
        self._size = int(state.get("size", sum(_lead_dim(o) for o in self._obs)))
        self.capacity = state.get("capacity", self.capacity)

    def __repr__(self) -> str:  # pragma: no cover - cosmetic
        return (
            f"RolloutBuffer(size={self._size}, capacity={self.capacity}, "
            f"store_teacher={self.store_teacher})"
        )


# Backwards/forwards compatible alias used by the training runners.
OnlineBuffer = RolloutBuffer


# ---------------------------------------------------------------------------
# Functional objective
# ---------------------------------------------------------------------------
def kickstarting_loss(
    student_dist: Any,
    teacher_dist: Any = None,
    direction: str = "reverse",
    use_exact_kl: bool = True,
    reduction: str = "mean",
    weight: Any = None,
    student_log_prob: Any = None,
    teacher_log_prob: Any = None,
    actions: Any = None,
) -> Any:
    """Unscaled ``E_{s ~ B_theta}[ D_KL^s ]`` for kickstarting.

    The paper's KS loss uses ``D_KL^s(pi_* || pi_theta)`` (Appendix C.2), i.e.
    actions are drawn from the **teacher**; this corresponds to
    ``direction="reverse"``.  Either

    * both distributions are given (analytic ``torch.distributions.kl_divergence``
      when available, otherwise Monte-Carlo with teacher-sampled actions), or
    * pre-computed log-probabilities of teacher-sampled actions are given, in
      which case the exact per-state estimate ``log pi_* - log pi_theta`` is
      used (gradients flow through the student term only).
    """
    if torch is None:  # pragma: no cover
        raise RuntimeError("torch is required to compute the kickstarting loss")

    if student_log_prob is not None and teacher_log_prob is not None:
        per_state = kl_s_divergence(teacher_log_prob.detach(), student_log_prob)
        return _reduce(per_state, reduction, weight)

    if teacher_dist is None:
        raise ValueError("kickstarting_loss requires either teacher_dist or teacher_log_prob")

    # For the reverse direction the teacher is the sampling distribution.
    sample_dist = teacher_dist if direction == "reverse" else student_dist
    if user_actions_needed := (actions is None):
        try:
            actions = sample_dist.sample()
        except Exception:  # pragma: no cover - exotic distributions
            pass
    del user_actions_needed

    if use_exact_kl:
        try:
            kl = torch.distributions.kl_divergence(teacher_dist, student_dist)
            if kl.dim() > 1:
                kl = kl.sum(dim=-1)
            return _reduce(kl, reduction, weight)
        except (NotImplementedError, AttributeError, TypeError):  # pragma: no cover
            pass

    teacher_lp = teacher_dist.log_prob(actions)
    student_lp = student_dist.log_prob(actions)
    if student_lp.dim() > 1:
        student_lp = student_lp.sum(dim=-1)
        teacher_lp = teacher_lp.sum(dim=-1)
    per_state = kl_s_divergence(teacher_lp.detach(), student_lp)
    return _reduce(per_state, reduction, weight)


# Alias requested by the plan / used by analysis scripts.
ks_loss = kickstarting_loss


# ---------------------------------------------------------------------------
# The regulariser
# ---------------------------------------------------------------------------
class Kickstarting:
    """Actor-only kickstarting retention loss for RL fine-tuning.

    Args:
        actor: the (student) policy whose parameters receive the auxiliary loss.
        teacher: the pre-trained policy ``pi_*`` (used for the KL target).
            Optional if the online buffer stores teacher log-probabilities.
        buffer: an :class:`RolloutBuffer` of online-policy states (``B_theta``).
        coef: initial scale of the auxiliary loss (NetHack: ``0.5``).
        schedule: optional schedule object exposing ``value_at``/``step`` (e.g.
            the shared ``CoefficientSchedule``).  Overrides ``coef``/``decay``.
        decay: per-step multiplicative decay factor (NetHack: ``0.99998``).
            ``None`` means a constant coefficient.
        direction: KL direction; ``"reverse"`` = ``D_KL^s(pi_* || pi_theta)``
            (the paper's kickstarting loss).
        batch_size: number of online states per update.
        use_exact_kl: use analytic KL when both distributions are available.
        temperature: softmax temperature applied to discovered logits.
        log_prob_fn: optional ``fn(module, obs, actions) -> log_prob``.
        forward_fn: optional ``fn(module, obs) -> output``.
        min_coef: lower bound on the (decaying) coefficient.
        name: label used in reprs / logs.
    """

    kind = "kickstarting"

    def __init__(
        self,
        actor: Any,
        teacher: Any = None,
        buffer: Optional[RolloutBuffer] = None,
        coef: float = 1.0,
        schedule: Optional[Any] = None,
        decay: Optional[float] = None,
        decay_type: str = "exponential",
        direction: str = "reverse",
        batch_size: int = 128,
        use_exact_kl: bool = True,
        temperature: float = 1.0,
        loss_type: str = "kl",
        log_prob_fn: Optional[Callable[..., Any]] = None,
        forward_fn: Optional[Callable[..., Any]] = None,
        min_coef: float = 0.0,
        device: Optional[Any] = None,
        name: str = "ks",
    ) -> None:
        if torch is None:  # pragma: no cover
            raise RuntimeError("Kickstarting requires torch to be installed")
        if direction not in ("forward", "reverse"):
            raise ValueError("direction must be 'forward' or 'reverse'")
        self.actor = actor
        self.teacher = teacher
        self.buffer = buffer if buffer is not None else RolloutBuffer(device=device)
        self.name = name
        self.direction = direction
        self.batch_size = int(batch_size)
        self.use_exact_kl = bool(use_exact_kl)
        self.temperature = float(temperature)
        self.loss_type = str(loss_type)
        self.log_prob_fn = log_prob_fn
        self.forward_fn = forward_fn
        self.min_coef = float(min_coef)
        self.device = device
        self.schedule = _as_schedule(schedule, coef=coef, decay=decay,
                                     decay_type=decay_type, min_coef=min_coef)
        # Initial coefficient as declared (used by config-driven reporting).
        self.coef = float(getattr(self.schedule, "value", coef))
        self._schedule_backend = getattr(self.schedule, "kind", type(self.schedule).__name__)
        if teacher is not None:
            freeze_teacher(teacher, device=device)

    # -- construction helpers --------------------------------------------
    @classmethod
    def for_env(cls, env_name: str, actor: Any, teacher: Any = None,
                buffer: Optional[RolloutBuffer] = None, **kwargs: Any) -> "Kickstarting":
        """Build a Kickstarting loss with the paper's per-environment constants."""
        settings = ks_config_for(env_name)
        settings.update(kwargs)
        if buffer is not None:
            settings.setdefault("buffer", buffer)
        return cls(actor, teacher=teacher, **settings)

    def configure(self, cfg: Any) -> "Kickstarting":
        """Apply configuration keys (``coef``/``scale``/``decay``/``batch_size``)."""
        get = _cfg_getter(cfg)

        def _get(*names: str, default: Any = None) -> Any:
            for n in names:
                v = get(n, None)
                if v is not None:
                    return v
            return default

        scale = _get("coef", "scale", "ks_coef", "lambda_ks")
        decay = _get("decay", "decay_factor")
        min_coef = _get("min_coef", "coef_min")
        direction = _get("direction")
        batch_size = _get("batch_size")
        use_exact_kl = _get("use_exact_kl", "exact_kl")
        if scale is not None or decay is not None or min_coef is not None:
            value = self.coef if scale is None else float(scale)
            if min_coef is not None:
                self.min_coef = float(min_coef)
            self.schedule = PerStepDecay(
                value=value,
                decay=None if decay is None else float(decay),
                min_value=self.min_coef,
            )
            self.coef = value
            self._schedule_backend = "per_step"
        if direction is not None:
            self.direction = str(direction)
        if batch_size is not None:
            self.batch_size = int(batch_size)
        if use_exact_kl is not None:
            self.use_exact_kl = bool(use_exact_kl)
        return self

    # -- state ------------------------------------------------------------
    @property
    def enabled(self) -> bool:
        """``False`` when the (current) coefficient is zero -> loss skipped."""
        return self.coef > 0.0 and self.schedule.value_at(self.step_count) > 0.0

    @property
    def coefficient(self) -> float:
        return float(self.schedule.value_at(self.step_count))

    @property
    def step_count(self) -> int:
        return int(getattr(self.schedule, "_step", 0))

    def value_at(self, step: int) -> float:
        return float(self.schedule.value_at(step))

    def step(self, n: int = 1) -> float:
        """Advance the decay schedule (called once per train step)."""
        self.schedule.step(n)
        return self.coefficient

    def reset(self) -> None:
        self.schedule.reset()

    # -- buffers / teacher -------------------------------------------------
    def attach_buffer(self, buffer: RolloutBuffer) -> "Kickstarting":
        self.buffer = buffer
        return self

    set_buffer = attach_buffer

    def add_rollout(self, obs: Any, **kwargs: Any) -> None:
        """Feed online policy observations into ``B_theta``.

        If the teacher is available and ``log_prob_fn`` is provided, teacher
        log-probabilities are precomputed on the fly, which keeps the update
        step free of teacher forward passes.
        """
        if "teacher_log_prob" not in kwargs and self.teacher is not None and self.log_prob_fn is not None:
            actions = kwargs.get("action", kwargs.get("teacher_action"))
            if actions is not None:
                with torch.no_grad():
                    kwargs["teacher_log_prob"] = self.teacher_log_prob(obs, actions)
        self.buffer.add(obs, **kwargs)

    def set_teacher_dist_fn(self, fn: Optional[Callable[..., Any]]) -> "Kickstarting":
        """Provide ``fn(obs) -> distribution`` (or ``-> module output``) for the teacher."""
        self._teacher_dist_fn = fn
        return self

    def teacher_log_prob(self, obs: Any, actions: Any) -> Any:
        """``log pi_*(a|s)`` for the given observations/actions (no grad)."""
        if self.teacher is None:
            raise RuntimeError("no teacher policy was provided to Kickstarting")
        if self.log_prob_fn is not None:
            return self.log_prob_fn(self.teacher, obs, actions)
        dist = self._distribution(self.teacher, obs, teacher=True)
        if hasattr(dist, "log_prob"):
            log_prob = dist.log_prob(actions)
        else:  # pragma: no cover - logits without a distribution wrapper
            from torch.distributions import Categorical  # local import

            log_prob = Categorical(logits=dist / max(self.temperature, 1e-8)).log_prob(actions)
        if log_prob.dim() > 1:
            log_prob = log_prob.sum(dim=-1)
        return log_prob.detach()

    # -- loss -------------------------------------------------------------
    def _distribution(self, module: Any, obs: Any, teacher: bool = False) -> Any:
        fn = self._teacher_dist_fn if (teacher and getattr(self, "_teacher_dist_fn", None)) else None
        output = fn(obs) if fn is not None else _forward_actor(module, obs, self.forward_fn)
        dist = _find_distribution(output, obs=obs, forward_fn=None,
                                  prefer_logits=(self.temperature != 1.0))
        return _apply_temperature(dist, self.temperature)

    def student_distribution(self, obs: Any) -> Any:
        return self._distribution(self.actor, obs, teacher=False)

    def penalty(self, batch: Optional[Mapping[str, Any]] = None,
                batch_size: Optional[int] = None) -> Any:
        """Scaled ``L_KS`` for one batch of online states.

        Returns a scalar tensor carrying gradients w.r.t. the actor's
        parameters; the teacher term is detached.
        """
        if self.coef <= 0.0:
            return _zero_tensor(self.actor)

        if batch is None:
            batch = self.buffer.sample(batch_size or self.batch_size)
        obs = _get_obs(batch)
        weight = batch.get("weights")
        if weight is None:
            weight = batch.get("weight")
        reduction = "mean" if weight is None else "none"

        teacher_lp = batch.get("teacher_log_prob")
        if teacher_lp is not None:
            actions = batch.get("teacher_action", batch.get("action"))
            if self.log_prob_fn is not None:
                student_lp = self.log_prob_fn(self.actor, obs, actions)
            else:
                dist = self.student_distribution(obs)
                student_lp = dist.log_prob(actions)
            if student_lp.dim() > 1:
                student_lp = student_lp.sum(dim=-1)
            if teacher_lp.dim() > 1:
                teacher_lp = teacher_lp.sum(dim=-1)
            per_state = kl_s_divergence(teacher_lp.detach(), student_lp)
            loss = _reduce(per_state, reduction, weight)
            return loss * self.coefficient

        if self.teacher is None:
            raise RuntimeError(
                "Kickstarting requires either a teacher policy or pre-computed "
                "teacher_log_prob entries in the online buffer"
            )
        if not hasattr(self.actor, "parameters") and not hasattr(self.actor, "__call__"):
            raise RuntimeError("actor must be callable or an nn.Module")

        student_dist = self.student_distribution(obs)
        if batch.get("teacher_output") is not None:
            teacher_dist = _apply_temperature(
                _find_distribution(batch["teacher_output"], obs=obs), self.temperature
            )
        else:
            teacher_dist = self._distribution(self.teacher, obs, teacher=True)

        loss = kickstarting_loss(
            student_dist,
            teacher_dist,
            direction=self.direction,
            use_exact_kl=self.use_exact_kl,
            reduction=reduction,
            weight=weight,
            actions=batch.get("teacher_action", batch.get("action")),
        )
        return loss * self.coefficient

    # Aliases matching the naming used across the code base.
    penalty_loss = penalty
    loss = penalty
    auxiliary_loss = penalty

    def __call__(self, batch: Optional[Mapping[str, Any]] = None,
                 batch_size: Optional[int] = None) -> Any:
        return self.penalty(batch, batch_size)

    # For convenience when a runner only keeps the auxiliary objects around.
    def done_adjusting(self) -> None:  # pragma: no cover - API parity with BC
        """No-op kept for API parity: KS decay is applied every train step."""
        return None

    # -- persistence ------------------------------------------------------
    def state_dict(self) -> Dict[str, Any]:
        return {
            "coef": self.coef,
            "direction": self.direction,
            "batch_size": self.batch_size,
            "schedule": self.schedule.state_dict(),
            "backend": self._schedule_backend,
        }

    def load_state_dict(self, state: Mapping[str, Any]) -> None:
        if not state:
            return
        self.coef = float(state.get("coef", self.coef))
        self.direction = state.get("direction", self.direction)
        self.batch_size = int(state.get("batch_size", self.batch_size))
        if state.get("schedule"):
            self.schedule.load_state_dict(state["schedule"])

    def extra_repr(self) -> str:
        return (
            f"name={self.name}, coef={self.coef}, coefficient={self.coefficient:.6g}, "
            f"decay={getattr(self.schedule, 'decay', None)}, direction={self.direction}, "
            f"batch_size={self.batch_size}, buffer={len(self.buffer)}"
        )

    def __repr__(self) -> str:  # pragma: no cover - cosmetic
        return f"Kickstarting({self.extra_repr()})"


# Alias: some callers refer to the module-level class by this name.
KickstartingLoss = Kickstarting


# ---------------------------------------------------------------------------
# Per-environment constants (paper Appendix B.1 / Section 3)
# ---------------------------------------------------------------------------
# NetHack: scale 0.5 with exponential decay 0.99998 applied every train step.
# The paper only reports KS for NetHack; other environments fall back to a
# constant coefficient of 1.0 (Montezuma/RoboticSequence use BC/EWC/EM).
DEFAULT_KS_COEF: Dict[str, float] = {
    "nethack": 0.5,
    "montezuma": 1.0,
    "robotic_sequence": 1.0,
    "metaworld": 1.0,
}

DEFAULT_KS_DECAY: Dict[str, Optional[float]] = {
    "nethack": 0.99998,
    "montezuma": None,
    "robotic_sequence": None,
    "metaworld": None,
}


def _normalise_env_name(env_name: str) -> str:
    name = str(env_name or "").strip().lower().replace("-", "_").replace(" ", "_")
    if "nethack" in name or name in ("nle", "nld"):
        return "nethack"
    if "montezuma" in name:
        return "montezuma"
    if "robot" in name or "meta" in name:
        return "robotic_sequence"
    return name


def ks_coef_for(env_name: str) -> float:
    """The paper's kickstarting scale for a given environment (NetHack: 0.5)."""
    return float(DEFAULT_KS_COEF.get(_normalise_env_name(env_name), 1.0))


def ks_decay_for(env_name: str) -> Optional[float]:
    """Per-step exponential decay for kickstarting (NetHack: 0.99998)."""
    return DEFAULT_KS_DECAY.get(_normalise_env_name(env_name), None)


def ks_config_for(env_name: str) -> Dict[str, Any]:
    """Kickstarting keyword arguments for a given environment (Appendix B.1)."""
    env = _normalise_env_name(env_name)
    return {
        "coef": ks_coef_for(env),
        "decay": ks_decay_for(env),
        "decay_type": "exponential" if ks_decay_for(env) is not None else "none",
        "min_coef": 0.0,
    }


# ---------------------------------------------------------------------------
# Small utilities
# ---------------------------------------------------------------------------
def freeze_teacher(module: Any, device: Optional[Any] = None) -> Any:
    """Put the teacher in eval mode and disable its gradients."""
    if module is None:
        return module
    if hasattr(module, "eval"):
        module.eval()
    if hasattr(module, "parameters"):
        for p in module.parameters():
            p.requires_grad_(False)
    if device is not None and hasattr(module, "to"):
        try:
            module.to(device)
        except Exception:  # pragma: no cover - already on device
            pass
    return module


def _cfg_getter(cfg: Any) -> Callable[[str, Any], Any]:
    if cfg is None:
        return lambda key, default=None: default
    if hasattr(cfg, "get"):
        return lambda key, default=None: cfg.get(key, default)
    return lambda key, default=None: getattr(cfg, key, default)


def _apply_temperature(dist: Any, temperature: float) -> Any:
    """Rescale an (unwrapped) distribution or logits by ``1/T``."""
    if temperature == 1.0:
        return dist
    try:
        from torch.distributions import Categorical

        if isinstance(dist, Categorical):
            logits = dist.logits / max(temperature, 1e-8)
            return Categorical(logits=logits)
    except Exception:  # pragma: no cover
        return dist
    return dist


def _get_obs(batch: Mapping[str, Any]) -> Any:
    for key in ("obs", "observations", "states", "state"):
        if isinstance(batch, Mapping) and batch.get(key) is not None:
            return batch[key]
    raise KeyError("batch does not contain observations under 'obs'/'states'")


def _reduce(per_sample: Any, reduction: str, weight: Any = None) -> Any:
    if reduction == "none":
        return per_sample
    if weight is not None:
        if isinstance(weight, (int, float)):
            norm = weight if reduction == "mean" else 1.0
            return (per_sample * float(weight)).sum() / max(float(norm), 1e-8)
        weight = weight.to(per_sample.device).float().reshape(-1)
        if weight.shape[0] != per_sample.shape[0]:  # pragma: no cover - broadcast
            weight = weight.expand_as(per_sample)
        weighted = per_sample.reshape(-1) * weight
        denom = weight.sum().clamp_min(1e-8)
        return weighted.sum() / denom
    if reduction == "sum":
        return per_sample.sum()
    return per_sample.mean()


def _to_tensor(value: Any) -> Any:
    if value is None or torch is None:
        return value
    if isinstance(value, torch.Tensor):
        return value.detach()
    try:
        return torch.as_tensor(value)
    except Exception:  # pragma: no cover - non-numeric payloads
        return value


def _concat(store: Sequence[Any]) -> Any:
    items = [x for x in store if x is not None]
    if not items:
        return torch.zeros(0) if torch is not None else None
    if len(items) == 1:
        return items[0]
    try:
        return torch.cat([x.reshape(-1, *x.shape[1:]) for x in items], dim=0)
    except Exception:  # pragma: no cover - mismatched shapes
        return items


def _lead_dim(value: Any) -> int:
    if torch is not None and isinstance(value, torch.Tensor):
        return int(value.shape[0]) if value.dim() > 0 else 1
    shape = getattr(value, "shape", None)
    if shape:
        return int(shape[0])
    try:
        return len(value)  # type: ignore[arg-type]
    except TypeError:  # pragma: no cover
        return 1


def _zeros_like(value: Any) -> Any:
    if torch is not None and isinstance(value, torch.Tensor):
        return torch.zeros(_lead_dim(value), dtype=torch.bool)
    return torch.zeros(_lead_dim(value))  # pragma: no cover


def _constant_like(value: Any, constant: float) -> Any:
    n = _lead_dim(value)
    if torch is None:  # pragma: no cover
        return [constant] * n
    dtype = torch.float32
    return torch.full((n,), float(constant), dtype=dtype)


def _move(value: Any, device: Optional[Any]) -> Any:
    if device is None or torch is None or not isinstance(value, torch.Tensor):
        return value
    return value.to(device)


def _zero_tensor(actor: Any) -> Any:
    """A differentiable-by-construction zero scalar (keeps ``.backward()`` valid)."""
    if torch is None:  # pragma: no cover
        return 0.0
    params = list(actor.parameters()) if hasattr(actor, "parameters") else []
    if params:
        return params[0].sum() * 0.0
    return torch.zeros((), requires_grad=True)


__all__ = [
    "Kickstarting",
    "KickstartingLoss",
    "RolloutBuffer",
    "OnlineBuffer",
    "PerStepDecay",
    "kickstarting_loss",
    "ks_loss",
    "ks_coef_for",
    "ks_decay_for",
    "ks_config_for",
    "freeze_teacher",
    "DEFAULT_KS_COEF",
    "DEFAULT_KS_DECAY",
]
