"""Goal-Conditioned IQL (GC-IQL) baseline for FRE zero-shot offline RL.

Reference
---------
Kostrikov et al. (2021), *Offline Reinforcement Learning with Implicit
Q-Learning*, in its goal-conditioned form.  The paper's addendum specifies the
variant used by the FRE benchmark:

    GC-IQL is just IQL with the additional goal state.

    Specifically, given a random state, a random goal state is sampled from
    1) future states in the trajectory using a geometric distribution,
    2) a random goal in the dataset, or
    3) the current state is the goal, in which case the reward is 0 and the
    mask/terminal flag is True.  In other cases, reward is -1.
    The ratio is p_randomgoal=0.3, p_geometric_goal=0.5, p_current_goal=0.2.

    To give the information to the neural network, goals and observations are
    concatenated.

    No environment rewards are used to train GC-IQL.  The reward passed to IQL
    are the goal-conditioned rewards generated by the preprocessor as described
    above, which is 0 if the state==goal and -1 otherwise.

    Evaluation: the goal-conditioned agent is given the ground-truth goal that
    the specific evaluation task contains, to condition on.

And Section 5.2:

    All methods are evaluated using a mean over twenty evaluation episodes, and
    each agent is trained using five random seeds [...].  FRE, GC-IQL, and
    GC-BC are implemented within the same codebase and with the same network
    structure.

Implementation notes (nothing in the paper fixes these, so sensible defaults):
  * Q(s,g,a), V(s,g) and pi(a|s,g) are `[512, 512, 512]` ReLU MLPs taking the
    concatenation ``[observation, goal]`` as input (no LayerNorm for GC-IQL).
  * Expectile 0.8, AWR temperature 3.0, discount 0.88, Polyak rate 0.001 and
    Adam lr 1e-4 (identical to the FRE agent's IQL hyperparameters).
  * The Bellman target uses the paper's `max_a' Q_target(s',g,a')` form, i.e.
    the classic IQL (non-pessimistic) target.
  * Geometric future-goal sampling uses ``p = 0.5`` over future offsets within
    the same trajectory.
"""

from __future__ import annotations

import argparse
import copy
import inspect
import json
import math
import os
import time
from dataclasses import dataclass, field, replace
from typing import Any, Callable, Dict, List, Mapping, Optional, Sequence, Tuple, Union

import numpy as np

try:  # pragma: no cover - torch is a hard requirement at runtime
    import torch
    import torch.nn as nn
    import torch.nn.functional as F

    _HAS_TORCH = True
except Exception:  # pragma: no cover
    torch = None  # type: ignore
    nn = object  # type: ignore
    F = None  # type: ignore
    _HAS_TORCH = False

from fre.models.rl_networks import (  # noqa: E402
    DEFAULT_RL_HIDDEN_DIMS,
    build_gc_mlp,
    get_activation,
)
from fre.models.iql import (  # noqa: E402
    DEFAULT_AWR_TEMPERATURE,
    DEFAULT_EXPECTILE,
    DEFAULT_TARGET_UPDATE_RATE,
    awr_loss,
    expectile_loss,
    polyak_update,
)

__all__ = [
    "GCIQLConfig",
    "GCIQLAgent",
    "GoalConditionedAgent",
    "GoalConditionedPolicy",
    "GoalSampler",
    "goal_conditioned_reward",
    "sample_hindsight_goals",
    "sample_goal_indices",
    "build_gc_iql",
    "train_gc_iql",
    "gc_iql_action_fn",
    "evaluate_gc_agent",
    "evaluate_gc_iql",
    "main",
    "DEFAULT_P_CURRENT_GOAL",
    "DEFAULT_P_FUTURE_GOAL",
    "DEFAULT_P_RANDOM_GOAL",
    "DEFAULT_GEOMETRIC_P",
    "DEFAULT_GC_HIDDEN_DIMS",
]


# ---------------------------------------------------------------------------
# Hyperparameter defaults (paper: identical network/optimizer to the FRE agent)
# ---------------------------------------------------------------------------

#: HER-style goal sampling mixing probabilities (addendum "Additional Details on GC-IQL").
DEFAULT_P_CURRENT_GOAL = 0.2
DEFAULT_P_FUTURE_GOAL = 0.5
DEFAULT_P_RANDOM_GOAL = 0.3

#: Geometric distribution parameter for sampling *future* goals in a trajectory.
DEFAULT_GEOMETRIC_P = 0.5

DEFAULT_GC_HIDDEN_DIMS: Tuple[int, int, int] = (512, 512, 512)
DEFAULT_GC_LEARNING_RATE = 1e-4
DEFAULT_GC_DISCOUNT = 0.88
DEFAULT_GC_BATCH_SIZE = 512
DEFAULT_GC_TRAIN_STEPS = 1_000_000
DEFAULT_GC_EXP_ADV_CLAMP = 100.0
DEFAULT_GC_LOG_STD_MIN = -10.0
DEFAULT_GC_LOG_STD_MAX = 2.0

#: Reward for an unachieved / achieved goal (addendum: "-1 otherwise", "0 if state==goal").
DEFAULT_REWARD_UNACHIEVED = -1.0
DEFAULT_REWARD_REACHED = 0.0


# ---------------------------------------------------------------------------
# Goal-conditioned rewards
# ---------------------------------------------------------------------------


def _to_numpy(x: Any) -> np.ndarray:
    if isinstance(x, np.ndarray):
        return x
    if _HAS_TORCH and torch is not None and isinstance(x, torch.Tensor):
        return x.detach().cpu().numpy()
    return np.asarray(x)


def goal_conditioned_reward(
    states: Any,
    goals: Any,
    threshold: Optional[float] = None,
    distance_dims: Optional[Sequence[int]] = None,
    state_std: Optional[np.ndarray] = None,
    reward_unachieved: float = DEFAULT_REWARD_UNACHIEVED,
    reward_reached: float = DEFAULT_REWARD_REACHED,
) -> np.ndarray:
    """Binary goal-conditioned reward: ``reward_reached`` at the goal else ``reward_unachieved``.

    ``threshold=None`` reproduces the addendum exactly (``reward is 0 if the
    state==goal and -1 otherwise``, i.e. exact equality).  A numeric threshold
    switches to a Euclidean radius test (used when goals are not drawn from the
    dataset itself, e.g. for evaluation).
    """
    states = np.asarray(_to_numpy(states), dtype=np.float64)
    goals = np.asarray(_to_numpy(goals), dtype=np.float64)
    if states.ndim == 1:
        states = states[None, :]
    if goals.ndim == 1:
        goals = goals[None, :]
    if distance_dims is not None:
        dims = np.asarray(list(distance_dims), dtype=np.int64)
        states = states[..., dims]
        goals = goals[..., dims]
    if state_std is not None:
        std = np.asarray(state_std, dtype=np.float64).reshape(1, -1)
        if std.shape[-1] != states.shape[-1]:
            std = std[:, : states.shape[-1]]
        states = states / np.maximum(std, 1e-8)
        goals = goals / np.maximum(std, 1e-8)

    if threshold is None:
        diff = np.abs(states - goals)
        reached = np.all(diff <= 1e-8, axis=-1)
    else:
        dist = np.linalg.norm(states - goals, axis=-1)
        reached = dist < float(threshold)

    return np.where(reached, float(reward_reached), float(reward_unachieved)).astype(np.float32)


# ---------------------------------------------------------------------------
# HER goal sampling (geometric future / random / current)
# ---------------------------------------------------------------------------


def _trajectory_bounds(dataset: Any, indices: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Return ``(traj_start, traj_end)`` for each index (inclusive endpoints)."""
    n = len(indices)
    starts = getattr(dataset, "traj_starts", None)
    ends = getattr(dataset, "traj_ends", None)
    traj_ids = getattr(dataset, "trajectory_ids", None)

    if starts is not None and ends is not None and traj_ids is not None:
        starts = np.asarray(starts, dtype=np.int64)
        ends = np.asarray(ends, dtype=np.int64)
        traj_ids = np.asarray(traj_ids, dtype=np.int64)
        # trajectory_ids maps transition -> trajectory slot
        slots = traj_ids[indices]
        if starts.shape[0] == int(traj_ids.max()) + 1:
            return starts[slots].astype(np.int64), ends[slots].astype(np.int64)
        # traj_ids may directly be the start index of the transition's trajectory
        base = traj_ids[indices].astype(np.int64)
        length = getattr(dataset, "max_trajectory_length", None)
        if length is None:
            length = getattr(dataset, "episode_length", None)
        if length is None:
            # fall back to the whole dataset as a single trajectory chunk
            length = max(1, int(len(dataset)) // max(1, len(np.unique(base))))
        return base, np.minimum(base + int(length) - 1, len(dataset) - 1)

    # Fallback: treat the dataset as one long trajectory.
    return np.zeros(n, dtype=np.int64), np.full(n, len(dataset) - 1, dtype=np.int64)


def sample_goal_indices(
    dataset_or_num_states: Any,
    indices: np.ndarray,
    rng: np.random.Generator,
    p_current: float = DEFAULT_P_CURRENT_GOAL,
    p_future: float = DEFAULT_P_FUTURE_GOAL,
    p_random: float = DEFAULT_P_RANDOM_GOAL,
    geometric_p: float = DEFAULT_GEOMETRIC_P,
    min_offset: int = 1,
) -> np.ndarray:
    """Sample goal indices for a batch of state indices.

    Mixing distribution (addendum): ``p_current=0.2`` (goal is the current
    state), ``p_future=0.5`` (a future state in the same trajectory drawn from a
    geometric distribution), ``p_random=0.3`` (a random dataset state).
    """
    dataset = dataset_or_num_states
    indices = np.asarray(indices, dtype=np.int64).reshape(-1)
    n = indices.shape[0]
    if n == 0:
        return indices.copy()

    num_states = int(len(dataset)) if hasattr(dataset, "__len__") else int(dataset)

    probs = np.asarray([p_current, p_future, p_random], dtype=np.float64)
    probs = probs / max(probs.sum(), 1e-8)
    mode = rng.choice(3, size=n, p=probs)

    goals = indices.copy()

    # --- future goals (geometric offset inside the same trajectory) ---------
    fut = np.flatnonzero(mode == 1)
    if fut.size:
        starts, ends = _trajectory_bounds(dataset, indices)
        offsets = rng.geometric(p=geometric_p, size=fut.size).astype(np.int64)
        offsets = np.maximum(offsets, min_offset)
        candidate = indices[fut] + offsets
        # keep the goal inside the same trajectory
        candidate = np.minimum(candidate, ends[fut])
        goal_idx = np.maximum(candidate, starts[fut])
        goals[fut] = goal_idx

    # --- random goals -------------------------------------------------------
    rnd = np.flatnonzero(mode == 2)
    if rnd.size:
        goals[rnd] = rng.integers(0, max(num_states, 1), size=rnd.size)

    # --- current goals ------------------------------------------------------
    cur = np.flatnonzero(mode == 0)
    if cur.size:
        goals[cur] = indices[cur]

    goals = np.clip(goals, 0, max(num_states - 1, 0))
    return goals


def sample_hindsight_goals(
    dataset: Any,
    indices: np.ndarray,
    rng: np.random.Generator,
    p_current: float = DEFAULT_P_CURRENT_GOAL,
    p_future: float = DEFAULT_P_FUTURE_GOAL,
    p_random: float = DEFAULT_P_RANDOM_GOAL,
    geometric_p: float = DEFAULT_GEOMETRIC_P,
    min_offset: int = 1,
) -> np.ndarray:
    """Goals (states) sampled with the GC-IQL HER distribution."""
    goal_idx = sample_goal_indices(
        dataset,
        indices,
        rng,
        p_current=p_current,
        p_future=p_future,
        p_random=p_random,
        geometric_p=geometric_p,
        min_offset=min_offset,
    )
    states = np.asarray(dataset.observations, dtype=np.float32)
    return states[goal_idx]


class GoalSampler:
    """Stateless helper bundling the GC-IQL HER goal distribution."""

    def __init__(
        self,
        p_current: float = DEFAULT_P_CURRENT_GOAL,
        p_future: float = DEFAULT_P_FUTURE_GOAL,
        p_random: float = DEFAULT_P_RANDOM_GOAL,
        geometric_p: float = DEFAULT_GEOMETRIC_P,
        min_offset: int = 1,
        seed: int = 0,
    ) -> None:
        self.p_current = float(p_current)
        self.p_future = float(p_future)
        self.p_random = float(p_random)
        self.geometric_p = float(geometric_p)
        self.min_offset = int(min_offset)
        self.rng = np.random.default_rng(seed)

    def __call__(self, dataset: Any, indices: np.ndarray) -> np.ndarray:
        return sample_hindsight_goals(
            dataset,
            indices,
            self.rng,
            p_current=self.p_current,
            p_future=self.p_future,
            p_random=self.p_random,
            geometric_p=self.geometric_p,
            min_offset=self.min_offset,
        )


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------


@dataclass
class GCIQLConfig:
    """Configuration for the GC-IQL baseline (network + IQL hyperparameters)."""

    domain: str = "antmaze"
    state_dim: Optional[int] = None
    action_dim: Optional[int] = None
    goal_dim: Optional[int] = None

    hidden_dims: Tuple[int, int, int] = DEFAULT_GC_HIDDEN_DIMS
    activation: str = "relu"
    use_layer_norm: bool = False

    expectile: float = DEFAULT_EXPECTILE
    awr_temperature: float = DEFAULT_AWR_TEMPERATURE
    discount: float = DEFAULT_GC_DISCOUNT
    target_update_rate: float = DEFAULT_TARGET_UPDATE_RATE
    learning_rate: float = DEFAULT_GC_LEARNING_RATE
    exp_adv_clamp: float = DEFAULT_GC_EXP_ADV_CLAMP
    log_std_min: float = DEFAULT_GC_LOG_STD_MIN
    log_std_max: float = DEFAULT_GC_LOG_STD_MAX
    update_policy: bool = True

    action_low: Union[float, Sequence[float]] = -1.0
    action_high: Union[float, Sequence[float]] = 1.0

    batch_size: int = DEFAULT_GC_BATCH_SIZE
    steps: int = DEFAULT_GC_TRAIN_STEPS
    seed: int = 0
    device: str = "cpu"

    # HER goal distribution
    p_current: float = DEFAULT_P_CURRENT_GOAL
    p_future: float = DEFAULT_P_FUTURE_GOAL
    p_random: float = DEFAULT_P_RANDOM_GOAL
    geometric_p: float = DEFAULT_GEOMETRIC_P
    min_offset: int = 1

    # Relabelling conventions
    relabel_target: str = "next"  # "next" (r from s') or "state" (r from s)
    goal_threshold: Optional[float] = None  # None => exact equality (addendum)
    goal_distance_dims: Optional[Sequence[int]] = None
    state_std: Optional[Sequence[float]] = None
    discretize_antmaze: bool = True

    def replace(self, **overrides: Any) -> "GCIQLConfig":
        return replace(self, **overrides)

    def to_dict(self) -> Dict[str, Any]:
        out = dict(self.__dict__)
        out["state_std"] = None if self.state_std is None else np.asarray(self.state_std).tolist()
        return out


# ---------------------------------------------------------------------------
# Goal-conditioned network
# ---------------------------------------------------------------------------


class GoalConditionedPolicy(nn.Module):
    """Tanh-squashed Gaussian policy ``pi(a | s, g)`` with an MLP trunk."""

    def __init__(
        self,
        input_dim: int,
        action_dim: int,
        hidden_dims: Sequence[int] = DEFAULT_GC_HIDDEN_DIMS,
        activation: str = "relu",
        use_layer_norm: bool = False,
        action_low: Union[float, Sequence[float]] = -1.0,
        action_high: Union[float, Sequence[float]] = 1.0,
        log_std_min: float = DEFAULT_GC_LOG_STD_MIN,
        log_std_max: float = DEFAULT_GC_LOG_STD_MAX,
        init_gain: Optional[float] = None,
    ) -> None:
        super().__init__()
        if not _HAS_TORCH:
            raise RuntimeError("torch is required for GoalConditionedPolicy")
        self.input_dim = int(input_dim)
        self.action_dim = int(action_dim)
        self.log_std_min = float(log_std_min)
        self.log_std_max = float(log_std_max)

        gain = math.sqrt(2.0) if init_gain is None else float(init_gain)
        self.net = build_gc_mlp(
            self.input_dim,
            hidden_dims=tuple(hidden_dims),
            output_dim=2 * self.action_dim,
            activation=activation,
            output_activation=None,
            use_layer_norm=use_layer_norm,
            init_gain=gain,
        )

        low = np.broadcast_to(np.asarray(action_low, dtype=np.float32), (self.action_dim,)).copy()
        high = np.broadcast_to(np.asarray(action_high, dtype=np.float32), (self.action_dim,)).copy()
        self.register_buffer("action_scale", torch.as_tensor((high - low) / 2.0, dtype=torch.float32))
        self.register_buffer("action_bias", torch.as_tensor((high + low) / 2.0, dtype=torch.float32))

    # -- distribution -------------------------------------------------------
    def distribution(self, x: "torch.Tensor") -> "torch.distributions.Normal":
        out = self.net(x)
        mean, log_std = torch.split(out, self.action_dim, dim=-1)
        log_std = torch.clamp(log_std, self.log_std_min, self.log_std_max)
        return torch.distributions.Normal(mean, log_std.exp())

    def forward(self, x: "torch.Tensor") -> "torch.distributions.Normal":
        return self.distribution(x)

    def log_prob(self, x: "torch.Tensor", actions: "torch.Tensor") -> "torch.Tensor":
        dist = self.distribution(x)
        y = torch.clamp(actions, -1.0 + 1e-6, 1.0 - 1e-6)
        pre = torch.atanh(y)
        log_prob = dist.log_prob(pre)
        # tanh change-of-variables correction
        log_prob = log_prob - torch.log(1.0 - actions.pow(2) + 1e-6)
        return log_prob.sum(dim=-1)

    def sample(self, x: "torch.Tensor", deterministic: bool = False) -> "torch.Tensor":
        dist = self.distribution(x)
        raw = dist.mean if deterministic else dist.rsample()
        return torch.tanh(raw) * self.action_scale + self.action_bias


class GCIQLAgent(nn.Module):
    """Goal-conditioned IQL agent: ``Q(s,g,a)``, ``V(s,g)``, ``pi(a|s,g)``.

    Goals and observations are concatenated (addendum).  Rewards are *not* taken
    from the environment: they are generated by the goal-conditioned
    preprocessor (0 at the goal, -1 otherwise).
    """

    def __init__(
        self,
        state_dim: int,
        action_dim: int,
        goal_dim: Optional[int] = None,
        hidden_dims: Sequence[int] = DEFAULT_GC_HIDDEN_DIMS,
        expectile: float = DEFAULT_EXPECTILE,
        awr_temperature: float = DEFAULT_AWR_TEMPERATURE,
        discount: float = DEFAULT_GC_DISCOUNT,
        target_update_rate: float = DEFAULT_TARGET_UPDATE_RATE,
        learning_rate: float = DEFAULT_GC_LEARNING_RATE,
        activation: str = "relu",
        use_layer_norm: bool = False,
        action_low: Union[float, Sequence[float]] = -1.0,
        action_high: Union[float, Sequence[float]] = 1.0,
        log_std_min: float = DEFAULT_GC_LOG_STD_MIN,
        log_std_max: float = DEFAULT_GC_LOG_STD_MAX,
        exp_adv_clamp: float = DEFAULT_GC_EXP_ADV_CLAMP,
        update_policy: bool = True,
        tau: Optional[float] = None,
        device: Optional[Union[str, "torch.device"]] = None,
        name: str = "gc-iql",
    ) -> None:
        super().__init__()
        if not _HAS_TORCH:
            raise RuntimeError("torch is required for GCIQLAgent")

        self.name = name
        self.state_dim = int(state_dim)
        self.action_dim = int(action_dim)
        self.goal_dim = int(goal_dim if goal_dim is not None else state_dim)
        self.goal_input_dim = self.state_dim + self.goal_dim

        self.hidden_dims = tuple(hidden_dims)
        self.expectile = float(expectile)
        self.awr_temperature = float(awr_temperature)
        self.discount = float(discount)
        self.target_update_rate = float(tau if tau is not None else target_update_rate)
        self.exp_adv_clamp = float(exp_adv_clamp)
        self.update_policy = bool(update_policy)
        self.activation = activation
        self.use_layer_norm = use_layer_norm
        self.log_std_min = float(log_std_min)
        self.log_std_max = float(log_std_max)
        gain = math.sqrt(2.0)

        self.q1 = build_gc_mlp(
            self.goal_input_dim + self.action_dim,
            hidden_dims=self.hidden_dims,
            output_dim=1,
            activation=activation,
            use_layer_norm=use_layer_norm,
            init_gain=gain,
        )
        self.q2 = build_gc_mlp(
            self.goal_input_dim + self.action_dim,
            hidden_dims=self.hidden_dims,
            output_dim=1,
            activation=activation,
            use_layer_norm=use_layer_norm,
            init_gain=gain,
        )
        self.q1_target = copy.deepcopy(self.q1)
        self.q2_target = copy.deepcopy(self.q2)
        self.q1_target.requires_grad_(False)
        self.q2_target.requires_grad_(False)

        self.v = build_gc_mlp(
            self.goal_input_dim,
            hidden_dims=self.hidden_dims,
            output_dim=1,
            activation=activation,
            use_layer_norm=use_layer_norm,
            init_gain=gain,
        )
        self.policy = GoalConditionedPolicy(
            self.goal_input_dim,
            self.action_dim,
            hidden_dims=self.hidden_dims,
            activation=activation,
            use_layer_norm=use_layer_norm,
            action_low=action_low,
            action_high=action_high,
            log_std_min=log_std_min,
            log_std_max=log_std_max,
            init_gain=gain,
        )

        self.learning_rate = float(learning_rate)
        self.q_optimizer = torch.optim.Adam(
            list(self.q1.parameters()) + list(self.q2.parameters()), lr=self.learning_rate
        )
        self.v_optimizer = torch.optim.Adam(self.v.parameters(), lr=self.learning_rate)
        self.policy_optimizer = torch.optim.Adam(self.policy.parameters(), lr=self.learning_rate)
        self.train_steps = 0

        if device is not None:
            self.to(device)

    # -- helpers ------------------------------------------------------------
    @staticmethod
    def compose(states: "torch.Tensor", goals: "torch.Tensor") -> "torch.Tensor":
        """Concatenate observation and goal (addendum: "goals and observations are concatenated")."""
        states = torch.as_tensor(states, dtype=torch.float32)
        goals = torch.as_tensor(goals, dtype=torch.float32)
        if states.ndim == 1:
            states = states.unsqueeze(0)
        if goals.ndim == 1:
            goals = goals.unsqueeze(0)
        if goals.shape[0] != states.shape[0]:
            if goals.shape[0] == 1:
                goals = goals.expand(states.shape[0], -1)
            else:
                raise ValueError(f"goal batch {tuple(goals.shape)} incompatible with states {tuple(states.shape)}")
        return torch.cat([states, goals], dim=-1)

    def _as_tensor(self, x: Any) -> "torch.Tensor":
        if isinstance(x, torch.Tensor):
            return x.to(next(self.parameters()).device).float()
        return torch.as_tensor(np.asarray(x), dtype=torch.float32, device=next(self.parameters()).device)

    # -- losses -------------------------------------------------------------
    def q_loss_fn(
        self,
        states: "torch.Tensor",
        actions: "torch.Tensor",
        rewards: "torch.Tensor",
        next_states: "torch.Tensor",
        goals: "torch.Tensor",
        next_goals: Optional["torch.Tensor"] = None,
        dones: Optional["torch.Tensor"] = None,
    ) -> Tuple["torch.Tensor", Dict[str, float]]:
        if next_goals is None:
            next_goals = goals
        if dones is None:
            dones = torch.zeros_like(rewards)
        x = self.compose(states, goals)
        xn = self.compose(next_states, next_goals)

        with torch.no_grad():
            # paper's Bellman target: eta(s) + gamma * E[max_a' Q_target(s', a', z)]
            a_next = self.policy.sample(xn, deterministic=False)
            q_next = torch.minimum(self.q1_target(xn, a_next), self.q2_target(xn, a_next))
            target_q = rewards + self.discount * (1.0 - dones) * q_next

        q1 = self.q1(x, actions)
        q2 = self.q2(x, actions)
        loss = F.mse_loss(q1, target_q) + F.mse_loss(q2, target_q)
        metrics = {
            "q_loss": float(loss.detach().cpu()),
            "q_mean": float(((q1 + q2) / 2.0).mean().detach().cpu()),
            "target_q_mean": float(target_q.mean().detach().cpu()),
            "reward_mean": float(rewards.mean().detach().cpu()),
        }
        return loss, metrics

    def value_loss_fn(self, states: "torch.Tensor", goals: "torch.Tensor", actions: "torch.Tensor") -> Tuple["torch.Tensor", Dict[str, float]]:
        x = self.compose(states, goals)
        with torch.no_grad():
            q = torch.minimum(self.q1(x, actions), self.q2(x, actions))
        v = self.v(x)
        loss = expectile_loss(q - v, expectile=self.expectile)
        metrics = {"v_loss": float(loss.detach().cpu()), "v_mean": float(v.mean().detach().cpu())}
        return loss, metrics

    def policy_loss_fn(self, states: "torch.Tensor", goals: "torch.Tensor", actions: "torch.Tensor") -> Tuple["torch.Tensor", Dict[str, float]]:
        x = self.compose(states, goals)
        with torch.no_grad():
            q = torch.minimum(self.q1(x, actions), self.q2(x, actions))
            v = self.v(x)
            adv = q - v
        log_probs = self.policy.log_prob(x, actions)
        loss = awr_loss(log_probs, adv, temperature=self.awr_temperature, clamp=self.exp_adv_clamp)
        metrics = {
            "policy_loss": float(loss.detach().cpu()),
            "log_prob_mean": float(log_probs.mean().detach().cpu()),
            "advantage_mean": float(adv.mean().detach().cpu()),
        }
        return loss, metrics

    # -- update -------------------------------------------------------------
    def update(self, batch: Mapping[str, Any]) -> Dict[str, float]:
        """One GC-IQL update: Q -> V -> pi -> Polyak."""
        states = self._as_tensor(batch["observations"])
        actions = self._as_tensor(batch["actions"])
        rewards = self._as_tensor(batch["rewards"]).reshape(-1, 1)
        next_states = self._as_tensor(batch.get("next_observations", batch["observations"]))
        goals = self._as_tensor(batch["goals"])
        next_goals = self._as_tensor(batch["next_goals"]) if "next_goals" in batch and batch["next_goals"] is not None else None
        dones = self._as_tensor(batch["dones"]).reshape(-1, 1) if batch.get("dones") is not None else None

        q_loss, metrics = self.q_loss_fn(states, actions, rewards, next_states, goals, next_goals, dones)
        self.q_optimizer.zero_grad(set_to_none=True)
        q_loss.backward()
        self.q_optimizer.step()

        v_loss, v_metrics = self.value_loss_fn(states, goals, actions)
        self.v_optimizer.zero_grad(set_to_none=True)
        v_loss.backward()
        self.v_optimizer.step()

        metrics.update(v_metrics)

        if self.update_policy:
            pi_loss, pi_metrics = self.policy_loss_fn(states, goals, actions)
            self.policy_optimizer.zero_grad(set_to_none=True)
            pi_loss.backward()
            self.policy_optimizer.step()
            metrics.update(pi_metrics)

        polyak_update(self.q1_target, self.q1, self.target_update_rate)
        polyak_update(self.q2_target, self.q2, self.target_update_rate)
        self.train_steps += 1
        metrics["train_steps"] = float(self.train_steps)
        return metrics

    update_from_batch = update
    train_step = update

    # -- acting -------------------------------------------------------------
    @torch.no_grad()
    def select_action(
        self,
        states: Any,
        goals: Any = None,
        deterministic: bool = False,
    ) -> np.ndarray:
        """Act with the goal-conditioned policy (evaluation: the task's ground-truth goal)."""
        states_t = self._as_tensor(states)
        if states_t.ndim == 1:
            states_t = states_t.unsqueeze(0)
        if goals is None:
            goals_t = torch.zeros(states_t.shape[0], self.goal_dim, device=states_t.device)
        else:
            goals_t = self._as_tensor(goals)
            if goals_t.ndim == 1:
                goals_t = goals_t.unsqueeze(0)
            if goals_t.shape[0] == 1 and states_t.shape[0] > 1:
                goals_t = goals_t.expand(states_t.shape[0], -1)
        x = self.compose(states_t, goals_t)
        actions = self.policy.sample(x, deterministic=deterministic)
        return actions.detach().cpu().numpy()

    def act(self, states: Any, goals: Any = None, deterministic: bool = False) -> np.ndarray:
        return self.select_action(states, goals, deterministic=deterministic)

    def __call__(self, states: Any, goals: Any = None) -> np.ndarray:  # pragma: no cover - convenience
        return self.select_action(states, goals, deterministic=True)

    def select_actions(self, states: Any, goals: Any = None, deterministic: bool = False) -> np.ndarray:
        return self.select_action(states, goals, deterministic=deterministic)

    # -- misc ---------------------------------------------------------------
    def hparams(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "state_dim": self.state_dim,
            "action_dim": self.action_dim,
            "goal_dim": self.goal_dim,
            "hidden_dims": list(self.hidden_dims),
            "expectile": self.expectile,
            "awr_temperature": self.awr_temperature,
            "discount": self.discount,
            "target_update_rate": self.target_update_rate,
            "learning_rate": self.learning_rate,
            "activation": self.activation,
            "use_layer_norm": self.use_layer_norm,
        }

    def to(self, device: Any) -> "GCIQLAgent":  # type: ignore[override]
        super().to(device)
        self.q1_target.requires_grad_(False)
        self.q2_target.requires_grad_(False)
        return self

    def extra_repr(self) -> str:  # pragma: no cover - cosmetic
        return (
            f"state_dim={self.state_dim}, goal_dim={self.goal_dim}, action_dim={self.action_dim}, "
            f"hidden_dims={self.hidden_dims}"
        )


# Backwards/forwards compatible alias used across the baseline suite.
GoalConditionedAgent = GCIQLAgent


def build_gc_iql(
    state_dim: int,
    action_dim: int,
    goal_dim: Optional[int] = None,
    device: Optional[Any] = None,
    **kwargs: Any,
) -> GCIQLAgent:
    """Factory mirroring :class:`GCIQLAgent` with tolerant kwargs."""
    accepted = _filter_kwargs(GCIQLAgent.__init__, kwargs)
    agent = GCIQLAgent(state_dim=state_dim, action_dim=action_dim, goal_dim=goal_dim, **accepted)
    if device is not None:
        agent.to(device)
    return agent


def _filter_kwargs(fn: Callable[..., Any], kwargs: Mapping[str, Any]) -> Dict[str, Any]:
    """Keep only kwargs accepted by ``fn`` (tolerant interface matching)."""
    try:
        params = inspect.signature(fn).parameters
    except (TypeError, ValueError):  # pragma: no cover
        return dict(kwargs)
    if "kwargs" in params or "kwargs" in [p.name for p in params.values() if p.kind == p.VAR_KEYWORD]:
        return dict(kwargs)
    allowed = set(params)
    return {k: v for k, v in kwargs.items() if k in allowed}


# ---------------------------------------------------------------------------
# Data pipeline (transition + relabelled-goal batches)
# ---------------------------------------------------------------------------


def _dataset_array(dataset: Any, *names: str) -> Optional[np.ndarray]:
    for name in names:
        value = getattr(dataset, name, None)
        if value is None:
            continue
        if callable(value):
            try:
                value = value()
            except TypeError:
                continue
        return np.asarray(value, dtype=np.float32)
    return None


def _next_state_indices(dataset: Any, indices: np.ndarray) -> np.ndarray:
    """Next-state indices respecting trajectory boundaries."""
    n_states = len(dataset)
    next_idx = np.minimum(np.asarray(indices, dtype=np.int64) + 1, n_states - 1)
    traj_ids = getattr(dataset, "trajectory_ids", None)
    if traj_ids is not None:
        traj_ids = np.asarray(traj_ids, dtype=np.int64)
        last_of_traj = np.arange(1, n_states)[traj_ids[1:] != traj_ids[:-1]] if n_states > 0 else np.array([], dtype=np.int64)
        if last_of_traj.size:
            bad = np.isin(next_idx, last_of_traj)
            next_idx[bad] = indices[bad]
    return next_idx


def sample_gc_batch(
    dataset: Any,
    batch_size: int,
    rng: np.random.Generator,
    config: Optional[GCIQLConfig] = None,
    goal_sampler: Optional[GoalSampler] = None,
) -> Dict[str, np.ndarray]:
    """Sample a GC-IQL training batch with hindsight-relabelled goals and rewards."""
    config = config or GCIQLConfig()
    obs = _dataset_array(dataset, "observations", "states")
    if obs is None:  # pragma: no cover - defensive
        raise ValueError("dataset does not expose observations/states")
    actions = _dataset_array(dataset, "actions")
    n = len(dataset)

    # --- sample transition indices ----------------------------------------
    indices = None
    for candidate in ("sample_indices", "sample"):
        fn = getattr(dataset, candidate, None)
        if callable(fn):
            try:
                indices = np.asarray(fn(batch_size), dtype=np.int64).reshape(-1)
                break
            except TypeError:
                try:
                    indices = np.asarray(fn(batch_size, rng=rng), dtype=np.int64).reshape(-1)
                    break
                except Exception:  # pragma: no cover
                    continue
            except Exception:  # pragma: no cover
                continue
    if indices is None or indices.size == 0:
        indices = rng.integers(0, max(n, 1), size=batch_size)

    next_idx = _next_state_indices(dataset, indices)

    # --- sample goals (HER mixture) ---------------------------------------
    sampler = goal_sampler or GoalSampler(
        p_current=config.p_current,
        p_future=config.p_future,
        p_random=config.p_random,
        geometric_p=config.geometric_p,
        min_offset=config.min_offset,
        seed=config.seed,
    )
    goal_idx = sample_goal_indices(
        dataset,
        indices,
        sampler.rng,
        p_current=config.p_current,
        p_future=config.p_future,
        p_random=config.p_random,
        geometric_p=config.geometric_p,
        min_offset=config.min_offset,
    )
    goals = obs[goal_idx]

    reward_states = obs[next_idx] if config.relabel_target == "next" else obs[indices]
    rewards = goal_conditioned_reward(
        reward_states,
        goals,
        threshold=config.goal_threshold,
        distance_dims=config.goal_distance_dims,
        state_std=config.state_std,
    )
    dones = (rewards > DEFAULT_REWARD_UNACHIEVED + 1e-6).astype(np.float32)

    batch: Dict[str, np.ndarray] = {
        "observations": obs[indices].astype(np.float32),
        "actions": (actions[indices] if actions is not None else np.zeros((len(indices), 0), dtype=np.float32)).astype(np.float32),
        "rewards": rewards.astype(np.float32),
        "next_observations": obs[next_idx].astype(np.float32),
        "dones": dones.astype(np.float32),
        "goals": goals.astype(np.float32),
        "next_goals": goals.astype(np.float32),
        "indices": indices.astype(np.int64),
    }
    return batch


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------


def train_gc_iql(
    dataset: Any = None,
    config: Optional[GCIQLConfig] = None,
    steps: Optional[int] = None,
    device: Optional[Any] = None,
    agent: Optional[GCIQLAgent] = None,
    progress: bool = True,
    log_every: int = 5000,
    log_fn: Optional[Callable[[int, Dict[str, float]], None]] = None,
    **config_overrides: Any,
) -> Dict[str, Any]:
    """Train a GC-IQL agent on an offline dataset (no environment rewards)."""
    if not _HAS_TORCH:
        raise RuntimeError("torch is required to train GC-IQL")

    config = config or GCIQLConfig()
    if config_overrides:
        config = config.replace(**{k: v for k, v in config_overrides.items() if hasattr(config, k)})
    steps = int(steps if steps is not None else config.steps)

    if device is not None:
        config = config.replace(device=str(device))
    device_t = torch.device(config.device)

    obs = _dataset_array(dataset, "observations", "states")
    actions = _dataset_array(dataset, "actions")
    if obs is None:
        raise ValueError("dataset does not expose observations/states")
    state_dim = int(config.state_dim or obs.shape[-1])
    action_dim = int(config.action_dim or (actions.shape[-1] if actions is not None else 0))
    goal_dim = int(config.goal_dim or state_dim)

    if agent is None:
        agent = GCIQLAgent(
            state_dim=state_dim,
            action_dim=action_dim,
            goal_dim=goal_dim,
            hidden_dims=config.hidden_dims,
            expectile=config.expectile,
            awr_temperature=config.awr_temperature,
            discount=config.discount,
            target_update_rate=config.target_update_rate,
            learning_rate=config.learning_rate,
            activation=config.activation,
            use_layer_norm=config.use_layer_norm,
            action_low=config.action_low,
            action_high=config.action_high,
            log_std_min=config.log_std_min,
            log_std_max=config.log_std_max,
            exp_adv_clamp=config.exp_adv_clamp,
            update_policy=config.update_policy,
            device=device_t,
        )
    agent.to(device_t)
    agent.train()

    rng = np.random.default_rng(config.seed)
    sampler = GoalSampler(
        p_current=config.p_current,
        p_future=config.p_future,
        p_random=config.p_random,
        geometric_p=config.geometric_p,
        min_offset=config.min_offset,
        seed=config.seed,
    )

    iterator = range(steps)
    if progress:
        try:
            from tqdm.auto import tqdm  # type: ignore

            iterator = tqdm(iterator, desc="gc-iql", total=steps)
        except Exception:  # pragma: no cover
            pass

    history: List[Dict[str, float]] = []
    last_metrics: Dict[str, float] = {}
    start = time.time()
    for step in iterator:
        batch = sample_gc_batch(dataset, config.batch_size, rng, config=config, goal_sampler=sampler)
        metrics = agent.update(batch)
        last_metrics = metrics
        if log_every and (step + 1) % log_every == 0:
            history.append({"step": step + 1, **metrics})
            if log_fn is not None:
                log_fn(step + 1, metrics)
            if progress:
                try:
                    iterator.set_postfix(  # type: ignore[attr-defined]
                        q=metrics.get("q_mean", float("nan")),
                        v=metrics.get("v_mean", float("nan")),
                    )
                except Exception:  # pragma: no cover
                    pass

    return {
        "agent": agent,
        "config": config.to_dict(),
        "steps": steps,
        "history": history,
        "final_metrics": last_metrics,
        "wall_time": time.time() - start,
    }


# ---------------------------------------------------------------------------
# Evaluation (ground-truth goal conditioning)
# ---------------------------------------------------------------------------


def _resolve_device(agent: Any, device: Optional[Any]) -> Any:
    if device is not None:
        return device
    try:
        iter_params = getattr(agent, "parameters")
        return next(iter_params()).device
    except Exception:  # pragma: no cover
        return "cpu"


def antmaze_goal_to_observation(
    goal_xy: Sequence[float],
    dataset: Any = None,
    state_dim: Optional[int] = None,
    discretize: bool = True,
    num_bins: int = 32,
    xy_indices: Sequence[int] = (0, 1),
    xy_min: Optional[Sequence[float]] = None,
    xy_max: Optional[Sequence[float]] = None,
) -> np.ndarray:
    """Convert an AntMaze ``(x, y)`` goal into the observation space used by the agent.

    AntMaze XY coordinates are discretized into 32 bins for FRE/GC-IQL/GC-BC/OPAL
    (Appendix C.1 / addendum), so goals must live in the same space.
    """
    state_dim = int(state_dim or 29)
    goal = np.zeros(state_dim, dtype=np.float32)
    xy = np.asarray(goal_xy, dtype=np.float32).reshape(2)

    if discretize:
        if xy_min is None or xy_max is None:
            obs = _dataset_array(dataset, "observations", "states") if dataset is not None else None
            if obs is not None:
                xy_min = np.min(obs[:, list(xy_indices)], axis=0)
                xy_max = np.max(obs[:, list(xy_indices)], axis=0)
            else:
                xy_min = np.zeros(2, dtype=np.float32)
                xy_max = np.full(2, 36.0, dtype=np.float32)
        xy_min = np.asarray(xy_min, dtype=np.float32).reshape(2)
        xy_max = np.asarray(xy_max, dtype=np.float32).reshape(2)
        rng_span = np.maximum(xy_max - xy_min, 1e-8)
        norm = np.clip((xy - xy_min) / rng_span, 0.0, 1.0)
        binned = np.clip(np.floor(norm * num_bins), 0, num_bins - 1)
        xy = binned.astype(np.float32)

    goal[list(xy_indices)] = xy.astype(np.float32)
    return goal


def goal_from_task(
    task: Any,
    dataset: Any = None,
    state_dim: Optional[int] = None,
    discretize_antmaze: bool = True,
    domain: Optional[str] = None,
    num_bins: int = 32,
) -> np.ndarray:
    """Extract the ground-truth goal a GC agent is conditioned on (addendum)."""
    goal = getattr(task, "goal", None)
    if goal is None:
        metadata = getattr(task, "metadata", None) or {}
        goal = metadata.get("goal") if isinstance(metadata, Mapping) else None

    state_dim = int(state_dim or getattr(task, "state_dim", None) or 29)
    if goal is None:
        return np.zeros(state_dim, dtype=np.float32)

    goal = np.asarray(_to_numpy(goal), dtype=np.float32).reshape(-1)
    if goal.shape[0] == state_dim:
        return goal.astype(np.float32)

    domain = domain or ("antmaze" if getattr(task, "name", "").startswith("ant") else None)
    if domain == "antmaze" and goal.shape[0] >= 2:
        return antmaze_goal_to_observation(
            goal[:2],
            dataset=dataset,
            state_dim=state_dim,
            discretize=discretize_antmaze,
            num_bins=num_bins,
        )

    padded = np.zeros(state_dim, dtype=np.float32)
    dims = min(state_dim, goal.shape[0])
    padded[:dims] = goal[:dims]
    return padded


def gc_iql_action_fn(
    agent: GCIQLAgent,
    goal: Any,
    deterministic: bool = True,
    state_fn: Optional[Callable[[Any], Any]] = None,
) -> Callable[[Any], np.ndarray]:
    """Build an ``action_fn`` for :func:`fre.evaluation.evaluate.rollout_episode`."""

    def action_fn(state: Any) -> np.ndarray:
        obs = state_fn(state) if state_fn is not None else state
        action = agent.select_action(obs, goal, deterministic=deterministic)
        return np.asarray(action).reshape(-1)

    return action_fn


def evaluate_gc_agent(
    agent: GCIQLAgent,
    domain: str = "antmaze",
    task_set: str = "all",
    dataset: Any = None,
    num_episodes: int = 20,
    seeds: Sequence[int] = (0, 1, 2, 3, 4),
    deterministic: bool = True,
    max_episode_steps: Optional[int] = None,
    device: Optional[Any] = None,
    verbose: bool = False,
    discretize_antmaze: bool = True,
    goal_override: Optional[Mapping[str, Any]] = None,
    **task_kwargs: Any,
) -> Dict[str, Any]:
    """Zero-shot style evaluation of GC-IQL using each task's ground-truth goal.

    Returns the same summary structure as ``fre.evaluation.evaluate.evaluate_fre``
    so the CLI/reporting helpers can be shared.
    """
    from fre.envs import build_tasks, domain_from_task_name  # local import (heavy deps)
    from fre.evaluation.metrics import NUM_EVAL_EPISODES, NUM_SEEDS, aggregate_seeds, aggregate_tasks
    from fre.evaluation.evaluate import (
        RolloutResult,
        normalize_episode_return,
        resolve_return_range,
        rollout_episode,
    )

    domain = domain_from_task_name(task_set) if task_set and str(task_set).startswith(("ant", "exorl", "kitchen")) else domain
    base = str(domain).split(":")[0]
    tasks = build_tasks(domain, task_set=task_set, dataset_states=None, **task_kwargs) if hasattr(build_tasks, "__call__") else []
    if not tasks:
        raise ValueError(f"no evaluation tasks found for domain={domain!r} task_set={task_set!r}")

    num_episodes = int(num_episodes or NUM_EVAL_EPISODES)
    seeds = tuple(seeds or tuple(range(NUM_SEEDS)))
    goal_override = dict(goal_override or {})

    per_task: Dict[str, Any] = {}
    for task in tasks:
        env = None
        task_name = getattr(task, "name", str(task))
        per_seed: List[Dict[str, float]] = []
        for seed in seeds:
            env = _make_task_env_for_domain(base, task, seed=seed, max_episode_steps=max_episode_steps)
            goal = goal_override.get(task_name)
            if goal is None:
                state_dim = getattr(agent, "state_dim", None)
                goal = goal_from_task(
                    task,
                    dataset=dataset,
                    state_dim=state_dim,
                    discretize_antmaze=discretize_antmaze,
                    domain=base,
                )
            else:
                goal = np.asarray(_to_numpy(goal), dtype=np.float32).reshape(-1)
            action_fn = gc_iql_action_fn(agent, goal, deterministic=deterministic)

            returns: List[float] = []
            successes = 0
            for ep in range(num_episodes):
                result: "RolloutResult" = rollout_episode(
                    env,
                    action_fn,
                    task,
                    max_episode_steps=max_episode_steps,
                    seed=int(seed) * 10_000 + ep,
                )
                returns.append(float(result.return_))
                successes += int(bool(result.success))
            aggregated = aggregate_seeds([{"seed": int(seed), "mean_return": float(np.mean(returns))}])
            per_seed.append(
                {
                    "seed": int(seed),
                    "mean_return": float(np.mean(returns)),
                    "std_return": float(np.std(returns)),
                    "success_rate": successes / max(num_episodes, 1),
                    "normalized_mean": aggregated.get("normalized_mean", float("nan")),
                }
            )
            if env is not None:
                try:
                    env.close()
                except Exception:  # pragma: no cover
                    pass
                env = None

        raw_mean = float(np.mean([s["mean_return"] for s in per_seed]))
        raw_std = float(np.std([s["mean_return"] for s in per_seed]))
        ref_min, ref_max = resolve_return_range(task)
        per_task[task_name] = {
            "task": task_name,
            "task_set": getattr(task, "task_set", task_set),
            "mean": raw_mean,
            "std": raw_std,
            "normalized": normalize_episode_return(raw_mean, ref_min, ref_max, clip=True),
            "success_rate": float(np.mean([s["success_rate"] for s in per_seed])),
            "num_seeds": len(per_seed),
            "per_seed": per_seed,
        }
        if verbose:
            print(f"[gc-iql] {task_name}: {per_task[task_name]['normalized']:.1f}")

    summary = {
        "method": "gc_iql",
        "domain": domain,
        "task_set": task_set,
        "tasks": per_task,
        "task_sets": aggregate_tasks(list(per_task.values())),
    }
    try:
        summary["task_sets"] = aggregate_tasks(list(per_task.values()))
    except Exception:  # pragma: no cover
        pass
    return summary


def _make_task_env_for_domain(domain: str, task: Any, seed: Optional[int] = None, max_episode_steps: Optional[int] = None) -> Any:
    domain = str(domain).split(":")[0]
    if domain == "antmaze":
        from fre.envs.antmaze_tasks import make_antmaze_task_env

        return make_antmaze_task_env(task, seed=seed, max_episode_steps=max_episode_steps)
    if domain in ("exorl", "walker", "cheetah"):
        from fre.envs.exorl_tasks import make_exorl_task_env

        return make_exorl_task_env(task, seed=seed, max_episode_steps=max_episode_steps)
    if domain == "kitchen":
        from fre.envs.kitchen_tasks import make_kitchen_task_env

        return make_kitchen_task_env(task, seed=seed, max_episode_steps=max_episode_steps)
    raise ValueError(f"unknown domain {domain!r}")


def evaluate_gc_iql(*args: Any, **kwargs: Any) -> Dict[str, Any]:
    """Alias for :func:`evaluate_gc_agent`."""
    return evaluate_gc_agent(*args, **kwargs)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="GC-IQL baseline for zero-shot offline RL")
    parser.add_argument("--domain", type=str, default="antmaze")
    parser.add_argument("--task-set", type=str, default="all")
    parser.add_argument("--steps", type=int, default=DEFAULT_GC_TRAIN_STEPS)
    parser.add_argument("--batch-size", type=int, default=DEFAULT_GC_BATCH_SIZE)
    parser.add_argument("--lr", type=float, default=DEFAULT_GC_LEARNING_RATE)
    parser.add_argument("--expectile", type=float, default=DEFAULT_EXPECTILE)
    parser.add_argument("--temperature", type=float, default=DEFAULT_AWR_TEMPERATURE)
    parser.add_argument("--discount", type=float, default=DEFAULT_GC_DISCOUNT)
    parser.add_argument("--tau", type=float, default=DEFAULT_TARGET_UPDATE_RATE)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--device", type=str, default="cpu")
    parser.add_argument("--dataset-path", type=str, default=None)
    parser.add_argument("--dataset-dir", type=str, default=None)
    parser.add_argument("--env-name", type=str, default=None)
    parser.add_argument("--run-dir", type=str, default=None)
    parser.add_argument("--num-episodes", type=int, default=20)
    parser.add_argument("--eval-seeds", type=int, default=5)
    parser.add_argument("--eval", action="store_true", help="run zero-shot evaluation after training")
    parser.add_argument("--log-every", type=int, default=5000)
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args, _unknown = build_arg_parser().parse_known_args(argv)
    if not _HAS_TORCH:
        print("torch is required for the GC-IQL baseline")
        return 1

    from fre.data import load_dataset

    dataset = load_dataset(
        domain=args.domain,
        env_name=args.env_name,
        dataset_path=args.dataset_path,
        dataset_dir=args.dataset_dir,
    )

    config = GCIQLConfig(
        domain=args.domain,
        steps=args.steps,
        batch_size=args.batch_size,
        learning_rate=args.lr,
        expectile=args.expectile,
        awr_temperature=args.temperature,
        discount=args.discount,
        target_update_rate=args.tau,
        seed=args.seed,
        device=args.device,
    )
    result = train_gc_iql(dataset=dataset, config=config, progress=True, log_every=args.log_every)
    agent = result["agent"]

    run_dir = args.run_dir or os.path.join("runs", "gc_iql", str(args.domain))
    os.makedirs(run_dir, exist_ok=True)
    torch.save(
        {
            "agent": agent.state_dict(),
            "hparams": agent.hparams(),
            "config": result["config"],
        },
        os.path.join(run_dir, "checkpoint.pt"),
    )
    with open(os.path.join(run_dir, "history.json"), "w", encoding="utf-8") as fh:
        json.dump(result["history"], fh, indent=2)

    if args.eval:
        summary = evaluate_gc_agent(
            agent,
            domain=args.domain,
            task_set=args.task_set,
            dataset=dataset,
            num_episodes=args.num_episodes,
            seeds=tuple(range(args.eval_seeds)),
        )
        with open(os.path.join(run_dir, "eval.json"), "w", encoding="utf-8") as fh:
            json.dump(summary, fh, indent=2, default=float)
        print(json.dumps(summary.get("task_sets", {}), indent=2, default=float))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
