"""Masked Language Modeling (MLM) ablation loss for BBox-Adapter.

Paper (§4.5, verbatim):
    "We compare the efficacy of ranking-based NCE loss against the Masked Language
     Modeling (MLM) loss. For the MLM-based approach, we generate text chunks from the
     groundtruth data, randomly masking words, and then train the adapter using the
     masked word as supervision. During inference, we apply a similar process: masking a
     random word in each sequence generated by beam search and scoring the sequence
     based on the probability of the masked word."

Reference numbers (Table 5, accuracy %):

    =====  ============  ============  ========  ========
    Loss   StratQA 0.1B  StratQA 0.3B  GSM 0.1B  GSM 0.3B
    =====  ============  ============  ========  ========
    MLM    61.52         60.41         70.56     70.81
    NCE    71.62         71.18         72.06     73.86
    =====  ============  ============  ========  ========

The ablation intentionally mirrors the NCE pipeline in :mod:`bbox_adapter.losses.nce`:

* training: one scalar objective term (masked-token cross entropy) on text chunks
  built from the *ground-truth* answers (positives);
* inference: a scalar *score per candidate sequence* obtained by masking a random word
  and reading off the probability the model assigns to the true (removed) word.

Both entry points are exposed through the ``EnergyModel``-compatible surface
``score_pairs(questions, answers) -> Tensor[N]`` so that ``inference/beam_search.py``
can swap the evaluator without any other change.

NOTE (paper, §3.2 + Addendum): the ``alpha * E[g^2]`` regularization applies to the
ranking-based NCE objective only; the MLM ablation is trained with plain cross entropy.
"""

from __future__ import annotations

import math
import os
import random
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple, Union

import torch
import torch.nn as nn
import torch.nn.functional as F

__all__ = [
    "MLMLossConfig",
    "MaskedLMLoss",
    "MLMAdapter",
    "MaskedLMScorer",
    "compute_mlm_loss",
    "mlm_objective",
    "mlm_loss_from_model",
    "masked_word_probability",
    "apply_random_mask",
    "word_spans",
    "split_text_chunks",
    "select_mask_word_indices",
    "build_mlm_batch",
    "masked_word_log_prob",
    "sentence_masked_word_score",
    "resolve_mlm_backbone",
]


# --------------------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------------------


@dataclass
class MLMLossConfig:
    """Configuration for the masked-LM ablation.

    Defaults mirror the BBox-Adapter setup (§H.2): max length 512 and the same small
    encoder backbone used by the energy adapter (DeBERTa-v3-base/large, BERT-base-cased).
    """

    backbone: Optional[str] = None
    dataset: Optional[str] = None
    size: str = "0.1b"
    max_length: int = 512
    # --- masking ---------------------------------------------------------------
    mask_prob: float = 0.15          # fraction of *words* masked
    max_masks_per_sequence: int = 5  # cap on masked words per sequence
    mask_whole_words: bool = True    # §4.5: "randomly masking words" (word level)
    prob_replace_mask: float = 0.8   # BERT-style 80/10/10 corruption
    prob_replace_random: float = 0.1
    # --- objective -------------------------------------------------------------
    reduction: str = "mean"          # {"mean", "sum", "none"}
    ignore_index: int = -100
    label_smoothing: float = 0.0
    # --- inference scoring -----------------------------------------------------
    n_inference_masks: int = 1       # "masking a random word in each sequence"
    inference_score: str = "logprob"  # {"logprob", "prob"}
    inference_reduction: str = "mean"
    seed: int = 0
    extra: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.reduction not in {"mean", "sum", "none"}:
            raise ValueError(f"unknown reduction {self.reduction!r}")
        if self.inference_score not in {"logprob", "prob"}:
            raise ValueError(f"unknown inference_score {self.inference_score!r}")
        if not 0.0 < self.mask_prob <= 1.0:
            raise ValueError("mask_prob must be in (0, 1]")
        s = self.prob_replace_mask + self.prob_replace_random
        if s > 1.0 + 1e-9:
            raise ValueError("prob_replace_mask + prob_replace_random must be <= 1")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "backbone": self.backbone,
            "dataset": self.dataset,
            "size": self.size,
            "max_length": self.max_length,
            "mask_prob": self.mask_prob,
            "max_masks_per_sequence": self.max_masks_per_sequence,
            "mask_whole_words": self.mask_whole_words,
            "prob_replace_mask": self.prob_replace_mask,
            "prob_replace_random": self.prob_replace_random,
            "reduction": self.reduction,
            "ignore_index": self.ignore_index,
            "label_smoothing": self.label_smoothing,
            "n_inference_masks": self.n_inference_masks,
            "inference_score": self.inference_score,
            "inference_reduction": self.inference_reduction,
            "seed": self.seed,
            "extra": dict(self.extra),
        }

    @classmethod
    def from_dict(cls, d: Optional[Dict[str, Any]]) -> "MLMLossConfig":
        if not d:
            return cls()
        known = {f for f in cls.__dataclass_fields__}  # type: ignore[attr-defined]
        return cls(**{k: v for k, v in d.items() if k in known})


# --------------------------------------------------------------------------------------
# Backbone resolution (mirrors adapter/energy_model.py, kept local to avoid a hard import)
# --------------------------------------------------------------------------------------


def resolve_mlm_backbone(
    dataset: Optional[str] = None,
    size: Optional[str] = None,
    backbone: Optional[str] = None,
) -> str:
    """Resolve the MLM backbone checkpoint (explicit > size alias > per-dataset)."""
    if backbone:
        return backbone
    try:  # reuse the canonical maps from the energy adapter when available
        from ..adapter.energy_model import ADAPTER_BACKBONES, SIZE_BACKBONES

        key_size = str(size or "").lower().replace("-", "").replace("_", "")
        if key_size and key_size in SIZE_BACKBONES:
            return SIZE_BACKBONES[key_size]
        key_ds = str(dataset or "").lower().replace("-", "").replace("_", "")
        if key_ds in ADAPTER_BACKBONES:
            return ADAPTER_BACKBONES[key_ds]
    except Exception:  # pragma: no cover - optional import
        pass
    if str(size or "").lower().replace("-", "").replace("_", "") in {"0.3b", "304m", "large"}:
        return "microsoft/deberta-v3-large"
    return "microsoft/deberta-v3-base"


def _hf_classes():
    """Lazily import transformers helpers (heavy dependency)."""
    try:
        from transformers import AutoModelForMaskedLM, AutoTokenizer
    except Exception as exc:  # pragma: no cover - dependency guard
        raise ImportError(
            "The MLM ablation requires `transformers`. Install with "
            "`pip install transformers` (see requirements.txt)."
        ) from exc
    return AutoModelForMaskedLM, AutoTokenizer


# --------------------------------------------------------------------------------------
# Word-level text utilities (§4.5: "generate text chunks ... randomly masking words")
# --------------------------------------------------------------------------------------


def word_spans(text: str) -> List[Tuple[int, int]]:
    """Character spans of whitespace-delimited words (including attached punctuation)."""
    spans: List[Tuple[int, int]] = []
    start = None
    for i, ch in enumerate(text):
        if ch.isspace():
            if start is not None:
                spans.append((start, i))
                start = None
        elif start is None:
            start = i
    if start is not None:
        spans.append((start, len(text)))
    return spans


def split_text_chunks(text: str, max_words: int = 128) -> List[str]:
    """Split a text into word chunks (used to build the ground-truth training chunks)."""
    words = text.split()
    if max_words <= 0 or len(words) <= max_words:
        return [text] if text.strip() else []
    return [" ".join(words[i : i + max_words]) for i in range(0, len(words), max_words)]


def select_mask_word_indices(
    word_ids: Sequence[Optional[int]],
    *,
    mask_prob: float = 0.15,
    max_masks: int = 5,
    rng: Optional[random.Random] = None,
    forced_word: Optional[int] = None,
) -> List[int]:
    """Choose token positions to mask, operating on *words* rather than tokens.

    ``word_ids`` maps each token position to a word id (``None`` for special tokens),
    exactly what a fast tokenizer's ``word_ids()`` returns.
    """
    rng = rng or random.Random()
    groups: Dict[int, List[int]] = {}
    for pos, wid in enumerate(word_ids):
        if wid is None:
            continue
        groups.setdefault(int(wid), []).append(pos)
    n_words = len(groups)
    if n_words == 0:
        return []
    if forced_word is not None:
        return list(groups.get(int(forced_word), []))
    n_mask = max(1, int(math.ceil(mask_prob * n_words)))
    n_mask = min(n_mask, max_masks, n_words)
    chosen = rng.sample(sorted(groups.keys()), n_mask)
    positions: List[int] = []
    for wid in chosen:
        positions.extend(groups[wid])
    return sorted(positions)


def _special_token_positions(tokenizer: Any, input_ids: Sequence[int]) -> List[int]:
    """Best-effort identification of special tokens in ``input_ids``."""
    try:
        mask = tokenizer.get_special_tokens_mask(list(input_ids), already_has_special_tokens=True)
        return [i for i, m in enumerate(mask) if m]
    except Exception:
        specials = set(getattr(tokenizer, "all_special_ids", []) or [])
        return [i for i, tid in enumerate(input_ids) if tid in specials]


def _word_ids(tokenizer: Any, text: str) -> Tuple[List[int], List[Optional[int]]]:
    """Tokenize ``text`` and return ``(token_ids, word_ids)`` without special tokens."""
    enc = tokenizer(text, add_special_tokens=False, truncation=False)["input_ids"]
    ids = list(enc) if not (enc and isinstance(enc[0], list)) else list(enc[0])
    wid: List[Optional[int]] = list(range(len(ids)))
    return ids, wid


# --------------------------------------------------------------------------------------
# Masked-token probability and loss
# --------------------------------------------------------------------------------------


def compute_mlm_loss(
    logits: torch.Tensor,
    labels: torch.Tensor,
    attention_mask: Optional[torch.Tensor] = None,
    *,
    reduction: str = "mean",
    ignore_index: int = -100,
    label_smoothing: float = 0.0,
) -> torch.Tensor:
    """Masked-token cross entropy.

    Args:
        logits: ``[B, L, V]`` LM head outputs.
        labels: ``[B, L]`` target ids with ``ignore_index`` at unmasked positions.
        attention_mask: optional ``[B, L]`` mask (unused positions must already be
            ``ignore_index`` in ``labels``; the mask only guards against garbage).
    """
    if labels is None:
        raise ValueError("labels are required for the MLM loss")
    if attention_mask is not None:
        labels = labels.masked_fill(attention_mask == 0, ignore_index)
    vocab = logits.shape[-1]
    loss = F.cross_entropy(
        logits.reshape(-1, vocab),
        labels.reshape(-1),
        ignore_index=ignore_index,
        reduction=reduction,
        label_smoothing=float(label_smoothing),
    )
    return loss


def mlm_objective(
    logits: torch.Tensor,
    labels: torch.Tensor,
    attention_mask: Optional[torch.Tensor] = None,
    **kwargs: Any,
) -> torch.Tensor:
    """Alias of :func:`compute_mlm_loss` (paper-facing name)."""
    return compute_mlm_loss(logits, labels, attention_mask, **kwargs)


def masked_word_log_prob(
    logits: torch.Tensor,
    labels: torch.Tensor,
    mask_positions: Optional[torch.Tensor] = None,
    *,
    ignore_index: int = -100,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Log-probability of the *true* masked word.

    Returns ``(log_probs, counts)`` where ``log_probs`` is ``[B]`` (sum over the masked
    positions of each sequence) and ``counts`` is ``[B]`` (number of masked positions).
    """
    log_probs = F.log_softmax(logits.float(), dim=-1)  # [B, L, V]
    if mask_positions is None:
        mask_positions = labels != ignore_index
    else:
        mask_positions = mask_positions.bool()
    safe_labels = labels.clamp(min=0)
    gathered = log_probs.gather(-1, safe_labels.unsqueeze(-1)).squeeze(-1)  # [B, L]
    gathered = gathered * mask_positions.to(gathered.dtype)
    return gathered.sum(dim=-1), mask_positions.sum(dim=-1).to(gathered.dtype)


def masked_word_probability(
    logits: torch.Tensor,
    labels: torch.Tensor,
    mask_positions: Optional[torch.Tensor] = None,
    *,
    ignore_index: int = -100,
    reduction: str = "mean",
) -> torch.Tensor:
    """Probability ``p(true masked word)`` averaged over masked positions.

    This is the inference-time scoring quantity of §4.5 ("scoring the sequence based on
    the probability of the masked word").
    """
    log_p, counts = masked_word_log_prob(logits, labels, mask_positions, ignore_index=ignore_index)
    probs = torch.exp(log_p)
    if reduction == "none":
        return probs
    if reduction == "sum":
        return probs.sum()
    denom = counts.clamp(min=1.0)
    return (probs / denom).mean()


def sentence_masked_word_score(
    logits: torch.Tensor,
    labels: torch.Tensor,
    mask_positions: Optional[torch.Tensor] = None,
    *,
    mode: str = "logprob",
    reduction: str = "mean",
    ignore_index: int = -100,
) -> torch.Tensor:
    """Per-sequence score used to rank beam-search candidates with the MLM ablation.

    Higher is better (log-probability or probability of the masked word).
    """
    log_p, counts = masked_word_log_prob(logits, labels, mask_positions, ignore_index=ignore_index)
    if mode == "logprob":
        scores = log_p
    elif mode == "prob":
        scores = torch.exp(log_p)
    else:
        raise ValueError(f"unknown scoring mode {mode!r}")
    if reduction == "mean":
        scores = scores / counts.clamp(min=1.0)
    return scores


# --------------------------------------------------------------------------------------
# Training-batch construction
# --------------------------------------------------------------------------------------


def build_mlm_batch(
    texts: Sequence[str],
    tokenizer: Any,
    config: Optional[MLMLossConfig] = None,
    *,
    rng: Optional[random.Random] = None,
    device: Optional[torch.device] = None,
) -> Dict[str, torch.Tensor]:
    """Tokenize ``texts`` and apply random-word masking plus labels.

    Returns a dict with ``input_ids``, ``attention_mask``, ``labels`` and
    ``mask_positions`` (bool ``[B, L]``).
    """
    cfg = config or MLMLossConfig()
    rng = rng or random.Random(cfg.seed)
    mask_token_id = getattr(tokenizer, "mask_token_id", None)
    if mask_token_id is None:
        raise ValueError("tokenizer has no mask token; a masked-LM tokenizer is required")
    vocab_size = int(getattr(tokenizer, "vocab_size", 0) or 0)

    all_ids: List[List[int]] = []
    all_labels: List[List[int]] = []
    for text in texts:
        enc = tokenizer(
            str(text),
            add_special_tokens=True,
            truncation=True,
            max_length=cfg.max_length,
            return_tensors=None,
        )
        ids = list(enc["input_ids"])
        if hasattr(tokenizer, "word_ids") and hasattr(tokenizer, "__call__"):
            try:
                fast = tokenizer(str(text), add_special_tokens=True, truncation=True,
                                 max_length=cfg.max_length)
                word_ids = list(fast.word_ids()) if hasattr(fast, "word_ids") else None
            except Exception:
                word_ids = None
        else:
            word_ids = None
        if word_ids is None or len(word_ids) != len(ids):
            special = set(_special_token_positions(tokenizer, ids)) if ids else set()
            word_ids = [None if i in special else i for i in range(len(ids))]
        if not cfg.mask_whole_words:
            word_ids = [None if w is None else i for i, w in enumerate(word_ids)]

        positions = select_mask_word_indices(
            word_ids,
            mask_prob=cfg.mask_prob,
            max_masks=cfg.max_masks_per_sequence,
            rng=rng,
        )
        labels = [cfg.ignore_index] * len(ids)
        for pos in positions:
            original = ids[pos]
            labels[pos] = original
            r = rng.random()
            if r < cfg.prob_replace_mask:
                ids[pos] = int(mask_token_id)
            elif r < cfg.prob_replace_mask + cfg.prob_replace_random and vocab_size > 0:
                ids[pos] = rng.randrange(vocab_size)
            # else: keep the original token (10% branch)
        all_ids.append(ids)
        all_labels.append(labels)

    max_len = max((len(x) for x in all_ids), default=0) or 1
    pad_id = int(getattr(tokenizer, "pad_token_id", 0) or 0)
    input_ids = torch.full((len(all_ids), max_len), pad_id, dtype=torch.long)
    attention_mask = torch.zeros((len(all_ids), max_len), dtype=torch.long)
    labels = torch.full((len(all_labels), max_len), cfg.ignore_index, dtype=torch.long)
    for i, (ids, labs) in enumerate(zip(all_ids, all_labels)):
        input_ids[i, : len(ids)] = torch.tensor(ids, dtype=torch.long)
        attention_mask[i, : len(ids)] = 1
        labels[i, : len(labs)] = torch.tensor(labs, dtype=torch.long)
    batch = {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "labels": labels,
        "mask_positions": labels != cfg.ignore_index,
    }
    if device is not None:
        batch = {k: v.to(device) for k, v in batch.items()}
    return batch


def apply_random_mask(
    text: str,
    tokenizer: Optional[Any] = None,
    config: Optional[MLMLossConfig] = None,
    *,
    rng: Optional[random.Random] = None,
) -> Tuple[str, List[str]]:
    """Replace a random word of ``text`` with the mask token (§4.5, training/inference).

    Returns ``(masked_text, removed_words)``. Purely string based, so it works with any
    tokenizer and is handy for building "text chunks from the groundtruth data".
    """
    cfg = config or MLMLossConfig()
    rng = rng or random.Random(cfg.seed)
    spans = word_spans(text)
    if not spans:
        return text, []
    n_mask = max(1, int(math.ceil(cfg.mask_prob * len(spans))))
    n_mask = min(n_mask, cfg.max_masks_per_sequence, len(spans))
    chosen = sorted(rng.sample(range(len(spans)), n_mask), reverse=True)
    mask_str = getattr(tokenizer, "mask_token", None) or "[MASK]"
    masked = text
    removed: List[str] = []
    for idx in chosen:
        s, e = spans[idx]
        removed.append(text[s:e])
        masked = masked[:s] + mask_str + masked[e:]
    removed.reverse()
    return masked, removed


# --------------------------------------------------------------------------------------
# Masked-LM adapter (the ablation's learnable module)
# --------------------------------------------------------------------------------------


class MLMAdapter(nn.Module):
    """Small masked-LM adapter used for the MLM ablation of Table 5.

    It is structurally the same tiny encoder as the energy adapter, but with a
    vocabulary-sized MLM head instead of a scalar energy head, trained with masked-word
    cross entropy on ground-truth text chunks (§4.5).
    """

    def __init__(
        self,
        config: Optional[MLMLossConfig] = None,
        tokenizer: Optional[Any] = None,
        *,
        backbone: Optional[str] = None,
    ) -> None:
        super().__init__()
        cfg = config or MLMLossConfig()
        if isinstance(cfg, dict):
            cfg = MLMLossConfig.from_dict(cfg)
        self.config = cfg
        AutoModelForMaskedLM, AutoTokenizer = _hf_classes()
        resolved = resolve_mlm_backbone(cfg.dataset, cfg.size, backbone or cfg.backbone)
        self.backbone_name = resolved
        if tokenizer is None:
            try:
                tokenizer = AutoTokenizer.from_pretrained(resolved)
            except Exception as exc:  # pragma: no cover - network guard
                raise RuntimeError(f"could not load tokenizer for {resolved!r}: {exc}") from exc
        self.tokenizer = tokenizer
        try:
            self.model = AutoModelForMaskedLM.from_pretrained(resolved)
        except Exception as exc:  # pragma: no cover - network guard
            raise RuntimeError(f"could not load MLM backbone {resolved!r}: {exc}") from exc

    # -- io ---------------------------------------------------------------------
    @classmethod
    def from_pretrained(
        cls,
        path_or_dir: str,
        config: Optional[MLMLossConfig] = None,
        tokenizer: Optional[Any] = None,
        map_location: str = "cpu",
    ) -> "MLMAdapter":
        cfg_path = os.path.join(path_or_dir, "mlm_config.pt")
        weights = os.path.join(path_or_dir, "mlm_adapter.pt")
        if config is None and os.path.isfile(cfg_path):
            blob = torch.load(cfg_path, map_location="cpu")
            config = MLMLossConfig.from_dict(blob if isinstance(blob, dict) else None)
        obj = cls(config=config, tokenizer=tokenizer)
        if os.path.isfile(weights):
            state = torch.load(weights, map_location=map_location)
            missing, unexpected = obj.load_state_dict(state, strict=False)
            obj._missing_keys, obj._unexpected_keys = list(missing), list(unexpected)
        return obj

    def save_pretrained(self, path_or_dir: str) -> None:
        os.makedirs(path_or_dir, exist_ok=True)
        torch.save(self.state_dict(), os.path.join(path_or_dir, "mlm_adapter.pt"))
        torch.save(self.config.to_dict(), os.path.join(path_or_dir, "mlm_config.pt"))
        tok_dir = os.path.join(path_or_dir, "tokenizer")
        try:
            self.tokenizer.save_pretrained(tok_dir)
        except Exception:  # pragma: no cover - optional
            pass

    # -- core -------------------------------------------------------------------
    @property
    def device(self) -> torch.device:
        try:
            return next(self.parameters()).device
        except StopIteration:  # pragma: no cover
            return torch.device("cpu")

    def num_parameters(self, trainable_only: bool = False) -> int:
        params = [p for p in self.parameters() if (p.requires_grad or not trainable_only)]
        return int(sum(p.numel() for p in params))

    def forward(
        self,
        input_ids: torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
        **kwargs: Any,
    ) -> torch.Tensor:
        """Return vocabulary logits ``[B, L, V]``."""
        out = self.model(input_ids=input_ids, attention_mask=attention_mask, **kwargs)
        return out.logits if hasattr(out, "logits") else out[0]

    def tokenize(
        self,
        texts: Sequence[str],
        max_length: Optional[int] = None,
    ) -> Dict[str, torch.Tensor]:
        enc = self.tokenizer(
            list(texts),
            add_special_tokens=True,
            truncation=True,
            max_length=int(max_length or self.config.max_length),
            padding=True,
            return_tensors="pt",
        )
        return {k: v for k, v in dict(enc).items() if k in {"input_ids", "attention_mask", "token_type_ids"}}

    # -- training ---------------------------------------------------------------
    def batch(
        self,
        texts: Sequence[str],
        *,
        rng: Optional[random.Random] = None,
        device: Optional[torch.device] = None,
    ) -> Dict[str, torch.Tensor]:
        return build_mlm_batch(texts, self.tokenizer, self.config, rng=rng, device=device)

    def loss(
        self,
        texts: Optional[Sequence[str]] = None,
        *,
        batch: Optional[Dict[str, torch.Tensor]] = None,
        rng: Optional[random.Random] = None,
    ) -> torch.Tensor:
        """Masked-word cross entropy over ground-truth text chunks (§4.5 training)."""
        if batch is None:
            if texts is None:
                raise ValueError("provide either `texts` or `batch`")
            batch = self.batch(texts, rng=rng, device=self.device)
        logits = self.forward(batch["input_ids"], batch.get("attention_mask"))
        return compute_mlm_loss(
            logits,
            batch["labels"],
            batch.get("attention_mask"),
            reduction=self.config.reduction,
            ignore_index=self.config.ignore_index,
            label_smoothing=self.config.label_smoothing,
        )

    # -- inference --------------------------------------------------------------
    @torch.no_grad()
    def score_sequences(
        self,
        texts: Sequence[str],
        *,
        n_masks: Optional[int] = None,
        rng: Optional[random.Random] = None,
    ) -> torch.Tensor:
        """Score each sequence by the probability of a randomly masked word (§4.5)."""
        cfg = self.config
        rng = rng or random.Random(cfg.seed)
        n_masks = int(n_masks or cfg.n_inference_masks)
        scores: List[float] = []
        for text in texts:
            acc = 0.0
            used = 0
            for _ in range(max(1, n_masks)):
                batch = build_mlm_batch([str(text)], self.tokenizer, cfg,
                                        rng=rng, device=self.device)
                if not bool(batch["mask_positions"].any()):
                    continue
                logits = self.forward(batch["input_ids"], batch.get("attention_mask"))
                s = sentence_masked_word_score(
                    logits, batch["labels"], batch["mask_positions"],
                    mode=cfg.inference_score, reduction=cfg.inference_reduction,
                    ignore_index=cfg.ignore_index,
                )
                acc += float(s.mean().item())
                used += 1
            scores.append(acc / used if used else 0.0)
        return torch.tensor(scores, dtype=torch.float32)

    @torch.no_grad()
    def score_pairs(
        self,
        questions: Sequence[str],
        answers: Sequence[str],
        *,
        n_masks: Optional[int] = None,
        rng: Optional[random.Random] = None,
        batch_size: int = 32,
        **_: Any,
    ) -> torch.Tensor:
        """Energy-model-compatible interface: scalar score per ``(question, answer)``."""
        if len(questions) != len(answers):
            raise ValueError("questions and answers must have the same length")
        pairs = [f"Question: {q}\nAnswer: {a}" for q, a in zip(questions, answers)]
        chunks = [pairs[i : i + batch_size] for i in range(0, len(pairs), batch_size)] or [[]]
        out: List[torch.Tensor] = []
        for chunk in chunks:
            if chunk:
                out.append(self.score_sequences(chunk, n_masks=n_masks, rng=rng))
        if not out:
            return torch.zeros(0, dtype=torch.float32)
        return torch.cat(out, dim=0)


class MaskedLMScorer:
    """Thin ``EnergyModel``-shaped wrapper around :class:`MLMAdapter` for beam search."""

    def __init__(self, model: MLMAdapter, n_masks: Optional[int] = None, seed: int = 0) -> None:
        self.model = model
        self.n_masks = n_masks
        self.rng = random.Random(seed)

    def score_pairs(self, questions: Sequence[str], answers: Sequence[str], **kwargs: Any) -> torch.Tensor:
        return self.model.score_pairs(questions, answers, n_masks=self.n_masks,
                                      rng=self.rng, **kwargs)

    __call__ = score_pairs

    def energy(self, questions: Sequence[str], answers: Sequence[str], **kwargs: Any) -> torch.Tensor:
        # For the ablation the "energy" is a negated log-probability so that lower is
        # better, matching the EnergyModel convention used by beam search.
        return -self.score_pairs(questions, answers, **kwargs)


# --------------------------------------------------------------------------------------
# Loss module (drop-in alternative to RankingNCELoss)
# --------------------------------------------------------------------------------------


class MaskedLMLoss(nn.Module):
    """``nn.Module`` wrapper exposing the MLM ablation through a loss-like interface.

    Usage::

        loss_fn = MaskedLMLoss(model=my_mlm_adapter)      # or MaskedLMLoss(config=...)
        loss = loss_fn(positive_texts)                    # ground-truth chunks
        loss = loss_fn(questions=qs, positive_answers=ys) # text pairs

    The signature accepts the same keyword names as
    :class:`~bbox_adapter.losses.nce.RankingNCELoss` (``questions``,
    ``positive_answers``) so the online-adaptation loop can swap objectives via
    ``get_loss("mlm")`` without further changes; negatives are ignored, as the paper's
    MLM ablation uses ground-truth masked-word supervision only.
    """

    def __init__(
        self,
        config: Optional[MLMLossConfig] = None,
        *,
        model: Optional[MLMAdapter] = None,
        tokenizer: Optional[Any] = None,
        **kwargs: Any,
    ) -> None:
        super().__init__()
        cfg = config if isinstance(config, MLMLossConfig) else MLMLossConfig.from_dict(config or {})
        for k, v in kwargs.items():
            if hasattr(cfg, k):
                setattr(cfg, k, v)
        self.config = cfg
        self.model = model if model is not None else MLMAdapter(cfg, tokenizer=tokenizer)
        self.rng = random.Random(int(cfg.seed))
        self._last_stats: Dict[str, float] = {}

    # -- helpers ----------------------------------------------------------------
    @property
    def tokenizer(self) -> Any:
        return self.model.tokenizer

    def _texts_from_inputs(
        self,
        texts: Optional[Sequence[str]] = None,
        questions: Optional[Sequence[str]] = None,
        positive_answers: Optional[Sequence[str]] = None,
    ) -> List[str]:
        if texts is not None:
            return [str(t) for t in texts]
        if questions is not None and positive_answers is not None:
            return [f"Question: {q}\nAnswer: {a}" for q, a in zip(questions, positive_answers)]
        if positive_answers is not None:
            return [str(t) for t in positive_answers]
        raise ValueError("no text supplied to the MLM loss")

    def forward(
        self,
        texts: Optional[Sequence[str]] = None,
        *,
        questions: Optional[Sequence[str]] = None,
        positive_answers: Optional[Sequence[str]] = None,
        negative_answers: Optional[Sequence[Any]] = None,  # ignored (ablation)
        batch: Optional[Dict[str, torch.Tensor]] = None,
        return_stats: bool = False,
        **_: Any,
    ) -> Union[torch.Tensor, Tuple[torch.Tensor, Dict[str, float]]]:
        chunks: List[str] = []
        if batch is None:
            raw = self._texts_from_inputs(texts, questions, positive_answers)
            for t in raw:
                chunks.extend(split_text_chunks(t, self.config.extra.get("chunk_max_words", 128)) or [t])
            batch = self.model.batch(chunks, rng=self.rng, device=self.model.device)
        logits = self.model.forward(batch["input_ids"], batch.get("attention_mask"))
        loss = compute_mlm_loss(
            logits,
            batch["labels"],
            batch.get("attention_mask"),
            reduction=self.config.reduction,
            ignore_index=self.config.ignore_index,
            label_smoothing=self.config.label_smoothing,
        )
        if not return_stats:
            return loss
        with torch.no_grad():
            prob = masked_word_probability(
                logits.detach(), batch["labels"], batch["mask_positions"],
                ignore_index=self.config.ignore_index, reduction="mean",
            )
        stats = {
            "loss": float(loss.detach().item()),
            "masked_word_prob": float(prob.item()),
            "n_masked": float(batch["mask_positions"].sum().item()),
            "n_sequences": float(batch["labels"].shape[0]),
        }
        self._last_stats = stats
        return loss, stats

    def score_pairs(self, questions: Sequence[str], answers: Sequence[str], **kw: Any) -> torch.Tensor:
        return self.model.score_pairs(questions, answers, **kw)


# --------------------------------------------------------------------------------------
# Functional end-to-end helpers
# --------------------------------------------------------------------------------------


def mlm_loss_from_model(
    model: Any,
    texts: Optional[Sequence[str]] = None,
    positive_answers: Optional[Sequence[str]] = None,
    *,
    questions: Optional[Sequence[str]] = None,
    config: Optional[MLMLossConfig] = None,
    rng: Optional[random.Random] = None,
    return_stats: bool = False,
):
    """Compute the MLM ablation loss through an ``MLMAdapter`` / ``MaskedLMLoss``."""
    cfg = config or getattr(model, "config", None) or MLMLossConfig()
    if hasattr(model, "loss"):
        batch = None
        if isinstance(model, MaskedLMLoss):
            return model(
                texts=texts,
                questions=questions,
                positive_answers=positive_answers,
                return_stats=return_stats,
            )
        if texts is None:
            if questions is not None and positive_answers is not None:
                texts = [f"Question: {q}\nAnswer: {a}" for q, a in zip(questions, positive_answers)]
            elif positive_answers is not None:
                texts = list(positive_answers)
        if texts is None:
            raise ValueError("no text supplied to the MLM loss")
        chunks: List[str] = []
        for t in texts:
            chunks.extend(split_text_chunks(t, cfg.extra.get("chunk_max_words", 128)) or [t])
        batch = model.batch(chunks, rng=rng, device=getattr(model, "device", None))
        logits = model.forward(batch["input_ids"], batch.get("attention_mask"))
        loss = compute_mlm_loss(
            logits, batch["labels"], batch.get("attention_mask"),
            reduction=cfg.reduction, ignore_index=cfg.ignore_index,
            label_smoothing=cfg.label_smoothing,
        )
        if not return_stats:
            return loss
        with torch.no_grad():
            prob = masked_word_probability(
                logits.detach(), batch["labels"], batch["mask_positions"],
                ignore_index=cfg.ignore_index, reduction="mean",
            )
        return loss, {
            "loss": float(loss.detach().item()),
            "masked_word_prob": float(prob.item()),
            "n_masked": float(batch["mask_positions"].sum().item()),
        }
    raise TypeError("model must expose a `.loss(...)` method (MLMAdapter / MaskedLMLoss)")


# --------------------------------------------------------------------------------------
# Self test
# --------------------------------------------------------------------------------------


def _self_test() -> None:
    """Dependency-free checks of masking + objective math (no transformers needed)."""
    rng = random.Random(0)
    text = "The answer is 21 because three times seven equals twenty one."
    spans = word_spans(text)
    assert len(spans) == 10, spans
    masked, removed = apply_random_mask(text, tokenizer=None, config=MLMLossConfig(seed=3), rng=rng)
    assert "[MASK]" in masked and removed, (masked, removed)
    assert "The answer is" in masked

    # word-level selection
    word_ids = [None, 0, 0, 1, 2, 3, None]
    pos = select_mask_word_indices(word_ids, mask_prob=1.0, max_masks=10, rng=random.Random(0))
    assert pos == [1, 2, 3, 4, 5], pos
    pos_forced = select_mask_word_indices(word_ids, forced_word=2)
    assert pos_forced == [4], pos_forced

    # objective: loss decreases as the true masked word probability rises
    B, L, V = 2, 4, 7
    labels = torch.full((B, L), -100, dtype=torch.long)
    labels[0, 1] = 3
    labels[1, 2] = 5
    good = torch.zeros(B, L, V)
    good[0, 1, 3] = 20.0
    good[1, 2, 5] = 20.0
    bad = torch.zeros(B, L, V)
    bad[0, 1, 3] = -20.0
    bad[1, 2, 5] = -20.0
    l_good = compute_mlm_loss(good, labels)
    l_bad = compute_mlm_loss(bad, labels)
    assert float(l_good) < float(l_bad), (l_good, l_bad)
    p_good = masked_word_probability(good, labels)
    assert float(p_good) > 0.9, p_good
    scores = sentence_masked_word_score(good, labels, mode="logprob")
    assert scores.shape == (B,)
    assert float(scores[0]) > 0.0

    # gradient flows into the logits
    logits = torch.zeros(B, L, V, requires_grad=True)
    compute_mlm_loss(logits, labels).backward()
    assert logits.grad is not None and float(logits.grad.abs().sum()) > 0.0

    # chunking
    chunks = split_text_chunks("a b c d e", max_words=2)
    assert chunks == ["a b", "c d", "e"], chunks


if __name__ == "__main__":  # pragma: no cover
    _self_test()
    print("mlm.py self-test passed")
